### ISSUE TITLE
Empty url results in crash in RN Android 

### ISSUE THREAD

**Issue by harshsrivastavaglobussoft** [axios/axios#1115]
`   export const peopleSearch = ({ name, location, navigation }) => {
	  console.log('People_Name: '+ name +' Location: '+location);
	  console.log("Search Url ============");
	  console.log(config.SEARCH_URL);

	const search_name = name;

	return (dispatch) => {
		axios.post(config.SEARCH_URL, {
				search_type: "people",
				searchCriteria1: name,
			})
			.then( data => {
				console.log(data);
				if(data.data.message === 'Success'){
					console.log("success")
					peopleSearchSuccess(dispatch, data, search_name, navigation)
				}else{
					console.log("Failed")
					peopleSearchFailed(dispatch)
				}
			})
			.catch(error => console.log(error.response))
	}
}
`
in Android I am getting error 

`0-05 07:44:20.068 1063-1245/com.d########ka E/unknown:ReactNative: Exception in native call
                                                                   java.lang.IllegalArgumentException: unexpected url: undefinedsearch-details
                                                                       at okhttp3.Request$Builder.url(Request.java:142)
                                                                       at com.facebook.react.modules.network.NetworkingModule.sendRequest(NetworkingModule.java:171)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                                       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
                                                                       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
                                                                       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                       at android.os.Handler.handleCallback(Handler.java:615)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                       at android.os.Looper.loop(Looper.java:137)
                                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                                       at java.lang.Thread.run(Thread.java:856)
![screen shot 2017-10-05 at 1 34 33 pm](https://user-images.githubusercontent.com/24026483/31216812-82b32670-a9d2-11e7-8096-4ad8518cf525.png)

`

**Comment by sabakugaara** [comment]
maybe you should check variable `config.SEARCH_URL`, I think it is `undefined`, not a axios bug

**Comment by ekimlinger** [comment]
Axios should still be throwing some kind of js error in this case though. (Also experiencing the same issue) This is an exception being thrown at the android level which is something that axios should be able to catch.

**Comment by chinesedfan** [comment]
Closed in favor of #3110.
