### ISSUE TITLE
Not handled error when try to convert buffer to string

### ISSUE THREAD

**Issue by rapkin** [axios/axios#1146]
__Summary__

Hi, I have part of code which checks status of link:

```js
let status
try {
    let res = await axios.head(link)
    status = res.status
} catch(err) {
    status = err.response && err.response.status || 500
}
console.log(`[${status}] ${link}`)
```

Here error (not handled by try/catch):

```
buffer.js:554
      if (encoding === 'utf8') return buf.utf8Slice(start, end);
                                          ^

Error: "toString()" failed
    at stringSlice (buffer.js:554:43)
    at Buffer.toString (buffer.js:627:10)
    at IncomingMessage.handleStreamEnd (/home/rapkin/cdn-handler/node_modules/axios/lib/adapters/http.js:186:41)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1057:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

I see that problem occurs at this line https://github.com/axios/axios/blob/master/lib/adapters/http.js#L186

I think this happens when try to load very big file (gif ~ 400mb), but i'm not sure.
Sorry I can't give you more info about this issue.
We realy need some errors handling at that place to receive more debug info.

__Context__

- axios version: 0.17.0
- Environment: nodejs v8.7.0, Ubuntu 16.04

**Comment by chinesedfan** [comment]
Noticed that it was a HEAD request and closed in favor of #2665.
