### ISSUE TITLE
Node.js Failures

### ISSUE THREAD

**Issue by bradennapier** [axios/axios#1163]
#### Summary

Not sure if this is due to Node 9.0 but axios definitely does not work on it.

```
 {
   "url": "<path>",
   "method": "POST",
   "baseURL": "<url>",
   "timeout": 15000,
   "headers": {
     "Header-Name": "Header-Value"
   },
   "data": {
     "some": "data"
   }
 }
```

-->

```
0|developm | 3:17:59:936 am | [SERVER] |  [ERROR] | API REQUEST | Error Caught during Request |  HyxwGat0W session /v2/system/session TypeError [ERR_MISSING_ARGS]: The "value" argument must be specified
0|developm |     at validateHeader (_http_outgoing.js:501:11)
0|developm |     at ClientRequest.setHeader (_http_outgoing.js:510:3)
0|developm |     at new ClientRequest (_http_client.js:173:14)
0|developm |     at Object.request (https.js:241:10)
0|developm |     at RedirectableRequest._performRequest (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-datastream/apps/datastream/node_modules/follow-redirects/index.js:73:20)
0|developm |     at new RedirectableRequest (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-datastream/apps/datastream/node_modules/follow-redirects/index.js:57:7)
0|developm |     at Object.wrappedProtocol.request (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-datastream/apps/datastream/node_modules/follow-redirects/index.js:229:10)
0|developm |     at dispatchHttpRequest (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-datastream/apps/datastream/node_modules/axios/lib/adapters/http.js:130:25)
0|developm |     at new Promise (<anonymous>)
0|developm |     at httpAdapter (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-datastream/apps/datastream/node_modules/axios/lib/adapters/http.js:18:10)
```

#### Context

- axios version: 0.17.0
- Environment: 9.0 OSX

**Comment by bradennapier** [comment]
Ok -- cryptic error that didnt actualy say a header was undefined.  I had lookeda t the values and they were all there but it was due to another issue occurring elsewhere. 

Might be good to wrap this and provide a real error :-P

**Comment by adibkadir** [comment]
I'm hitting the same error when making get requests using axios and node v9.6.1.

`[ERR_MISSING_ARGS]: The "value" argument must be specified`

It worked just seconds before on node 6.x prior to the upgrade.

**Comment by jplew** [comment]
I was getting the same `The "value" argument must be specified`. Using Node 9.5.0 and Axios 0.18.0.

My fix was similar to @adibkadir, I wasn't specifiying some required config parameters, apparently. I found this weird, considering my server was working fine when hosting it from Heroku, but suddenly started showing this bug when I migrated to Google Cloud Functions. At any rate, in case anyone finds it useful here is my before after:

Before:
    const config = {
      headers: {
        Accept: 'application/json',
        app_id: process.env.OXFORD_ID,
        app_key: process.env.OXFORD_KEY,
      },
    }

    app.get('/api/oxford/inflect/:word', (req, res) => {
      axios
        .get(`${oxfordInflect}/${req.params.word}`, config)
        .then(response => {
          res.json(response.data)
        })
        .catch(err => {
          handleError(err, res)
        })
    })

After:

    function getConfigObj(type: string, word: string): ConfigObject {
      console.log(host)
      console.log('word', word)

      return {
        method: 'GET',
        url: host + type + word,
        headers: {
          Accept: 'application/json',
          app_id: process.env.OXFORD_ID,
          app_key: process.env.OXFORD_KEY,
        },
      }
    }

    app.get('/api/oxford/inflection/:word', (req, res) => {
      const type = '/inflections/en/'
      console.log(getConfigObj(type, req.params.word))

      axios(getConfigObj(type, req.params.word))
        .then(response => res.json(response.data))
        .catch(function(error) {
          console.log(error)
        })
    })

**Comment by gomezmark** [comment]
@adibkadir have you resolve your issue?
thanks

**Comment by chanchalvashistha** [comment]
I am hitting same error with node v9.11.2. I am stuck in between my project starts throwing error now . Try to provide the solution.

Find the stackrace as below
`[ERR_MISSING_ARGS]: The "value" argument must be specified
    at validateHeader (_http_outgoing.js:501:11)
    at ClientRequest.setHeader (_http_outgoing.js:510:3)
    at new ClientRequest (_http_client.js:208:14)
    at Object.request (https.js:275:10)
    at Object.request (/Users/chanchalvashistha/workspace/boons-workspace/boons-rc-api/node_modules/agent-base/patch-core.js:23:20)
    at RedirectableRequest._performRequest (/Users/chanchalvashistha/workspace/boons-workspace/boons-rc-api/node_modules/follow-redirects/index.js:169:24)
    at new RedirectableRequest (/Users/chanchalvashistha/workspace/boons-workspace/boons-rc-api/node_modules/follow-redirects/index.js:66:8)
    at Object.wrappedProtocol.request (/Users/chanchalvashistha/workspace/boons-workspace/boons-rc-api/node_modules/follow-redirects/index.js:307:14)
    at dispatchHttpRequest (/Users/chanchalvashistha/workspace/boons-workspace/boons-rc-api/node_modules/axios/lib/adapters/http.js:141:25)
    at new Promise (<anonymous>)
    at httpAdapter (/Users/chanchalvashistha/workspace/boons-workspace/boons-rc-api/node_modules/axios/lib/adapters/http.js:18:10)
    at dispatchRequest (/Users/chanchalvashistha/workspace/boons-workspace/boons-rc-api/node_modules/axios/lib/core/dispatchRequest.js:59:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
`

**Comment by ganeshjangid** [comment]
TypeError [ERR_MISSING_ARGS]: The "name" and "value" arguments must be specified

i am getting this error
