### ISSUE TITLE
PUT of binary data seems to be corrupted

### ISSUE THREAD

**Issue by NuSkooler** [axios/axios#1250]
**Summary**

Performing a `PUT` of binary data seems to result in corrupted data. 

Example:
```
const itemStream = createReadStream(`/path/to/somefile.ovf`); // file is actually an XML file
return axios({
  method  : 'PUT',
  url     : endpointUrl,
  headers : {
    'Content-Type' : 'application/octet-stream',
    'Accept' : 'application/json',
  },
  data    : itemStream,
});
```

In this case I'm `PUT`ing to a VMWare vCenter server. The `PUT` results in a 200 OK, but upon further inspection, the server believes the data is corrupted.

However, `PUY`ing the same file to the same URL via Postman works. In Postman I'm setting the same headers and using binary file upload. If upload via Postman using different means I get the same error presented when using axios as described above.

**Context**

- axios version: *e.g.: v0.17.1*
- Environment: *Electron*

**Comment by NuSkooler** [comment]
Sorry to "bump" this, but are there obvious issues with the code above? I'm reaching the point in which I need to get this fixed or switch to the `request` library :(

**Comment by ablankenship10** [comment]
Having same issue. I'm uploading a file to S3 from the Chrome FileReader API on the browser. The file data is loaded the correct size(48kb) and then when Axios goes to upload the file it comes out in S3 as 70.7kb and im unable to open the file (zip file). I've tried loading it using all the Filereader.readAs options to the same result. Console.Logging the result shows the correct file size, its only with axios progress event logs that it shows the almost twice the filesize amount.


```
return fileReader(file)
          .then((result) => {
            return axios.put(fileurl, result, {
              onUploadProgress: progressEvent => console.log('file progress', progressEvent.loaded),
              headers: { 'Content-Type': 'text/octet-stream' }
            });
          })


function fileReader(file){
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = (e) => {
        resolve(reader.result)
      };

      reader.readAsBinaryString(file)
    })
  }

```

**Comment by Remigius2011** [comment]
Had the same issue. I resolved it by using `reader.readAsArrayBuffer` instead of `reader.readAsBinaryString`. See also:

https://github.com/axios/axios#request-config - description of `data`
https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsArrayBuffer
https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsBinaryString

(it seems also that there is wider browser support for  `reader.readAsArrayBuffer`).

**Comment by yang-f** [comment]
> Having same issue. I'm uploading a file to S3 from the Chrome FileReader API on the browser. The file data is loaded the correct size(48kb) and then when Axios goes to upload the file it comes out in S3 as 70.7kb and im unable to open the file (zip file). I've tried loading it using all the Filereader.readAs options to the same result. Console.Logging the result shows the correct file size, its only with axios progress event logs that it shows the almost twice the filesize amount.
> 
> ```
> return fileReader(file)
>           .then((result) => {
>             return axios.put(fileurl, result, {
>               onUploadProgress: progressEvent => console.log('file progress', progressEvent.loaded),
>               headers: { 'Content-Type': 'text/octet-stream' }
>             });
>           })
> 
> 
> function fileReader(file){
>     return new Promise((resolve, reject) => {
>       const reader = new FileReader();
>       reader.onload = (e) => {
>         resolve(reader.result)
>       };
> 
>       reader.readAsBinaryString(file)
>     })
>   }
> ```

`transformRequest` would solve this problem perfectly.

**Comment by David-dp-** [comment]
I'm having the same problem when trying to PUT a range of bytes using Box.com's REST API.

The error trace is:
"message":"Request failed with status code 400","name":"Error","stack":"Error: Request failed with status code 400\n    at createError (/var/task/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/var/task/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/var/task/node_modules/axios/lib/adapters/http.js:237:11)\n    at IncomingMessage.emit (events.js:203:15)\n    at IncomingMessage.EventEmitter.emit (domain.js:448:20)\n    at endReadableNT (_stream_readable.js:1143:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"

@yang-f I removed the Typescript typing of your parameters and tried your workaround, but it made no difference. It's also not clear to me what transformation is done, if any, to the request.

**Comment by jeremy21212121** [comment]
There is no transformation being done in that `tranformRequest` function posted by yang. It is merely logging the data.

I think his intention was to show where one can perform the necessary transformations, not to provide working code.

**Comment by voortwis** [comment]
Used the `transformRequest` too. Removed the logging and now it works (sending a protobuf to hyperledger-sawtooth). With the code removed the first char sent is a /n (newline). Maybe there is another way to solve this in the bowels of axios?
