### ISSUE TITLE
Axios throws 404 after returning 200 response

### ISSUE THREAD

**Issue by selfagency** [axios/axios#1426]
#### Summary

this is happening to me *after* issuing a 200 response for no explicable reason
```
    >> Error: Request failed with status code 404
    >>     at createError (/Users/daniel/Dev/nylon-web/node_modules/axios/lib/core/createError.js:16:15)
    >>     at settle (/Users/daniel/Dev/nylon-web/node_modules/axios/lib/core/settle.js:18:12)
    >>     at IncomingMessage.handleStreamEnd (/Users/daniel/Dev/nylon-web/node_modules/axios/lib/adapters/http.js:201:11)
    >>     at emitNone (events.js:110:20)
    >>     at IncomingMessage.emit (events.js:207:7)
    >>     at endReadableNT (_stream_readable.js:1059:12)
    >>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
    >>     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

here's my code
```
/* fetch data */
async function fetch (apiCall, type) {
  const response = await axios(encodeURI(apiCall), {
    maxRedirects: 0,
    validateStatus() { return true }
  })

  let out
  if (response.status === 200) {
    if (validJson(type, response.data)) {
      out = response.data
      out.status = 200
    } else {
      out = new Error(`API returned invalid JSON for ${apiCall}.`)
      out.status = 417
    }
  } else {
    out = errorHandler({ status: response.status })
  }

  log.info(`${type} out: ${out.status}`)
  return is.err(out) ? Promise.reject(out) : Promise.resolve(out)
}
```

here's the result, 200s all the way down but still 404s somehow

```
[2018-03-16T17:24:01.049Z]  INFO: nylon/71301 on selfagency-macpro: API call: https://api.nylon.com/api/v2/article/lcd-soundsystem-and-the-absurd-politics
[2018-03-16T17:24:04.274Z]  INFO: nylon/71301 on selfagency-macpro: article out: 200
[2018-03-16T17:24:04.288Z]  INFO: nylon/71301 on selfagency-macpro: article cache out: 200 | bad? false | {"id":38888,"published":"2018-03-16T12:00:00-04:00","updated":"2018-03...
[2018-03-16T17:24:04.291Z]  INFO: nylon/71301 on selfagency-macpro: API call: https://api.nylon.com/api/v2/author/tanner-howard
[2018-03-16T17:24:04.292Z]  INFO: nylon/71301 on selfagency-macpro: API call: https://api.nylon.com/api/v2/post/38888/related
[2018-03-16T17:24:04.476Z]  INFO: nylon/71301 on selfagency-macpro: related out: 200
[2018-03-16T17:24:04.500Z]  INFO: nylon/71301 on selfagency-macpro: related cache out: 200 | bad? false | {"related":[{"id":38888,"published":"2018-03-16T12:00:00-04:00","updat...
[2018-03-16T17:24:05.046Z]  INFO: nylon/71301 on selfagency-macpro: author out: 200
[2018-03-16T17:24:05.049Z]  INFO: nylon/71301 on selfagency-macpro: author cache out: 200 | bad? false | {"type":"author-page","category":"author","author":{"url":"tanner-howa...
    raven@2.4.2 alert: failed to send exception to sentry: HTTP Error (413): undefined
    >> Error: Request failed with status code 404
    >>     at createError (/Users/daniel/Dev/nylon-web/node_modules/axios/lib/core/createError.js:16:15)
    >>     at settle (/Users/daniel/Dev/nylon-web/node_modules/axios/lib/core/settle.js:18:12)
    >>     at IncomingMessage.handleStreamEnd (/Users/daniel/Dev/nylon-web/node_modules/axios/lib/adapters/http.js:201:11)
    >>     at emitNone (events.js:110:20)
    >>     at IncomingMessage.emit (events.js:207:7)
    >>     at endReadableNT (_stream_readable.js:1059:12)
    >>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
    >>     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
    [nodemon] app crashed - waiting for file changes before starting...
```

#### Context

- axios version: 0.18.0
- Environment: node 8.4.0 – occurs on mac and linux

**Comment by selfagency** [comment]
never mind it was a separate call causing the 404
