### ISSUE TITLE
why did not support https request?

### ISSUE THREAD

**Issue by msforest** [axios/axios#1527]
#### why did not support https request?
```
function test(){
    axios({
        method: 'get',
        url: 'https://www.xxx.com/rest/api/latest/search?project=FPB',
    }).then((e, r)=>{
        console.log('then', e, r)
    }).catch(e=>{
        console.log('catch', e);
    })
}
```
it will be hang up
```
Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1124:19)
    at TLSSocket.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'ECONNRESET',
```

After that, I try use node https module, it is okay. 
```
const http = require("https");

function test(){
    var options = {
      "method": "GET",
      "hostname": "www.xxx.com",
      "path": "/rest/api/latest/search?project=FPB",
    };
    
    var req = http.request(options, function (res) {
      var chunks = [];
    
      res.on("data", function (chunk) {
        chunks.push(chunk);
      });
    
      res.on("end", function (d) {
        console.log('no errors', chunks.toString());
      });
    });
    req.on("error", function (e) {
        console.log(JSON.stringify(e));
    });
    req.end();
}
```
So, why not support https request via wrap node module? thanks.

#### Context

- axios version: *e.g.: v0.18.0*
- Environment: *e.g.: node v6.11.5,  ubuntu 16.04*

**Comment by msforest** [comment]
test that case is in node v6.x.  today, i test no problem when use v8.9
