### ISSUE TITLE
Why GET requests has header of 'Content-Length' 

### ISSUE THREAD

**Issue by hectorqin** [axios/axios#1659]
Sometimes the get request will have a 'Content-Length' header, which causes the nginx server to wait for the remaining body and then cause a timeout.  I can't figure out why this happen.

This request is very simple as below，it occurs during the nuxtServerInit phase of the nuxt service

![image](https://user-images.githubusercontent.com/14220132/42405854-c530817a-81cf-11e8-824c-d7a7b9402753.png)

Below is the error log

```
{ Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  code: 'ECONNRESET',
  config: 
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers: 
      { Accept: 'application/json, text/plain, */*',
        'x-real-ip': '117.136.41.54',
        'x-forwarded-for': '117.136.41.54',
        'x-forwarded-proto': 'https',
        connection: 'close',
        'content-length': '40',
        'content-type': 'application/x-www-form-urlencoded',
        'x-requested-with': 'XMLHttpRequest',
        'accept-language': 'zh-cn',
        'accept-encoding': 'br, gzip, deflate',
        origin: 'https://f.xuelele.dsmake.com',
        referer: 'https://f.xuelele.dsmake.com/Api/Pay/unReturn?orderId=74F449738F25497ABCD8812B0A94BCC4&partyId=FCBD8DD510D04CE8B905919330C99B0E',
        'user-agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E302 Version/11.0 Safari/604.1',
        cookie: 'PHPSESSID=5p1id0m632pfd32mk6ph85nsp7; CNZZDATA1261106501=793224775-1530695821-%7C1530695821; UM_distinctid=1646498da07c44-06f4af9e73b52-787d4176-3d10d-1646498da08b73' },
     method: 'get',
     baseURL: 'http://xuelele.dsmake.com/appserver',
     url: 'http://xuelele.dsmake.com/appserver/Login/auth?',
     params: { jrPlatform: 'WAP' },
     withCredentials: true,
     data: undefined },
  request: 
   Writable {
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     domain: null,
     _events: 
      { response: [Function: handleResponse],
        error: [Function: handleRequestError] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _options: 
      { protocol: 'http:',
        maxRedirects: 21,
        maxBodyLength: 10485760,
        path: '/appserver/Login/auth?&jrPlatform=WAP',
        method: 'get',
        headers: [Object],
        agent: undefined,
        auth: undefined,
        hostname: 'xuelele.dsmake.com',
        port: null,
        nativeProtocols: [Object],
        pathname: '/appserver/Login/auth',
        search: '?&jrPlatform=WAP' },
     _redirectCount: 0,
     _requestBodyLength: 0,
     _requestBodyBuffers: [],
     _onNativeResponse: [Function],
     _currentRequest: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /appserver/Login/auth?&jrPlatform=WAP HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nx-real-ip: 117.136.41.54\r\nx-forwarded-for: 117.136.41.54\r\nx-forwarded-proto: https\r\nconnection: close\r\ncontent-length: 40\r\ncontent-type: application/x-www-form-urlencoded\r\nx-requested-with: XMLHttpRequest\r\naccept-language: zh-cn\r\naccept-encoding: br, gzip, deflate\r\norigin: https://f.xuelele.dsmake.com\r\nreferer: https://f.xuelele.dsmake.com/Api/Pay/unReturn?orderId=74F449738F25497ABCD8812B0A94BCC4&partyId=FCBD8DD510D04CE8B905919330C99B0E\r\nuser-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E302 Version/11.0 Safari/604.1\r\ncookie: PHPSESSID=5p1id0m632pfd32mk6ph85nsp7; CNZZDATA1261106501=793224775-1530695821-%7C1530695821; UM_distinctid=1646498da07c44-06f4af9e73b52-787d4176-3d10d-1646498da08b73\r\nHost: xuelele.dsmake.com\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/appserver/Login/auth?&jrPlatform=WAP',
        _ended: false,
        res: null,
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Circular],
        [Symbol(outHeadersKey)]: [Object] },
     _currentUrl: 'http://xuelele.dsmake.com/appserver/Login/auth?&jrPlatform=WAP' },
  response: undefined,
  statusCode: 500,
  name: 'NuxtServerError' }
```

#### Context

- axios version: v0.18.0*
- Environment:  node v8.11.1, PM2 v2.10.2, CentOS 6.5*

**Comment by delirius325** [comment]
Hey @hectorqin,

I'm curious about this one. I'm not sure how the Content-Length is being set since your config.data is undefined. In the http adapter of axios we can see the following:

```javascript
// lib/adapters/http.js - line 54
// Add Content-Length header if data exists
headers['Content-Length'] = data.length;
```

Unless I'm missing something (which is possible), that line should throw an error since you can't access the length of _undefined_.

Were you able to investigate a little further?
Thanks,

**Comment by fed135** [comment]
Hey, thanks for submitting this issue. Since it has been inactive for a while and that our resources for maintaining and triaging are limited, we will be closing this ticket. If the issue persists on your end, please feel free to open a new issue.
