### ISSUE TITLE
problem  Error: connect EMFILE 

### ISSUE THREAD

**Issue by yangchongduo** [axios/axios#1662]
在node 通过axios 调用其他服务 

日志

```
body: 
      { Error: connect EMFILE xx.xx.xx.xx:80 - Local (undefined:undefined)
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at internalConnect (net.js:976:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:283:19)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1122:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
        code: 'EMFILE',
        errno: 'EMFILE',
        syscall: 'connect',
```
监控 ：服务tcp  close_wait 数突然由0增加到 4k

给点方向 这是什么引起的？
谢谢

**Comment by fed135** [comment]
Hey, thanks for logging this issue. This sounds like a support issue. For these, we encourage you to post on StackOverflow, or to use our [Gitter](https://gitter.im/mzabriskie/axios). For now, we're going to close this issue, as it is not feature or bug specific to Axios. If you feel this is an error, let us know.
