### ISSUE TITLE
axios non-error thrown: [Circular]

### ISSUE THREAD

**Issue by fridaydream** [axios/axios#1700]
* nodejs I post a request ,but get error of 400. I try the postman to get that post request,it's ok.

and I also use request-promise package to do a post request, it's ok. I don't how to resolve it with axios. 

thank you !

my code
```
let result = await new Promise((resolve, reject) => {
    axios.post(`${baseUrl}/accesstoken`, {
      accesstoken: ctx.request.body.accessToken
    })
      .then(resp => {
        resolve(resp)
      })
      .catch(err =>{
        reject(err.response)
      })
  })
```

error

```
Error: non-error thrown: [Circular]
      at Object.onerror (/Users/chenpan/Documents/react-jocket/node_modules/koa/lib/context.js:109:40)
      at onerror (/Users/chenpan/Documents/react-jocket/node_modules/koa/lib/application.js:147:32)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by fridaydream** [comment]
in the end, I found that I have write the worry address, https => http. But postman is ok,request-promise give me 404, but axios give me this error message, I don't think it is easy for people to understand that.
