### ISSUE TITLE
Request failed with status code 503 while trying to get response of an api using axios

### ISSUE THREAD

**Issue by rajitgargkohls** [axios/axios#1780]
Hi,

I am using axios to fetch response of one of the Api/Url, I am successfully able to fetch its value from my React Client side code, but when I am setting express endpoint for this at server side and calling below endpoint from the browser 

```
app.get('/health', function (req, res) {
var url = serviceUrl + '/actuator/health';
axios.get(url)
    .then((response) => {
      const data = response.data;
      console.log("data>>>>>>>>>>>", data);
      res.json(data);
    })
    .catch((err) => {
      console.log("err :::: ", err);
      res.json({ status: 'DOWN' })
    })
});
```
then I am getting below error

err ::::  
**{ Error: Request failed with status code 503
     at createError (/deployments/packages/Portal/node_modules/axios/lib/core/createError.js:16:15)
     at settle (/deployments/packages/Portal/node_modules/axios/lib/core/settle.js:18:12)
     at IncomingMessage.handleStreamEnd (/deployments/packages/Portal/node_modules/axios/lib/adapters/http.js:192:11)
     at emitNone (events.js:111:20)
     at IncomingMessage.emit (events.js:208:7)
     at endReadableNT (_stream_readable.js:1055:12)
     at _combinedTickCallback (internal/process/next_tick.js:138:11)
     at process._tickCallback (internal/process/next_tick.js:180:9)
   config: 
    { adapter: [Function: httpAdapter],
      transformRequest: { '0': [Function: transformRequest] },
      transformResponse: { '0': [Function: transformResponse] },
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      validateStatus: [Function: validateStatus],
      headers: 
       { Accept: 'application/json, text/plain, */*',
         'User-Agent': 'axios/0.17.1',
         host: 'xxxxxxxxx' },
      method: 'get',
      url: 'http://xxxxxxxxx/actuator/health' ,
      data: undefined },
   request: 
    ClientRequest {
      domain: null,
      _events: 
       { socket: [Function],
         abort: [Function],
         aborted: [Function],
         error: [Function],
         timeout: [Function],
         prefinish: [Function: requestOnPrefinish] },
      _eventsCount: 6,
      _maxListeners: undefined,
      output: [],
      outputEncodings: [],
      outputCallbacks: [],
      outputSize: 0,
      writable: true,
      _last: true,
      upgrading: false,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: 
       Socket {
         connecting: false,
         _hadError: false,
         _handle: null,
         _parent: null,
         _host: 'proxy-gcp-central.kohls.com',
         _readableState: [Object],
         readable: false,
         domain: null,
         _events: [Object],
         _eventsCount: 8,
         _maxListeners: undefined,
         _writableState: [Object],
         writable: false,
         allowHalfOpen: false,
         _bytesDispatched: 248,
         _sockname: null,
         _pendingData: null,
         _pendingEncoding: '',
         server: null,
         _server: null,
         parser: null,
         _httpMessage: [Circular],
         read: [Function],
         _consuming: true,
         _idleNext: null,
         _idlePrev: null,
         _idleTimeout: -1,
         [Symbol(asyncId)]: 5786,
         [Symbol(bytesRead)]: 1752 },
      connection: 
       Socket {
         connecting: false,
         _hadError: false,
         _handle: null,
         _parent: null,
         _host: 'proxy-gcp-central.kohls.com',
         _readableState: [Object],
         readable: false,
         domain: null,
         _events: [Object],
         _eventsCount: 8,
         _maxListeners: undefined,
         _writableState: [Object],
         writable: false,
         allowHalfOpen: false,
         _bytesDispatched: 248,
         _sockname: null,
         _pendingData: null,
         _pendingEncoding: '',
         server: null,
         _server: null,
         parser: null,
         _httpMessage: [Circular],
         read: [Function],
         _consuming: true,
         _idleNext: null,
         _idlePrev: null,
         _idleTimeout: -1,
         [Symbol(asyncId)]: 5786,
         [Symbol(bytesRead)]: 1752 },
      _header: 'GET http://xxxxxxxxx/actuator/health  HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.17.1\r\nhost: xxxxxxxxx\r\nConnection: close\r\n\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: 
       Agent {
         domain: null,
         _events: [Object],
         _eventsCount: 1,
         _maxListeners: undefined,
         defaultPort: 80,
         protocol: 'http:',
         options: [Object],
         requests: {},
         sockets: [Object],
         freeSockets: {},
         keepAliveMsecs: 1000,
         keepAlive: false,
         maxSockets: Infinity,
         maxFreeSockets: 256 },
      socketPath: undefined,
      timeout: undefined,
      method: 'GET',
      path: 'http://xxxxxxxxx/actuator/health' ,
      _ended: true,
      res: 
       IncomingMessage {
         _readableState: [Object],
         readable: false,
         domain: null,
         _events: [Object],
         _eventsCount: 3,
         _maxListeners: undefined,
         socket: [Object],
         connection: [Object],
         httpVersionMajor: 1,
         httpVersionMinor: 1,
         httpVersion: '1.1',
         complete: true,
         headers: [Object],
         rawHeaders: [Array],
         trailers: {},
         rawTrailers: [],
         upgrade: false,
         url: '',
         method: null,
         statusCode: 503,
         statusMessage: 'DNS Fail',
         client: [Object],
         _consuming: true,
         _dumped: false,
         req: [Circular],
         responseUrl: 'http://proxy-gcp-central.kohls.com/http://xxxxxxxxx/actuator/health' ,
         redirects: [],
         read: [Function] },
      aborted: undefined,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      _redirectable: 
       Writable {
         _writableState: [Object],
         writable: true,
         domain: null,
         _events: [Object],
         _eventsCount: 2,
         _maxListeners: undefined,
         _options: [Object],
         _redirectCount: 0,
         _redirects: [],
         _requestBodyLength: 0,
         _requestBodyBuffers: [],
         _onNativeResponse: [Function],
         _currentRequest: [Circular],
         _currentUrl: 'http://proxy-gcp-central.kohls.com/http://xxxxxxxxx/actuator/health'  },
      [Symbol(outHeadersKey)]: { accept: [Array], 'user-agent': [Array], host: [Array] } },
   response: 
    { status: 503,
      statusText: 'DNS Fail',
      headers: 
       { connection: 'close',
         via: 'HTTP/1.1 proxy10606',
         'content-length': '1660' },
      config: 
       { adapter: [Function: httpAdapter],
         transformRequest: [Object],
         transformResponse: [Object],
         timeout: 0,
         xsrfCookieName: 'XSRF-TOKEN',
         xsrfHeaderName: 'X-XSRF-TOKEN',
         maxContentLength: -1,
         validateStatus: [Function: validateStatus],
         headers: [Object],
         method: 'get',
         url: 'http://xxxxxxxxx/actuator/health' ,
         data: undefined },
      request: 
       ClientRequest {
         domain: null,
         _events: [Object],
         _eventsCount: 6,
         _maxListeners: undefined,
         output: [],
         outputEncodings: [],
         outputCallbacks: [],
         outputSize: 0,
         writable: true,
         _last: true,
         upgrading: false,
         chunkedEncoding: false,
         shouldKeepAlive: false,
         useChunkedEncodingByDefault: false,
         sendDate: false,
         _removedConnection: false,
         _removedContLen: false,
         _removedTE: false,
         _contentLength: 0,
         _hasBody: true,
         _trailer: '',
         finished: true,
         _headerSent: true,
         socket: [Object],
         connection: [Object],
         _header: 'GET http://xxxxxxxxx/actuator/health  HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.17.1\r\nhost: xxxxxxxxx\r\nConnection: close\r\n\r\n',
         _onPendingData: [Function: noopPendingOutput],
         agent: [Object],
         socketPath: undefined,
         timeout: undefined,
         method: 'GET',
         path: 'http://xxxxxxxxx/actuator/health' ,
         _ended: true,
         res: [Object],
         aborted: undefined,
         timeoutCb: null,
         upgradeOrConnect: false,
         parser: null,
         maxHeadersCount: null,
         _redirectable: [Object],**
         
I am getting this issue on cloud environment, I am able to fix this issue on my local by providing proxy information along with url in axios.get function above(as on local I am using proxy server to access this URL), but on cloud we are able to access this directly without use of proxy server, so for cloud, we cannot set this proxy information in this code.

I have tried this with many other node modules like http, request, request-promise, but still I am getting the same issue.

I have also tried to set `Access-Control-Allow-Origin, Access-Control-Allow-Methods, Access-Control-Allow-Headers` in headers as well as in app.use, but none of them resolve my issue.

#### Context

- axios version: *e.g.: v0.17.1*
- Environment: *e.g.: node v8.11.3, npm v6.2.0, chrome 68.0.3440.106 (Official Build) (64-bit), windows 7*

**Comment by arunkumargan** [comment]
+1

**Comment by tinaboyce** [comment]
Experiencing the same issue with axios@0.18.0

**Comment by sivasankars** [comment]
+1, Same Issue :(

**Comment by erisnuts** [comment]
Any solution?

**Comment by jonathanfoster** [comment]
Looks like PR #2562 may resolve this issue. I ran into a similar issue and was able to resolve it by explicitly configuring proxy options and setting the protocol to HTTPS.

```javascript
proxy: {
  host: 'localhost'
  port: 8080,
  protocol: 'https'
}
```

Take a look at PR #3070 for more info.

**Comment by magicdawn** [comment]
![image](https://user-images.githubusercontent.com/4067115/96322775-0a85d000-104d-11eb-8acd-c8498ee7c730.png)
in order to proxy https url, http tunnel (CONNECT method) should be used.
what axios current use: modify url to `proxy + url` may be buggy


case for me:
https://github.com/jeffijoe/typesync/blob/81a10e96a73a2948950513892318cc4e23ffe99c/src/type-definition-source.ts#L4
https://github.com/jeffijoe/typesync/blob/81a10e96a73a2948950513892318cc4e23ffe99c/src/type-definition-source.ts#L16

with `process.env.http_proxy enabled`
cause
![image](https://user-images.githubusercontent.com/4067115/96323077-39e90c80-104e-11eb-9761-00de3a7ba266.png)
![image](https://user-images.githubusercontent.com/4067115/96323212-ba0f7200-104e-11eb-945a-24229f79076a.png)


the NO_PROXY help could help
```fish
# fish
set -x NO_PROXY 'typespublisher.blob.core.windows.net'
```
