### ISSUE TITLE
Requested entity was not found

### ISSUE THREAD

**Issue by ferrantejake** [axios/axios#1916]
Hi there, 

I'm using the JWT functionality in the google-auth-library getting the following error sporadically without any real consistency:

```shell
Error: Requested entity was not found.
at createError (D:\home\site\wwwroot\projects\project\node_modules\axios\lib\core\createError.js:16:15)
at settle (D:\home\site\wwwroot\projects\project\node_modules\axios\lib\core\settle.js:18:12)
at IncomingMessage.handleStreamEnd (D:\home\site\wwwroot\projects\project\node_modules\axios\lib\adapters\http.js:201:11)
at emitNone (events.js:111:20)
at IncomingMessage.emit (events.js:208:7)
at endReadableNT (_stream_readable.js:1064:12)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

The following is the code which I am calling to create this issue:

```javascript
const JWTClient = new JWT(
    email,
    null,
    privateKey,
    [ subject ]
);

await JWTClient.authorize();

JWTClient.request({
    method: 'post',
    url,
    data
});
```

#### Context

- axios version: v0.18.0
- Environment: node v8.10.0, Windows 

Apologies for such vague issue. The stack traces are not very good on my end either.
Thanks in advance!

**Comment by ferrantejake** [comment]
Turns out this is just the response from a standard 404. Case closed.
