### ISSUE TITLE
baseURL not recognized in Node environment

### ISSUE THREAD

**Issue by reintroducing** [axios/axios#2108]
I'm trying to make an axios request on the server, the same one that works fine on the client. The config setup is as follows:
```
{ adapter: [Function: httpAdapter],
  transformRequest: { '0': [Function: transformRequest] },
  transformResponse: { '0': [Function: transformResponse] },
  timeout: 0,
  xsrfCookieName: 'csrftoken',
  xsrfHeaderName: 'X-CSRFToken',
  maxContentLength: -1,
  validateStatus: [Function: validateStatus],
  headers:
   { common: { Accept: 'application/json, text/plain, */*' },
     delete: {},
     get: {},
     head: {},
     post: { 'Content-Type': 'application/x-www-form-urlencoded' },
     put: { 'Content-Type': 'application/x-www-form-urlencoded' },
     patch: { 'Content-Type': 'application/x-www-form-urlencoded' },
     'X-Requested-With': 'XMLHttpRequest',
     Authorization: null,
     'Content-Type': 'application/x-www-form-urlencoded',
     cookie:
      '...removed',
     'accept-language': 'en-US,en;q=0.9',
     'accept-encoding': 'identity',
     accept:
      'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
     'user-agent':
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36',
     'upgrade-insecure-requests': '1',
     'cache-control': 'max-age=0',
     connection: 'close',
     host: 'spothero.local:9000' },
  method: 'get',
  baseURL: 'http://andrew-ssr.sandbox.local/api/v1',
  params: null,
  url: 'users/logged-in/' }
```

When I get the error on the server, this is the traceback:
```
Server request failed: { Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443,
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'csrftoken',
     xsrfHeaderName: 'X-CSRFToken',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'X-Requested-With': 'XMLHttpRequest',
        Authorization: null,
        cookie:
         '...removed',
        'accept-language': 'en-US,en;q=0.9',
        'accept-encoding': 'identity',
        accept:
         'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
        'user-agent':
         'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36',
        'upgrade-insecure-requests': '1',
        'cache-control': 'max-age=0',
        connection: 'close' },
     method: 'get',
     baseURL: 'http://andrew-ssr.sandbox.local/api/v1',
     params: null,
     url: 'http://andrew-ssr.sandbox.local/api/v1/users/logged-in/',
     data: undefined },
  request:
   Writable {
     _writableState:
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        emitClose: true,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     _events:
      { response: [Function: handleResponse],
        error: [Function: handleRequestError] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _options:
      { maxRedirects: 21,
        maxBodyLength: 10485760,
        protocol: 'https:',
        path: '/api/v1/users/logged-in/',
        method: 'GET',
        headers: [Object],
        agent: undefined,
        auth: null,
        hostname: 'spothero.local',
        port: null,
        nativeProtocols: [Object],
        pathname: '/api/v1/users/logged-in/',
        slashes: true,
        host: 'spothero.local',
        hash: null,
        search: null,
        query: null,
        href: 'https://spothero.local/api/v1/users/logged-in/' },
     _ended: true,
     _ending: true,
     _redirectCount: 1,
     _redirects: [],
     _requestBodyLength: 0,
     _requestBodyBuffers: [],
     _onNativeResponse: [Function],
     _currentRequest:
      ClientRequest {
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header:
         'GET /api/v1/users/logged-in/ HTTP/1.1\r\naccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3\r\nX-Requested-With: XMLHttpRequest\r\nAuthorization: null\r\ncookie: ..removed\r\naccept-language: en-US,en;q=0.9\r\naccept-encoding: identity\r\nuser-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36\r\nupgrade-insecure-requests: 1\r\ncache-control: max-age=0\r\nconnection: close\r\nHost: spothero.local\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/api/v1/users/logged-in/',
        _ended: false,
        res: null,
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Circular],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     _currentUrl: 'https://spothero.local/api/v1/users/logged-in/',
     _isRedirect: true },
  response: undefined }
Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
```

What is extremely confusing to me is that in the config portion, the `url` is correct but in the request portion the `_currentUrl` is not and is set to `'https://spothero.local/api/v1/users/logged-in/'`. 

I'm completely stumped as to what is going on here and would really appreciate it if someone has any hints for me on this.

**Comment by reintroducing** [comment]
I've narrowed this down to be a problem elsewhere. While I have no explanation for why the currentUrl is incorrect, thats not actually the issue here. Apologies for the noise.

**Comment by jscottsf** [comment]
Having the same issue.
