### ISSUE TITLE
HPE_INVALID_STATUS with 100 Continue

### ISSUE THREAD

**Issue by ktalebian** [axios/axios#2310]
I'm making creating a FormData request as

```js
const content = fs.createReadStream(localFilePath);
const form = new FormData();
form.append('Content', content, {
  filename: fileName,
  contentType: contentType,
});
```

Then making a POST request using:

```js
const headers = { 'Content-Type': 'multipart/form-data' }
axios.post(url, form, headers);
```

Using `curl` to the URL, the response is like

```
> Accept: */*
> Content-Length: 227
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------2492d184681b2e94
> 
< HTTP/1.1 100 Continue
< HTTP/1.1 201 Created
< Date: Thu, 25 Jul 2019 17:18:46 GMT
< Content-Type: application/json
< Content-Length: 131
< Connection: keep-alive
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since
< Access-Control-Allow-Methods: GET, POST, DELETE, OPTIONS
< Access-Control-Expose-Headers: ETag
< Access-Control-Allow-Credentials: true
< X-Powered-By: AT-5000
< Strict-Transport-Security: max-age=31536000
```

Notice there is a `100 Continue`. When running the axios script I get

```
{ Error: Parse Error
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at TLSSocket.Readable.push (_stream_readable.js:220:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:94:17)
  bytesParsed: 9,
  code: 'HPE_INVALID_STATUS',
```

This even fails if I send an empty form data; it seems like axios doesn't like the 100 Continue state?

**Comment by chinesedfan** [comment]
Closed due to stale. And seems like you want to post data by `form-data`, see #2049.
