### ISSUE TITLE
Is There a way to change axios User-Agent?

### ISSUE THREAD

**Issue by iamanas20** [axios/axios#2560]
I'm trying to use axios to access an ebay product page but I get 'access is denied' when I log the error, and I can see that user-agent is set to "axios"

this is my code (the url is only an example):
```
axios
    .get(`https://www.ebay.com/itm/Apple-iPhone-11-64GB-All-Colors-GSM-CDMA-Unlocked-Apple-Factory-Warranty-/163856625084`)
    .then(response => {
      let $ = cheerio.load(response.data);
      // here will be cheerio scraping
    })
    .catch(function(e) {
      console.log(e);
    });
```

this is the error I get in the console:
```
Error: Request failed with status code 403
    at createError (C:\Users\annou\Documents\GitHub\e_slayer\eslayer\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\annou\Documents\GitHub\e_slayer\eslayer\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\annou\Documents\GitHub\e_slayer\eslayer\node_modules\axios\lib\adapters\http.js:237:11)      
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1199:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: {
    url: 'https://www.ebay.com/itm/Apple-iPhone-11-64GB-All-Colors-GSM-CDMA-Unlocked-Apple-Factory-Warranty-/163856625084',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.19.0'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function (anonymous)],
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      error: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 6,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: 'www.ebay.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'www.ebay.com',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 6,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'GET /itm/Apple-iPhone-11-64GB-All-Colors-GSM-CDMA-Unlocked-Apple-Factory-Warranty-/163856625084 HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'User-Agent: axios/0.19.0\r\n' +
      'Host: www.ebay.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      maxCachedSessions: 100,
      _sessionCache: [Object]
    },
    socketPath: undefined,
    method: 'GET',
    path: '/itm/Apple-iPhone-11-64GB-All-Colors-GSM-CDMA-Unlocked-Apple-Factory-Warranty-/163856625084',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 403,
      statusMessage: 'Forbidden',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://www.ebay.com/itm/Apple-iPhone-11-64GB-All-Colors-GSM-CDMA-Unlocked-Apple-Factory-Warranty-/163856625084',
      redirects: []
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    _redirectable: Writable {
      _writableState: [WritableState],
      writable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://www.ebay.com/itm/Apple-iPhone-11-64GB-All-Colors-GSM-CDMA-Unlocked-Apple-Factory-Warranty-/163856625084'
    },
    [Symbol(kNeedDrain)]: false,
    [Symbol(isCorked)]: false,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 403,
    statusText: 'Forbidden',
    headers: {
      server: 'AkamaiGHost',
      'mime-version': '1.0',
      'content-type': 'text/html',
      'content-length': '407',
      expires: 'Tue, 19 Nov 2019 17:15:56 GMT',
      date: 'Tue, 19 Nov 2019 17:15:56 GMT',
      connection: 'close'
    },
    config: {
      url: 'https://www.ebay.com/itm/Apple-iPhone-11-64GB-All-Colors-GSM-CDMA-Unlocked-Apple-Factory-Warranty-/163856625084',
      method: 'get',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      validateStatus: [Function: validateStatus],
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'GET /itm/Apple-iPhone-11-64GB-All-Colors-GSM-CDMA-Unlocked-Apple-Factory-Warranty-/163856625084 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.19.0\r\n' +
        'Host: www.ebay.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      '</HTML>\n'
  },
  isAxiosError: true,
  toJSON: [Function (anonymous)]
}
```

how can I change the "User-Agent"

**Comment by pauloprestes** [comment]
you should pass `user-agent` in your header, like below:
```
axios
    .get(`https://www.ebay.com/itm/Apple-iPhone-11-64GB-All-Colors-GSM-CDMA-Unlocked-Apple-Factory-Warranty-/163856625084`, { headers: { 'User-Agent': 'YOUR-SERVICE-NAME' }  } )
    .then(response => {
      
      // here will be cheerio scraping
    })
    .catch(function(e) {
      console.log(e);
    });
```

**Comment by iamanas20** [comment]
Yes, Thank you!

**Comment by czlinNYC** [comment]
> you should pass `user-agent` in your header, like below:
> 
> ```
> axios
>     .get(`https://www.ebay.com/itm/Apple-iPhone-11-64GB-All-Colors-GSM-CDMA-Unlocked-Apple-Factory-Warranty-/163856625084`, 
> { headers: { 'User-Agent': 'YOUR-SERVICE-NAME' }  } )
>     .then(response => {
>       
>       // here will be cheerio scraping
>     })
>     .catch(function(e) {
>       console.log(e);
>     });
> ```

Where do i find the "YOUR SERVICE HERE" in my app? is it the app name?

**Comment by D3vl0per** [comment]
@czlinNYC It's is the user-agent, Paulo just show this example. Replace the YOUR-SERVICE-NAME section to for example Mozilla/5.0. :grinning: 
  
Some agent: https://deviceatlas.com/blog/list-of-user-agent-strings
