### ISSUE TITLE
axios 0.19.1 breaking changes

### ISSUE THREAD

**Issue by gre** [axios/axios#2645]
We can notice in our tests some important breaking changes that axios 0.19.1 patch:
It seems to be around XSS:

```
   console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Headers X-LedgerWallet-SyncToken forbidden
          at dispatchError (/home/circleci/live-common/cli/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
          at validCORSPreflightHeaders (/home/circleci/live-common/cli/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:102:5)
          at Request.preflightClient.on.resp (/home/circleci/live-common/cli/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:380:12)
          at emitOne (events.js:116:13)
          at Request.emit (events.js:211:7)
          at Request.onRequestResponse (/home/circleci/live-common/cli/node_modules/request/request.js:1066:10)
          at emitOne (events.js:116:13)
          at ClientRequest.emit (events.js:211:7)
          at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:552:21)
          at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17) undefined
    console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Cross origin http://localhost forbidden
          at dispatchError (/home/circleci/live-common/cli/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
          at Object.validCORSHeaders (/home/circleci/live-common/cli/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:77:5)
          at receiveResponse (/home/circleci/live-common/cli/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:847:21)
          at Request.client.on.res (/home/circleci/live-common/cli/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:679:38)
          at emitOne (events.js:116:13)
          at Request.emit (events.js:211:7)
          at Request.onRequestResponse (/home/circleci/live-common/cli/node_modules/request/request.js:1066:10)
          at emitOne (events.js:121:20)
          at ClientRequest.emit (events.js:211:7)
          at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:552:21) undefined
```

Happy to provide more information if necessary. On our side, we are staying on 0.19.0 because it works fine.

**Comment by chinesedfan** [comment]
@gre Can you provide your test codes?

**Comment by HosseinAlipour** [comment]
I can confirm the breaking change! this is the exact snippet causing fails in a few tests. I would be expecting semantic versioning for this project.
```
  api.defaults.headers['csrf-token'] = res.data.token;
  api.defaults.headers['cookie'] = res.headers['set-cookie'];
```

**Comment by textbook** [comment]
I think this is the same as #2654 - does setting the Node adapter, rather than the default XHR adapter that's picking up jsdom, help?

**Comment by chinesedfan** [comment]
Closed in favor of #2654.

**Comment by gre** [comment]
That issue also mentioned issue with custom headers which is not mentioned in #2654 but is probably in context of jsdom / mock

**Comment by chinesedfan** [comment]
@gre Would you mind setting your axios adapter explicitly as http adapter? Then check the extra custom headers error is still there or not.
