### ISSUE TITLE
Incomplete stacktrace on connection refused

### ISSUE THREAD

**Issue by CTimmerman** [axios/axios#2649]
```
Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
```

Where is the rest?

**To Reproduce**
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
const axios = require("axios")

process.on('unhandledRejection', (err, p) => console.log(err.stack))

;(async function includemeplz() {
	await axios.get('/')
})()
```

**Expected behavior**
```
Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
    at includemeplz (/home/cees/code/tester/test.js:17:8)
    at Object.<anonymous> (/home/cees/code/tester/test.js:18:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
```

**Environment:**
 - Axios Version 0.19.1
 - OS: Kubuntu 19.10
 - Node v10.15.2

**Comment by chinesedfan** [comment]
Interesting. Node.js didn't give the full error stack and axios did nothing. The following codes output the same result.

```
const http = require('http')

;(async function includemeplz() {
    const req = http.request({})
    req.on('error', (err) => {
        console.log('onerror', err.stack)
    })
})()
```

**Comment by CTimmerman** [comment]
Reported as https://github.com/nodejs/node/issues/31297
