### ISSUE TITLE
Not ignored ssl certification

### ISSUE THREAD

**Issue by alex-jss** [axios/axios#2690]
**Node version**: 10.16.3
**Axios version**:  0.18.0 and 0.19.2

It doesn't work for me

```
return axios.post(url,
 {
    httpsAgent: new https.Agent({
       rejectUnauthorized: false
    })
 }
).then(function (inst) {
 console.log('inst', inst)
}).catch(function (err) {
 console.log('err', err)
});
```

`err`:
```
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:636:8)
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
```

But works well on:
**Node version**: 6.9.1
**Axios version**:  0.18.0

How can I fix the error?

**Comment by alex-jss** [comment]
The only thing that helped me was to add before the call
`process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`

**Comment by alex-jss** [comment]
#535
