### ISSUE TITLE
Error: Request failed with status code 502

### ISSUE THREAD

**Issue by xiaomuzizier** [axios/axios#2802]
**Describe the issue**
A clear and concise description of what the issue is.
![image](https://user-images.githubusercontent.com/30134089/75999545-5318cf00-5f3d-11ea-812c-4ca38e0af8d0.png)
In my development,I have this error:
 Error: Request failed with status code 502
      at createError (/Users/ninaqqli/Desktop/lopan/lopan-server/node_modules/axios/lib/core/createError.js:16:15)
      at settle (/Users/ninaqqli/Desktop/lopan/lopan-server/node_modules/axios/lib/core/settle.js:17:12)
      at IncomingMessage.handleStreamEnd (/Users/ninaqqli/Desktop/lopan/lopan-server/node_modules/axios/lib/adapters/http.js:236:11)
      at IncomingMessage.emit (events.js:203:15)
      at IncomingMessage.EventEmitter.emit (domain.js:466:23)
      at endReadableNT (_stream_readable.js:1145:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
**Example Code**
Code snippet to illustrate your question

```js
// Example code here
```

**Expected behavior, if applicable**

**Environment:**
 - Axios Version [e.g. 0.18.0]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).

A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.

**Comment by xiaomuzizier** [comment]
Thank you，I try it




| |
李倩倩
|
|
邮箱：13051391963@163.com
|

签名由 网易邮箱大师 定制

On 03/06/2020 13:16, Xianming Zhong wrote:

Closed #2802.
