### ISSUE TITLE
Socket hangs up when using keepAlive on HTTPS agent

### ISSUE THREAD

**Issue by viniciusjssouza** [axios/axios#2958]
I am using axios to reach an external API on a node.js backend. Due to the large amount of requests, I tried to use `https.Agent` with `{ keepAlive: true }` option but, after that, I started receiving `socket hang up` error responses **every other request**. When I turn off persistent connections (`{ keepAlive: false }`), it works again. 

Also, I tried to use the request library (https://github.com/request/request) with the same agent and keepAlive enabled, and it worked perfectly. It really seems to be an issue with axios involving persistent connections on TLS sockets. 

Version: 0.19.2
Stack trace:
```
Error: socket hang up
    at createHangUpError (_http_client.js:332:15)
    at TLSSocket.socketCloseListener (_http_client.js:373:25)
    at TLSSocket.emit (events.js:203:15)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at _handle.close (net.js:607:12)
    at TCP.done (_tls_wrap.js:388:7)
```
Code: `ECONNRESET`
Node versions: 
  -  v10.19.0
  -  v12.15.0

**Comment by viniciusjssouza** [comment]
After struggling here, I found that the problem was not axios, but the HttpModule of Nest.js, which uses axios and I was using: https://github.com/nestjs/nest/blob/master/packages/common/http/http.module.ts#L34

I don't know the reason but, using axios directly worked perfectly.
