### ISSUE TITLE
question about promise and await

### ISSUE THREAD

**Issue by bi-kai** [axios/axios#2959]
## question 1
```
axios.post(url, {...})
  .then(
    function(res){...},
    function(err){...})
```
comes error with:
```
(node:11064) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at D:\node\www\test-koa\nte-proxy\index.js:63:42
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:11064) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11064) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

and this is correct:
```
axios.post(url, {})
  .then(
    function(res){...})
  .catch(function(err){...})
```

this is correct too:
```
axios.post(url, {})
  .then(
    function(res){...})
  .then(null, function(err){...})
```
**what's the difference between the 2nd 3rd and 1st?**

## question 2
code above I got result:`proxy failed: {}`(**err in catch() is undefined**), but the server sent the correct http 200 response indeed.
when I use await like this:
```
let res = await axios.post(url, {...});
console.log(`proxy status: ${res.status}, data: ${JSON.stringify(res.data)}`);
```
got corrent log:
`proxy status: 200, data: {"data":"[Session ID(852e25a3620e46a68e6a29b4b864f21f) is not exist]","sessionId":"","message":["Session ID(852e25a3620e46a68e6a29b4b864f21f) is not exist"],"status":"failed"}`
**why await is corrent, and promise is so strange?**

**Comment by bi-kai** [comment]
@chinesedfan `support` label是什么意思？这个问题能看下么？搞得我都怀疑promise了

**Comment by chinesedfan** [comment]
@bi-kai 客服支持，就是用户使用过程中遇到的其它问题。一般issue中只处理明确是axios代码导致的bug，要求是可以被复现。

你需要自行想办法，或者等待热心群众解答。尤其在信息缺失的情况下，别人是很难帮忙定位的，一来一回的问答也导致大家没有足够精力来处理。类似的issue有很多，虽然不是特别有人情味，一段时间之后都会被自动关闭。

**Comment by bi-kai** [comment]
我以为已经把问题描述得比较详细了，我再补充一下吧

**Comment by chinesedfan** [comment]
分享一个[文档](https://github.com/chinesedfan/You-Dont-Know-Axios#interceptors)，可能会帮助你。

**Comment by bi-kai** [comment]
确认了遇到的问题并不是axios的问题。

我是在koa中，promise回调方法里用ctx返回，类似这样：
```
app.use(async (ctx, next) => {
  axios
    .get(
      "http://127.0.0.1:4000/",
      {},
      {
        headers: {},
      }
    )
    .then(function (response) {
      console.log(`proxy succeed: ${JSON.stringify(response)}`);
      ctx.response.status = 200;
      ctx.response.type = "application/json; charset=utf-8";
      ctx.response.body = response;
    })
    .catch(function (error) {
      console.log(`proxy failed: ${JSON.stringify(error)}`);
      ctx.response.status = 200;
      ctx.response.type = "application/json; charset=utf-8";
      ctx.response.body = "rr";
    });
});
```
在回调执行前，koa流程已经走完了，直接返回404，而不会等待回调方法中ctx赋值，这与express不同，express会一直等待。

**koa中还是老老实实用async/await吧。**
