### ISSUE TITLE
Error response missing CORS exposed headers

### ISSUE THREAD

**Issue by fgsalomon** [axios/axios#3004]
**Error response missing CORS exposed headers**

Axios is removing CORS exposed headers on error responses. It's the same issue that the one reported [here](https://github.com/axios/axios/issues/1388) but it's locked and I cannot comment there.

I've followed the instructions given in [this answer](https://github.com/axios/axios/issues/1388#issuecomment-372028197) and expose the headers on my backend but the exposed headers are missing.

I want Axios to be able to handle a 401 error with a `WWW-Authenticate` header.

You can see on this screenshot that my backend is exposing the header:
![image](https://user-images.githubusercontent.com/3149695/84129841-c5201900-aa42-11ea-9a67-33445461dfdc.png)

But if I print the Axios error response the header is missing:

```json
{
  "config": {
    "baseURL": "/test",
    "data": "{\"username\":\"user\",\"password\":\"password\"}",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/json;charset=utf-8"
    },
    "maxContentLength": -1,
    "method": "post",
    "timeout": 0,
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "url": "/client/login",
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN"
  },
  "message": "Request failed with status code 401",
  "name": "Error",
  "stack": "Error: Request failed with status code 401\n    at createError (webpack-internal:///./node_modules/axios/lib/core/createError.js:16:15)\n    at settle (webpack-internal:///./node_modules/axios/lib/core/settle.js:17:12)\n    at XMLHttpRequest.handleLoad (webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:61:7)"
}
```

**Example Code**
This is the code that I'm using for the request.

```js
   axios({
          baseURL: process.env.VUE_APP_API_ENDPOINT,
          url: "/client/login",
          data: credentials,
          method: 'POST'
        }).then(resp => {
          console.log("Login resp: " + JSON.stringify(resp));
          resolve(resp);
        }).catch(err => {
          console.log("Login error: " + JSON.stringify(err));
          reject(err);
        })
```

**Expected behavior, if applicable**
I expected to found the header `WWW-Authenticate` in the error response.

**Environment:**
 - Axios Version: 0.19.2
 - OS: Ubuntu 18.04.4 LTS
 - Browser: Chrome
 - Browser Version:  83.0.4103.97

**Comment by jasonsaayman** [comment]
Can you please try with the latest version and let me know If this issue is still occurring?

**Comment by fgsalomon** [comment]
> Can you please try with the latest version and let me know If this issue is still occurring?

Still happening with v0.21.1. 😢  

Headers are missing in the error response:
```
{
	"message": "Request failed with status code 401",
	"name": "Error",
	"fileName": "http://localhost:8081/app.js line 1269 > eval",
	"lineNumber": 16,
	"columnNumber": 15,
	"stack": "createError@webpack-internal:///./node_modules/axios/lib/core/createError.js:16:15\nsettle@webpack-internal:///./node_modules/axios/lib/core/settle.js:17:12\nhandleLoad@webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:62:13\nEventHandlerNonNull*dispatchXhrRequest@webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:37:5\nxhrAdapter@webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:13:10\ndispatchRequest@webpack-internal:///./node_modules/axios/lib/core/dispatchRequest.js:52:10\npromise callback*request@webpack-internal:///./node_modules/axios/lib/core/Axios.js:61:23\nwrap@webpack-internal:///./node_modules/axios/lib/helpers/bind.js:9:15\nlogin/<@webpack-internal:///./src/store.js:32:53\nlogin@webpack-internal:///./src/store.js:31:14\nwrappedActionHandler@webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:786:23\ndispatch@webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:465:15\nboundDispatch@webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:355:21\nlogin@webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/pages/Login.vue?vue&type=script&lang=js&:108:57\nsubmit@webpack-internal:///./node_modules/cache-loader/dist/cjs.js?{\"cacheDirectory\":\"node_modules/.cache/vue-loader\",\"cacheIdentifier\":\"4667a1aa-vue-loader-template\"}!./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/pages/Login.vue?vue&type=template&id=07b13bd8&:52:46\ninvokeWithErrorHandling@webpack-internal:///./node_modules/vue/dist/vue.esm.js:1862:26\ninvoker@webpack-internal:///./node_modules/vue/dist/vue.esm.js:2187:14\nadd$1/original._wrapper@webpack-internal:///./node_modules/vue/dist/vue.esm.js:7555:25\nEventListener.handleEvent*add$1@webpack-internal:///./node_modules/vue/dist/vue.esm.js:7559:12\nupdateListeners@webpack-internal:///./node_modules/vue/dist/vue.esm.js:2219:10\nupdateDOMListeners@webpack-internal:///./node_modules/vue/dist/vue.esm.js:7589:18\ninvokeCreateHooks@webpack-internal:///./node_modules/vue/dist/vue.esm.js:6070:22\ncreateElm@webpack-internal:///./node_modules/vue/dist/vue.esm.js:5957:28\ncreateChildren@webpack-internal:///./node_modules/vue/dist/vue.esm.js:6054:18\ncreateElm@webpack-internal:///./node_modules/vue/dist/vue.esm.js:5955:23\ncreateChildren@webpack-internal:///./node_modules/vue/dist/vue.esm.js:6054:18\ncreateElm@webpack-internal:///./node_modules/vue/dist/vue.esm.js:5955:23\ncreateChildren@webpack-internal:///./node_modules/vue/dist/vue.esm.js:6054:18\ncreateElm@webpack-internal:///./node_modules/vue/dist/vue.esm.js:5955:23\ncreateChildren@webpack-internal:///./node_modules/vue/dist/vue.esm.js:6054:18\ncreateElm@webpack-internal:///./node_modules/vue/dist/vue.esm.js:5955:23\ncreateChildren@webpack-internal:///./node_modules/vue/dist/vue.esm.js:6054:18\ncreateElm@webpack-internal:///./node_modules/vue/dist/vue.esm.js:5955:23\ncreateChildren@webpack-internal:///./node_modules/vue/dist/vue.esm.js:6054:18\ncreateElm@webpack-internal:///./node_modules/vue/dist/vue.esm.js:5955:23\n",
	"config": {
		"url": "/client/login",
		"method": "post",
		"data": "{\"username\":\"test\",\"password\":\"test\"}",
		"headers": {
			"Accept": "application/json, text/plain, */*",
			"Content-Type": "application/json;charset=utf-8"
		},
		"baseURL": "/test",
		"transformRequest": [null],
		"transformResponse": [null],
		"timeout": 0,
		"xsrfCookieName": "XSRF-TOKEN",
		"xsrfHeaderName": "X-XSRF-TOKEN",
		"maxContentLength": -1,
		"maxBodyLength": -1
	}
}
```

But they're present in the success response :
```
{
	"data": "Foo bar baz",
	"status": 200,
	"statusText": "OK",
	"headers": {
		"access-control-allow-origin": "http://localhost:8081",
		"access-control-expose-headers": "WWW-Authenticate",
		"connection": "keep-alive",
		"content-length": "11",
		"content-type": "text/html; charset=utf-8",
		"date": "Sat, 22 May 2021 10:49:27 GMT",
		"server": "Werkzeug/1.0.0 Python/3.6.7",
		"vary": "Origin",
		"x-powered-by": "Express"
	},
	"config": {
		"url": "/client/login",
		"method": "post",
		"data": "{\"username\":\"test\",\"password\":\"test\"}",
		"headers": {
			"Accept": "application/json, text/plain, */*",
			"Content-Type": "application/json;charset=utf-8"
		},
		"baseURL": "/test",
		"transformRequest": [null],
		"transformResponse": [null],
		"timeout": 0,
		"xsrfCookieName": "XSRF-TOKEN",
		"xsrfHeaderName": "X-XSRF-TOKEN",
		"maxContentLength": -1,
		"maxBodyLength": -1
	},
	"request": {}
}
```

**Comment by fgsalomon** [comment]
@jasonsaayman do you need more information?

**Comment by fgsalomon** [comment]
Hi,

It's been a long time since the last time I worked on the project I was having issues with but now using version 0.21.4 it's working correctly.

Thank you for your work!
