### ISSUE TITLE
0.20.0 Released as version next on NPM

### ISSUE THREAD

**Issue by jasonsaayman** [axios/axios#3009]
Hi All,

We have created a branch for a beta version of 0.20.0, please check it out here:

[0.20.0-beta.1](https://github.com/axios/axios/tree/release/0.20.0-beta.1)

Thanks

**Comment by chinesedfan** [comment]
For other users, please understand that we also want to release a new version soon, but can't contact any members (like @emilyemorehouse @mzabriskie) with publish permissions now.

If you can find ways to help, that will be great.

**Comment by jasonsaayman** [comment]
Update on this, 0.20.0 has been pinned and tagged, also we have a release on NPM under the next tag! Please try this version out and provide feedback.

**Comment by elamperti** [comment]
Out of curiosity: was there a reason to have a `-0` in the version tag? (instead of being just `v0.20.0`)

**Comment by chrisparton1991** [comment]
@elamperti `v0.20.0-0` is a pre-release version, so I assume they're saving `v0.20.0` for the proper release :)

**Comment by yoyo837** [comment]
max call stack size exceeded

0.20.0

**Comment by sk-** [comment]
Could this issue be closed or at least remove the `v0.20.1` label?

Version `next` points to a pre-release version, while `latest` to `0.20.0`.

Also `next` probably need to be updated to either `0.20.0` or a rc for `0.20.1`.

@yoyo837 could you create a separate issue for your report.

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/105940405-34ac4c80-6096-11eb-9ec8-d22aced94ab2.png)

@sk- 
I'll try it.

**Comment by jiayisheji** [comment]
I use 0.21.1 

update RangeError: Maximum call stack size exceeded
    at merge (E:\gitlab\xs-webapp\node_modules\axios\lib\utils.js:1:1)
    at assignValue (E:\gitlab\xs-webapp\node_modules\axios\lib\utils.js:282:21)
    at forEach (E:\gitlab\xs-webapp\node_modules\axios\lib\utils.js:253:12)
    at merge (E:\gitlab\xs-webapp\node_modules\axios\lib\utils.js:291:5)
    at assignValue (E:\gitlab\xs-webapp\node_modules\axios\lib\utils.js:282:21)
    at forEach (E:\gitlab\xs-webapp\node_modules\axios\lib\utils.js:253:12)
    at merge (E:\gitlab\xs-webapp\node_modules\axios\lib\utils.js:291:5)
    at assignValue (E:\gitlab\xs-webapp\node_modules\axios\lib\utils.js:282:21)
    at forEach (E:\gitlab\xs-webapp\node_modules\axios\lib\utils.js:253:12)
    at merge (E:\gitlab\xs-webapp\node_modules\axios\lib\utils.js:291:5)

**Comment by yoyo837** [comment]
@jiayisheji Do you use `axios` in `vue` or `nuxt.js` program?

**Comment by yoyo837** [comment]
It looks like there have some object circular reference.

**Comment by yoyo837** [comment]
@jiayisheji I found some mistake by myself. `axios.get` or `axios.post` or other methods input params have circular references.

**Comment by alameenpa** [comment]
de1d8d8.js:2 RangeError: Maximum call stack size exceeded
    at a.t._render (de1d8d8.js:2)
    at a.r (de1d8d8.js:2)
    at pn.get (de1d8d8.js:2)
    at new pn (de1d8d8.js:2)
    at de1d8d8.js:2
    at a.xn.$mount (de1d8d8.js:2)
    at a.xn.$mount (de1d8d8.js:2)
    at init (de1d8d8.js:2)
    at de1d8d8.js:2
    at l (de1d8d8.js:2)
