### ISSUE TITLE
Cant send a post request with axios

### ISSUE THREAD

**Issue by EiskalterFreund** [axios/axios#3412]
I cant send post request using axios to a site.
<b>It always goes in catch</b>

-- MY CODE
```
postRequest(request, data, data_) { // data_ is the d normall
		const URL = getUrl(request, this.host, data_);
		// console.log(data)

		return axios({
			url: URL,
			method: 'POST',
			followRedirect: true,
			maxRedirects: 5,
			headers: {
				'Authorization': 'Bearer ' + this.key,
				'Content-Type': 'application/json',
				'Accept': 'Application/vnd.pterodactyl.v1+json',
			},
			data: data
		}).then(response => {
			if (request == 'CreateServer') {
				// If people want make it return the server object
				return response.data.attributes;
			}
			else if (request == 'CreateUser') {
				return response.data.attributes;
			}
			else if (request == 'CreateNode') {
				return response.data.attributes;
			}
			else if (request == 'SuspendServer') {
				return 'Server suspended successfully';
			}
			else if (request == 'UnSuspendServer') {
				return 'Server unsuspended successfully';
			}
		}).catch(error => {
			const err = createError(request, error, data);
			if (err) throw err;
			console.log(error)
		});
	}
```

-- FULL ERROR LOG --

```
Error: Request failed with status code 422
    at createError (C:\Users\engin\Desktop\Development\CreateServerTEst\node_modules\nodeactyl-v1-support\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\engin\Desktop\Development\CreateServerTEst\node_modules\nodeactyl-v1-support\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\engin\Desktop\Development\CreateServerTEst\node_modules\nodeactyl-v1-support\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  config: {
    url: 'https://panel.linux123123.cf/api/application/servers',
    method: 'post',
    data: '{"name":"Pls work","user":1,"egg":1,"docker_image":"quay.io/pterodactyl/core:java","startup":"java -Xms128M -Xmx128M -jar server.jar","environment":{"BUNGEE_VERSION":"latest","SERVER_JARFILE":"server.jar"},"limits":{"memory":128,"swap":0,"disk":512,"io":500,"cpu":100},"feature_limits":{"databases":5,"backups":1},"allocation":{"default":17}}',
    headers: {
      Accept: 'Application/vnd.pterodactyl.v1+json',
      'Content-Type': 'application/json',
      Authorization: 'Bearer 7LGoU4Tbmbmgk0tyOIMF6b0uxiuhiJxN6tFd84oZNXPbHYjw',
      'User-Agent': 'axios/0.19.2',
      'Content-Length': 342
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus],
    maxRedirects: 5,
    followRedirect: true
  },
  request: ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function],
      abort: [Function],
      aborted: [Function],
      error: [Function],
      timeout: [Function],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 6,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: true,
      _SNICallback: null,
      servername: 'panel.linux123123.cf',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'panel.linux123123.cf',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(asyncId)]: 16,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    connection: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: true,
      _SNICallback: null,
      servername: 'panel.linux123123.cf',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'panel.linux123123.cf',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(asyncId)]: 16,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'POST /api/application/servers HTTP/1.1\r\n' +
      'Accept: Application/vnd.pterodactyl.v1+json\r\n' +
      'Content-Type: application/json\r\n' +
      'Authorization: Bearer 7LGoU4Tbmbmgk0tyOIMF6b0uxiuhiJxN6tFd84oZNXPbHYjw\r\n' +
      'User-Agent: axios/0.19.2\r\n' +
      'Content-Length: 342\r\n' +
      'Host: panel.linux123123.cf\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    insecureHTTPParser: undefined,
    path: '/api/application/servers',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      connection: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 422,
      statusMessage: 'Unprocessable Entity',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [Circular],
      responseUrl: 'https://panel.linux123123.cf/api/application/servers',
      redirects: [],
      [Symbol(kCapture)]: false
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'panel.linux123123.cf',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      writable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 342,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function],
      _currentRequest: [Circular],
      _currentUrl: 'https://panel.linux123123.cf/api/application/servers',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      authorization: [Array],
      'user-agent': [Array],
      'content-length': [Array],
      host: [Array]
    }
  },
  response: {
    status: 422,
    statusText: 'Unprocessable Entity',
    headers: {
      date: 'Fri, 13 Nov 2020 16:26:47 GMT',
      'content-type': 'application/json',
      'transfer-encoding': 'chunked',
      connection: 'close',
      'set-cookie': [Array],
      'cache-control': 'no-cache, private',
      'x-ratelimit-limit': '240',
      'x-ratelimit-remaining': '239',
      'cf-cache-status': 'DYNAMIC',
      'cf-request-id': '0664075a9f0000076aac924000000001',
      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
      'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report?s=G7LwD9La5x2CS7S6n21W1K5NYmyiBvP5QZML7dCBV%2FM7XfETr3uizU2lnEA3tVyzPtyohAcVar7M8JoDpwWlmLb5FDHHF3V4KvTx4aT3nFk6CaIG2A%3D%3D"}],"group":"cf-nel","max_age":604800}',
      nel: '{"report_to":"cf-nel","max_age":604800}',
      server: 'cloudflare',
      'cf-ray': '5f19db3dcc98076a-LHR'
    },
    config: {
      url: 'https://panel.linux123123.cf/api/application/servers',
      method: 'post',
      data: '{"name":"Pls work","user":1,"egg":1,"docker_image":"quay.io/pterodactyl/core:java","startup":"java -Xms128M -Xmx128M -jar server.jar","environment":{"BUNGEE_VERSION":"latest","SERVER_JARFILE":"server.jar"},"limits":{"memory":128,"swap":0,"disk":512,"io":500,"cpu":100},"feature_limits":{"databases":5,"backups":1},"allocation":{"default":17}}',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      validateStatus: [Function: validateStatus],
      maxRedirects: 5,
      followRedirect: true
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'POST /api/application/servers HTTP/1.1\r\n' +
        'Accept: Application/vnd.pterodactyl.v1+json\r\n' +
        'Content-Type: application/json\r\n' +
        'Authorization: Bearer 7LGoU4Tbmbmgk0tyOIMF6b0uxiuhiJxN6tFd84oZNXPbHYjw\r\n' +
        'User-Agent: axios/0.19.2\r\n' +
        'Content-Length: 342\r\n' +
        'Host: panel.linux123123.cf\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      insecureHTTPParser: undefined,
      path: '/api/application/servers',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'panel.linux123123.cf',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: { errors: [Array] }
  },
  isAxiosError: true,
  toJSON: [Function]
}
```

**Comment by EiskalterFreund** [comment]
pls help

**Comment by lopezdp** [comment]
This is a real problem that I can believe no one else has discovered. How to you make an HTTP request that needs an API key using Axios???
