### ISSUE TITLE
will not read headers on get request

### ISSUE THREAD

**Issue by mikeck1** [axios/axios#3456]
#### Describe the bug
I only want to make an API get request with headers and parameters. I notice my header is not being read.  I get an error_message: 'Invalid API key.' error. Notice below the default axios headers. What am I missing? I've looked in the various issues raised by others and none of the workarounds have helped. 
```bash
config: {
    url: 'https://api.airbnb.com/v2/explore_tabs',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.0'
    }
```

### index.js
```js
const axios = require('axios');
let URL = 'https://api.airbnb.com/v2/explore_tabs'
let headers = {
    "x-airbnb-api-key": "915pw2pnf4h1aiguhph5gc5b2",
    "user-agent": "Airbnb/19.18 AppVersion/19.18 iPhone/12.2 Type/Phone",
    "x-airbnb-screensize": "w=375.00;h=812.00",
    "x-airbnb-carrier-name": "T-Mobile",
    "x-airbnb-network-type": "wifi",
}
var config = {
    headers: headers
};

let params = {
    'query': 'Big Bear, CA'
}

axios.get(URL,
    params,
    config).then(response => {
        const data = response.data.results;
        console.log(data)
    }).catch(error => {
        console.log(error);
    })
```

## console output:
```js
Error: Request failed with status code 400
    at createError (/Users/mikeck/Desktop/airbnb-node/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/mikeck/Desktop/airbnb-node/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/mikeck/Desktop/airbnb-node/node_modules/axios/lib/adapters/http.js:244:11)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  config: {
    url: 'https://api.airbnb.com/v2/explore_tabs',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.0'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
...
```

#### Expected behavior
I should have the headers read, and the server not return a 400. I've tested this in postman and it works correctly, just axios seems to ignore the headers.

#### Environment
 - Axios Version [axios@0.21.0]
 - ADAPTERS: https, http
 - Node.js Version [v12.16.2]
 - OS: [OSX 10.15.7 (19H2)]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by buyan302** [comment]
Check https://github.com/axios/axios#axiosgeturl-config

The right way to set get request headers is 

```js
axios.get(URL, {headers, params})
```
