### ISSUE TITLE
Webpack 5 - "Unexpected token: punc (.)" after import axios

### ISSUE THREAD

**Issue by fiskolini** [axios/axios#3560]
#### Describe the bug
I am getting a strange issue on bundling webpack for production environment.
`Unexpected token: punc (.)`

#### To Reproduce
1. Please fork the following [axios-issue-example-with-webpack5](https://github.com/fiskolini/axios-issue-example-with-webpack5) repository
2. Perform `npm install`
3. Run `npm run build`

```js
import React from "react";
import axios from "axios"; // <---------------

class SimpleComponent extends React.Component {
  render() {

    return (
      <section className="bg-white py-16">
        Simple
      </section>
    )
  }
}

export default SimpleComponent
```

#### Expected behavior
I was expecting all working, since everything works when I run `npm run start`

#### Environment
- Axios Version [0.21.1]
- Node.js Version [v12.20.1]
- Additional Library Versions [React 17.0.1, Webpack 5.15.0]

#### Additional context/Screenshots
The error that I am getting is
```bash
ERROR in static/main.9fe9a667dce8c4fcefc1.js from Terser
Unexpected token: punc (.) [static/main.9fe9a667dce8c4fcefc1.js:18979,6]
    at js_error (/home/franciscocarvalho/code/oss/axios-issue-example-with-webpack5/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:546:11)
    at croak (/home/franciscocarvalho/code/oss/axios-issue-example-with-webpack5/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1264:9)
    at token_error (/home/franciscocarvalho/code/oss/axios-issue-example-with-webpack5/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1272:9)
    at unexpected (/home/franciscocarvalho/code/oss/axios-issue-example-with-webpack5/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1278:9)
    at statement (/home/franciscocarvalho/code/oss/axios-issue-example-with-webpack5/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1397:17)
    at _embed_tokens_wrapper (/home/franciscocarvalho/code/oss/axios-issue-example-with-webpack5/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1322:26)
    at block_ (/home/franciscocarvalho/code/oss/axios-issue-example-with-webpack5/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:2155:20)
    at statement (/home/franciscocarvalho/code/oss/axios-issue-example-with-webpack5/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1386:29)
    at _embed_tokens_wrapper (/home/franciscocarvalho/code/oss/axios-issue-example-with-webpack5/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1322:26)
    at if_ (/home/franciscocarvalho/code/oss/axios-issue-example-with-webpack5/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:2141:21)
```

**Comment by fiskolini** [comment]
The problem is related to the `debug` package, not related to `axios`.
## Solution
The code of `debug` for node has been added since I haven't yet told webpack build for web app so then it won't include that code.

So as long as I set the target as `web` in configuration, then it would work:

**webpack.common.js**

```
module.exports = {  
  target: 'web',
  // ...
}
```
