### ISSUE TITLE
when post request in server render without cookie, got error `ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Cookie"`

### ISSUE THREAD

**Issue by wanxiaodong404** [axios/axios#4510]
#### Describe the bug
when post request in server render without cookie, got error `ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Cookie"`
```
 TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Cookie"
    at ClientRequest.setHeader (_http_outgoing.js:561:3)
    at new ClientRequest (_http_client.js:251:14)
    at Object.request (http.js:50:10)
```
<img width="864" alt="image" src="https://user-images.githubusercontent.com/17507889/156984976-18bc4aec-0206-4510-b19f-9f759ca6b890.png">

#### To Reproduce
normal request in ssr

```
return this.$axios.get('/api/****',{
                params:{}
            }).then(({data: rs}) => {
            })
```

#### Environment
 - Axios Version [0.19.2]
 - Adapter [/HTTP]
 - Browser [Chromei]
 - Browser Version [100.0.4896.20]
 - Node.js Version [14.16.1]
 - OS: [ OSX 12.0.1]
 - Additional Library Versions [none]

**Comment by wanxiaodong404** [comment]
coder error
