### ISSUE TITLE
Axios, graphql: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by burgossrodrigo** [axios/axios#4526]
#### Describe the issue

Maybe it's duplicated anyway i've searched this specific case without finding anything related.

I'm working to plot a chart with tradingview and bitquery api using axios and graphql

The config of my query goes like this:

#### Example Code

```js
        const response = await axios.post(
            Bitquery.endpoint, {
                query: Bitquery.GET_COIN_INFO,
                variables: {
                    "tokenAddress": symbolName
                },
                mode: 'cors',
                headers: {
                    "Content-Type": "application/json",
                    "X-API-KEY": "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                    "Access-Control-Allow-Origin" : ["http://localhost:3000", "https://graphql.bitquery.io/ide"]
                }
            }
        ); 
```

#### Expected behavior, if applicable

Shouldn't be any issue with cors i guess.

#### Environment
 - Axios Version 0.26.1
 - Graphq query
 - Windows 10

#### Additional context/Screenshots
Console error

```

localhost/:1 Access to XMLHttpRequest at 'https://graphql.bitquery.io/' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
graphql.bitquery.io/:1          Failed to load resource: net::ERR_FAILED
createError.js:17 Uncaught (in promise) Error: Network Error
    at createError (createError.js:17:1)
    at XMLHttpRequest.handleError (xhr.js:123:1)

```

**Comment by monster898** [comment]
Besed on error message,I think it's still a CORS issue.

`Access-Control-Allow-Origin` should be set in the response header,not request header.

**Comment by jasonsaayman** [comment]
closing i agree this is cors
