### ISSUE TITLE
Proxy config via HTTP_PROXY env variable on explicit port 80 doesn't work

### ISSUE THREAD

**Issue by lucafaggianelli** [axios/axios#4533]
#### Describe the bug
I'm in company environment behind a proxy, the proxy host is `10.90.176.62` and is configured on the env vars HTTP_PROXY and HTTPS_PROXY as `http://10.90.176.62:80` **notice the trailing port :80**.
Then I'm using Axios on NodeJS (v14) and with some URLs the HTTP call doesn't work, I receive the following error (please find the full log at the end of the post):
```
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
    at TLSWrap.callbackTrampoline (internal/async_hooks.js:130:17) {
  errno: -4077,
  code: 'ECONNRESET',
```

#### To Reproduce
I'm trying to call GitHub Enterprise API but I get the `ECONNRESET` error mentioned above.

❌ not working
```js
const axios = require('axios')

process.env.HTTP_PROXY
// > 'http://10.90.176.62:80'
axios.get('https://github.tools.digital.mycompany.com/api/v3/repos/LQ6211/portfolio_name_fix').catch(console.log)
```

After some debugging I noticed that if I manually set the same proxy value (`http://10.90.176.62:80`) in `axios.get` options, I receive the same error, so the proxy is correctly set from the `HTTP_PROXY` variable:

❌ not working
```
// This is equivalent to using HTTP_PROXY=http://10.90.176.62:80 and results in an error
axios.get('https://github.tools.digital.mycompany.com/api/v3/repos/LQ6211/portfolio_name_fix', {
  proxy: {
    protocol: 'http',
    host: '10.90.176.62',
    port: 80
  }
})
```

✔ Working
Finally I tried to omit the port and magically it works correctly:
```
axios.get('https://github.tools.digital.mycompany.com/api/v3/repos/LQ6211/portfolio_name_fix', {
  proxy: {
    protocol: 'http',
    host: '10.90.176.62',
    // Remove the port!
    // port: 80
  }
})
```

Then I tried to set HTTP_PROXY env var to `http://10.90.176.62` and it works, so it's definitely the port `80` in the proxy URL.
For curiosity, I tried to set 443 as the proxy port (still with the http protocol) as the final URL is on HTTP**S** and it works as well.
So something weird is going on.

For what is worth, with some URLs the http calls work also when the proxy includes the port `80` in the config.

#### Expected behavior
I expect the HTTP call to correctly work and correctly set the proxy.

#### Environment
 - Axios Version [from 0.21.4 to 0.26.1]
 - Adapter [Node]
 - Browser [N/A]
 - Browser Version [N/A]
 - Node.js Version [14.18.0]
 - OS: [Microsoft Windows 10 Enterprise V 10.0.18363 Build 18363]
 - Additional Library Versions [N/A]

#### Additional context/Screenshots

<details>
  <summary>Full error log</summary>
<pre>
<code>
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
    at TLSWrap.callbackTrampoline (internal/async_hooks.js:130:17) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.26.1',
      host: 'github.tools.digital.mycompany.com'
    },
    method: 'get',
    url: 'https://github.tools.digital.mycompany.com/api/v3/repos/LQ6211/portfolio_name_fix',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: 'https://github.tools.digital.mycompany.com/api/v3/repos/LQ6211/portfolio_name_fix',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: null,
      hostname: '10.90.176.62',
      port: '80',
      beforeRedirect: [Function: beforeRedirect],
      nativeProtocols: [Object],
      pathname: '/api/v3/repos/LQ6211/portfolio_name_fix',
      slashes: true,
      hash: null,
      search: null,
      query: null,
      href: 'https://github.tools.digital.mycompany.com/api/v3/repos/LQ6211/portfolio_name_fix'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 1,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'GET https://github.tools.digital.mycompany.com/api/v3/repos/LQ6211/portfolio_name_fix HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.26.1\r\n' +
        'host: github.tools.digital.mycompany.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: 'https://github.tools.digital.mycompany.com/api/v3/repos/LQ6211/portfolio_name_fix',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '10.90.176.62',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://10.90.176.62:80/api/v3/repos/LQ6211/portfolio_name_fix',
    _isRedirect: true,
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
</code>
</pre>
</details>

**Comment by filex** [comment]
We ran into the same issue. Corporate proxy is advertised via env vars `https_proxy` with `http://` schema and explicit port `80`.

We use axios to fetch a binary in a npm install script (by coincidence also from Github). The installation fails with `read ECONNRESET`.

When we remove the explicit port from `https_proxy`, fetching works.

In the same shell with the same env vars, `curl` can fetch the resource in both configurations, with and without port.

**Comment by AlexWang-16** [comment]
I'm having the same issue as well. The corporate proxy for my company is on port 3128. When I'm making an API call, I'm getting `ECONNRESET` with a 400 response. Using Postman and CURL, I'm able to hit the API endpoint and obtain results.

Are there any workarounds for this? I'm using mailgun.js library that uses axios under the hood. I'm hoping I won't have to create a PR for mailgun.js just to fix this issue.

**Comment by lucafaggianelli** [comment]
> I'm having the same issue as well. The corporate proxy for my company is on port 3128. When I'm making an API call, I'm getting `ECONNRESET` with a 400 response. Using Postman and CURL, I'm able to hit the API endpoint and obtain results.
> 
> 
> 
> Are there any workarounds for this? I'm using mailgun.js library that uses axios under the hood. I'm hoping I won't have to create a PR for mailgun.js just to fix this issue.
> 
> 
> 
> As an additional data point, the [mailgun.js NPM package](https://github.com/mailgun/mailgun.js) is using Axios 1.3.3.
> 
> 
> 
> -- Update --
> 
> I'm hoping to create a PR that will fix this issue, but I'm struggling on the code base to find where axios picks up on `http_proxy`, `https_proxy`, and `no_proxy` environment variables. I found the PR that adds support for `no_proxy` environment variable, but that was back in 2018 prior to version 1.x release. The code base has significantly changed sinced then.
> 
> 
> 
> I would appreciate it if anyone can point me in the right direction.

Ah interesting that you have the same problem and your proxy is not on port 80 or 443.

Hoping for a feedback from the axios team.

**Comment by ricovitch** [comment]
I also face issues with a proxy url using port 3128, getting 407 error with latest version of axios library

**Comment by jvxiao** [comment]
I also encountered a similar problem when I wanted to request data. My system is Windows. After editing the environment variables and setting the values ​​of HTTP_PRXOY and HTTPS_PROXY, reopening a terminal, it worked.

**Be sure to open a new terminal after setting environment variables.**

**Comment by jvxiao** [comment]
Using https-proxy-agent would be a better way . Refer: https://github.com/axios/axios/issues/6330

**Comment by jasonsaayman** [comment]
Thanks for your bug report, we will be closing this issue and ask that you please test and try re-create the issue with the latest version of Axios. If the bug is still present please open a issue. If possible and you are willing open a pull request with a proposed fix. Please see the motivation for doing this:

https://github.com/axios/axios/issues/6983
