### ISSUE TITLE
The request status 500 is returned correctly in the browser, but 404 is returned incorrectly in nodejs.

### ISSUE THREAD

**Issue by wll8** [axios/axios#4589]
#### Describe the bug
The request status 500 is returned correctly in the browser, but 404 is returned incorrectly in nodejs.

#### To Reproduce
I tried using exporess with the following code without issue:

``` js
res.status(500)
// or res.status(500).send()
// or res.status(500).json({})
// or res.status(500).end()
````

Maybe it needs to be in a specific interface state, I don't know what interface can cause the error.

So I recorded this video, and the same code has two results:

``` js
axios = require(`axios`).default

console.log(`axios.VERSION`, axios.VERSION) // 0.26.0
http = axios.create({
  proxy: false,
})
http.interceptors.request.use(async (config) => {
  return config
}, (err) => Promise.reject(err))
http.interceptors.response.use((res) => {
  return res.config._getRaw === true ? res : res.data
}, (err) => Promise.reject(err))
http({
  baseURL: "http://localhost:9030",
  method: "get",
  url: "/api/main-actuator/helpers/quality/monitor/v1/search_seat_list/94751",
  //  url: "/500",
  params: {
    callStatus: "0",
    alertStatus: "0",
    seatSearchText: "",
  },
  headers: {
    host: "172.16.203.81",
    connection: "keep-alive",
    pragma: "no-cache",
    "cache-control": "no-cache",
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
    accept: "application/json, text/plain, */*",
    authorization: "Basic c2FiZXI6c2FiZXJfc2VjcmV0",
    "blade-auth": "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRfaWQiOiIwMDAwMDAiLCJ1c2VyX25hbWUiOiJhcHBhZG1pbiIsInJlYWxfbmFtZSI6IuW6lOeUqOeuoeeQhuWRmCIsImF2YXRhciI6IiIsImF1dGhvcml0aWVzIjpbImFwcC1hZG1pbiJdLCJjbGllbnRfaWQiOiJzYWJlciIsInJvbGVfbmFtZSI6ImFwcC1hZG1pbiIsImxpY2Vuc2UiOiJwb3dlcmVkIGJ5IGJsYWRleCIsInBvc3RfaWQiOiIxMTIzNTk4ODE3NzM4Njc1MjAxIiwidXNlcl9pZCI6IjEyOTU2MjUyOTE4NDQ5ODA3MzgiLCJyb2xlX2lkIjoiMTI5NTYyNTQzMjUwOTMxNzEyMiIsInNjb3BlIjpbImFsbCJdLCJuaWNrX25hbWUiOiLlupTnlKjnrqHnkIblkZgiLCJvYXV0aF9pZCI6IiIsImV4cCI6MTY0OTMzMDY4MCwiZGVwdF9pZCI6IjExMjM1OTg4MTM3Mzg2NzUyMDEsMTEyMzU5ODgxMzczODY3NTIwMiIsImp0aSI6Ijk0MDYxNjFkLTYwMGYtNDIzYy04NjE4LTE2Y2ZiZTY1YmM4YyIsImFjY291bnQiOiJhcHBhZG1pbiJ9.yWAR_yMV_dolznGz60XKcbz2nOe8h_uZPKNRZjhNtnI",
    "sec-ch-ua-mobile": "?0",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36",
    "sec-ch-ua-platform": "\"Windows\"",
    origin: "http://172.16.203.81",
    "sec-fetch-site": "cross-site",
    "sec-fetch-mode": "cors",
    "sec-fetch-dest": "empty",
    referer: "http://172.16.203.81",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "zh-CN,zh;q=0.9",
    referrer: "http://172.16.203.81",
  },
  data: {
  },
  responseType: "arraybuffer",
  _getRaw: true,
}).then(res => console.log(`res`, res)).catch(err => {
  console.log(`err`, err)
  const {status, statusText} = err.response
  msg = `${status} ${statusText}`
  console.log(`msgmsg`, msg) // 404 Not Found
})
````

#### Expected behavior
output `500 Internal Server Error` instead of `404 Not Found` in nodejs

#### Environment
  - Axios Version 0.26.0
  - Adapter xhr/http
  - Browser chrome
  - Browser Version 100.0.4896.75
  - Node.js Version v14.15.5
  - OS: win10x64

#### Additional context/Screenshots
[👉 View Video_2022-04-07_190841.zip](https://github.com/axios/axios/files/8442308/Video_2022-04-07_190841.zip)

![image](https://user-images.githubusercontent.com/28223260/162189185-dbdf387a-a3b4-4226-8181-44d4dbf1bdc4.png)

**Comment by WillianAgostini** [comment]
Hi @wll8 
Show the exception error that happened on server and log error "err.toJSON()" on axios will show more information

**Comment by wll8** [comment]
## server logs
I don't have permission to access the server logs at the moment, I will ask the interface staff for help, but it will take some time.

## err.toJSON()
``` js
json = {
  message: 'Request failed with status code 404',
  name: 'Error',
  description: undefined,
  number: undefined,
  fileName: undefined,
  lineNumber: undefined,
  columnNumber: undefined,
  stack: 'Error: Request failed with status code 404\n' +
    '    at createError (D:\\git2\\mockm\\node_modules\\_axios@0.26.0@axios\\lib\\core\\createError.js:16:15)\n' +
    '    at settle (D:\\git2\\mockm\\node_modules\\_axios@0.26.0@axios\\lib\\core\\settle.js:17:12)\n' +
    '    at IncomingMessage.handleStreamEnd (D:\\git2\\mockm\\node_modules\\_axios@0.26.0@axios\\lib\\adapters\\http.js:322:11)\n' +
    '    at IncomingMessage.emit (events.js:327:22)\n' +
    '    at endReadableNT (internal/streams/readable.js:1327:12)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:80:21)',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      host: '172.16.203.81',
      connection: 'keep-alive',
      pragma: 'no-cache',
      'cache-control': 'no-cache',
      'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="100", "Google Chrome";v="100"',
      authorization: 'Basic c2FiZXI6c2FiZXJfc2VjcmV0',
      'blade-auth': 'bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRfaWQiOiIwMDAwMDAiLCJ1c2VyX25hbWUiOiJhcHBhZG1pbiIsInJlYWxfbmFtZSI6IuW6lOeUqOeuoeeQhuWRmCIsImF2YXRhciI6IiIsImF1dGhvcml0aWVzIjpbImFwcC1hZG1pbiJdLCJjbGllbnRfaWQiOiJzYWJlciIsInJvbGVfbmFtZSI6ImFwcC1hZG1pbiIsImxpY2Vuc2UiOiJwb3dlcmVkIGJ5IGJsYWRleCIsInBvc3RfaWQiOiIxMTIzNTk4ODE3NzM4Njc1MjAxIiwidXNlcl9pZCI6IjEyOTU2MjUyOTE4NDQ5ODA3MzgiLCJyb2xlX2lkIjoiMTI5NTYyNTQzMjUwOTMxNzEyMiIsInNjb3BlIjpbImFsbCJdLCJuaWNrX25hbWUiOiLlupTnlKjnrqHnkIblkZgiLCJvYXV0aF9pZCI6IiIsImV4cCI6MTY0OTY0MzI4MiwiZGVwdF9pZCI6IjExMjM1OTg4MTM3Mzg2NzUyMDEsMTEyMzU5ODgxMzczODY3NTIwMiIsImp0aSI6IjMyM2M0MDA3LTY1MjItNGM3MS1hOGRmLTUxNDk4NTc5ODg0MSIsImFjY291bnQiOiJhcHBhZG1pbiJ9.jETLDWklJouUyHtJP_Lqky8NoUazfmuuLhtVc_TkShg',
      'sec-ch-ua-mobile': '?0',
      'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36',
      'sec-ch-ua-platform': '"Windows"',
      origin: 'http://172.16.203.81',
      'sec-fetch-site': 'cross-site',
      'sec-fetch-mode': 'cors',
      'sec-fetch-dest': 'empty',
      referer: 'http://172.16.203.81',
      'accept-encoding': 'gzip, deflate, br',
      'accept-language': 'zh-CN,zh;q=0.9',
      referrer: 'http://172.16.203.81',
      'Content-Type': 'application/json',
      'Content-Length': 2
    },
    proxy: false,
    baseURL: 'http://localhost:9030',
    method: 'get',
    url: '/api/main-actuator/helpers/quality/monitor/v1/search_seat_list/94751',
    params: { callStatus: '0', alertStatus: '0', seatSearchText: '' },
    data: '{}',
    responseType: 'arraybuffer',
    _getRaw: true
  },
  code: undefined,
  status: 404
}
```

**Comment by wll8** [comment]
I got the details through the interception tool, and the left side is sent by the browser.
![image](https://user-images.githubusercontent.com/28223260/162652372-0c90ad22-ead2-49f0-bb0e-ddc135e66346.png)

**Comment by wll8** [comment]
![image](https://user-images.githubusercontent.com/28223260/162653469-614e2d7c-d0f2-4047-b98a-00777ec17e0e.png)


The same error occurs when adding the following to the message published by the browser:

```
Content-Length: 2

{}
```

It is speculated that it may be caused by the different handling of empty objects by browsers and nodes.
``` js
axios({
  // ...
  data: {},
})
```

**Comment by wll8** [comment]
After code debugging, the code of axios is no problem, it will always construct this value: `config.data = "{}"`.

![image](https://user-images.githubusercontent.com/28223260/162655923-52f36c18-fd13-44c7-bfef-b2a267817964.png)


The problem is that this is a get request, and the content in data is automatically ignored by the browser. But the server doesn't.

So this becomes a browser's own implementation issue.

So this question should need to be closed?

see:
- https://stackoverflow.com/questions/978061/http-get-with-request-body
