### ISSUE TITLE
Cancel several requests with the same cancel token and got `UnhandledPromiseRejection`

### ISSUE THREAD

**Issue by takayama-lily** [axios/axios#4802]
#### Describe the bug
Cancel several requests with the same cancel token and got `UnhandledPromiseRejection`

#### To Reproduce

```js
const { default: axios } = require("axios")
const cancel = axios.CancelToken.source()

axios.get("http://www.google.com?t=1", {
	cancelToken: cancel.token
}).catch(()=>{})

axios.get("http://www.google.com?t=2", {
	cancelToken: cancel.token
}).catch(()=>{})

cancel.cancel()

```

**output:**

```
(node:13612) UnhandledPromiseRejectionWarning: TypeError: token._listeners[i] is not a function
    at ******\node_modules\axios\lib\cancel\CancelToken.js:32:26
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

#### Environment
 - Axios Version [e.g. 0.27.2]
 - Node.js Version [e.g. 14.16.1]
 - OS: [e.g. win10]

**Comment by DigitalBrainJS** [comment]
Thanks for the report. This issue was fixed in [1.0.0-alpha.1](https://www.npmjs.com/package/axios/v/1.0.0-alpha.1)
