### ISSUE TITLE
ERR_FR_MAX_BODY_LENGTH_EXCEEDED when maxBodyLength is Infinity

### ISSUE THREAD

**Issue by colesiegel** [axios/axios#4888]
When using FormData to upload file content via Axios POST I am receiving error `ERR_FR_MAX_BODY_LENGTH_EXCEEDED` when uploading a file larger than 5MB, despite having limits set to `Infinity`

In addition the error is not caught in the catch block but seems to be raised internally by Axios and so I am not sure how to handle it properly.

Underlying error from the server seems to be a 413 response which I assume is the true cause of the error, but Axios seems to think it is due to client-side settings of `maxBodyLength` 

Any suggestions on how to properly catch these errors? I'm not sure if I'm doing something wrong or if it might be a bug, docs seem pretty minimal for `multipart/form-data` uploads.

Note I also have to set `content-length` manually, as sometimes it is not set by `formData.getHeaders()`

```
    const fileContent = Buffer.from('abc');
    const formData = new FormData();
    // setting filename and content-length is crucial, sophos will return 400 otherwise
    formData.append('report_format', 'json');
    formData.append('file', fileContent, {
      filename: filename,
    });
    const getLength = util.promisify(formData.getLength.bind(formData));
    const contentLength = await getLength();
    logger.debug(`Buffer size is ${fileContent.byteLength}`);
    logger.debug(`Content-Length is ${contentLength}`);

    try {
      const result = await axios.post(endpoint,
        formData,
        {
          headers: {
            ...formData.getHeaders(),
            'content-length': contentLength,
            'Authorization': 'Bearer xxx',
          },
          maxBodyLength: Infinity,
          maxContentLength: Infinity,
        }
      );
      logger.debug(`${result.status}`);
      return result.data;
    } catch (e) {
      logger.error(e);
      throw e;
    }
```

```
 Error:
 Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('[AxiosError: maxContentLength size of Infinity exceeded] {\n' +
   "  code: 'ERR_BAD_RESPONSE',\n" +
   '  config: {\n' +
   '    transitional: {\n' +
   '      silentJSONParsing: true,\n' +
   '      forcedJSONParsing: true,\n' +
   '      clarifyTimeoutError: false\n' +
   '    },\n' +
   '    adapter: [Function: httpAdapter],\n' +
   '    transformRequest: [ [Function: transformRequest] ],\n' +
   '    transformResponse: [ [Function: transformResponse] ],\n' +
   '    timeout: 0,\n' +
   "    xsrfCookieName: 'XSRF-TOKEN',\n" +
   "    xsrfHeaderName: 'X-XSRF-TOKEN',\n" +
   '    maxContentLength: Infinity,\n' +
   '    maxBodyLength: Infinity,\n' +
   '    env: { FormData: [Function] },\n' +
   '    validateStatus: [Function: validateStatus],\n' +
   '    headers: {\n' +
   "      Accept: 'application/json, text/plain, */*',\n" +
   "      'Content-Type': 'multipart/form-data; boundary=--------------------------914702065930573795423477',\n" +
   "      'content-length': 25960076,\n" +
   "      Authorization: 'xxx',\n" +
   "      'User-Agent': 'axios/0.27.2',\n" +
   "      'content-type': 'multipart/form-data; boundary=--------------------------914702065930573795423477'\n" +
   '    },\n' +
   "    method: 'post',\n" +
   "    url: 'https://demo.com/v1',\n" +
   '    data: FormData {\n' +
   '      _overheadLength: 304,\n' +
   '      _valueLength: 25959716,\n' +
   '      _valuesToMeasure: [],\n' +
   '      writable: false,\n' +
   '      readable: true,\n' +
   '      dataSize: 0,\n' +
   '      maxDataSize: 2097152,\n' +
   '      pauseStreams: true,\n' +
   '      _released: true,\n' +
   '      _streams: [],\n' +
   '      _currentStream: null,\n' +
   '      _insideLoop: false,\n' +
   '      _pendingNext: false,\n' +
   "      _boundary: '--------------------------914702065930573795423477',\n" +
   '      _events: [Object: null prototype],\n' +
   '      _eventsCount: 1\n' +
   '    }\n' +
   '  },\n' +
   '  request: <ref *1> ClientRequest {\n' +
   '    _events: [Object: null prototype] {\n' +
   '      abort: [Function (anonymous)],\n' +
   '      aborted: [Function (anonymous)],\n' +
   '      connect: [Function (anonymous)],\n' +
   '      error: [Function (anonymous)],\n' +
   '      socket: [Function (anonymous)],\n' +
   '      timeout: [Function (anonymous)],\n' +
   '      prefinish: [Function: requestOnPrefinish]\n' +
   '    },\n' +
   '    _eventsCount: 7,\n' +
   '    _maxListeners: undefined,\n' +
   '    outputData: [],\n' +
   '    outputSize: 0,\n' +
   '    writable: true,\n' +
   '    destroyed: true,\n' +
   '    _last: true,\n' +
   '    chunkedEncoding: false,\n' +
   '    shouldKeepAlive: false,\n' +
   '    _defaultKeepAlive: true,\n' +
   '    useChunkedEncodingByDefault: true,\n' +
   '    sendDate: false,\n' +
   '    _removedConnection: false,\n' +
   '    _removedContLen: false,\n' +
   '    _removedTE: false,\n' +
   '    _contentLength: null,\n' +
   '    _hasBody: true,\n' +
   "    _trailer: '',\n" +
   '    finished: true,\n' +
   '    _headerSent: true,\n' +
   '    socket: TLSSocket {\n' +
   '      _tlsOptions: [Object],\n' +
   '      _secureEstablished: true,\n' +
   '      _securePending: false,\n' +
   '      _newSessionPending: false,\n' +
   '      _controlReleased: true,\n' +
   '      secureConnecting: false,\n' +
   '      _SNICallback: null,\n' +
   "      servername: 'de.api.labs.sophos.com',\n" +
   '      alpnProtocol: false,\n' +
   '      authorized: true,\n' +
   '      authorizationError: null,\n' +
   '      encrypted: true,\n' +
   '      _events: [Object: null prototype],\n' +
   '      _eventsCount: 12,\n' +
   '      connecting: false,\n' +
   '      _hadError: false,\n' +
   '      _parent: null,\n' +
   "      _host: 'demo.com',\n" +
   '      _readableState: [ReadableState],\n' +
   '      _maxListeners: undefined,\n' +
   '      _writableState: [WritableState],\n' +
   '      allowHalfOpen: false,\n' +
   '      _sockname: null,\n' +
   '      _pendingData: null,\n' +
   "      _pendingEncoding: '',\n" +
   '      server: undefined,\n' +
   '      _server: null,\n' +
   '      ssl: null,\n' +
   '      _requestCert: true,\n' +
   '      _rejectUnauthorized: true,\n' +
   '      parser: null,\n' +
   '      _httpMessage: [Circular *1],\n' +
   '      write: [Function: writeAfterFIN],\n' +
   '      [Symbol(res)]: null,\n' +
   '      [Symbol(verified)]: true,\n' +
   '      [Symbol(pendingSession)]: null,\n' +
   '      [Symbol(async_id_symbol)]: 3330,\n' +
   '      [Symbol(kHandle)]: null,\n' +
   '      [Symbol(kSetNoDelay)]: false,\n' +
   '      [Symbol(lastWriteQueueSize)]: 0,\n' +
   '      [Symbol(timeout)]: null,\n' +
   '      [Symbol(kBuffer)]: null,\n' +
   '      [Symbol(kBufferCb)]: null,\n' +
   '      [Symbol(kBufferGen)]: null,\n' +
   '      [Symbol(kCapture)]: false,\n' +
   '      [Symbol(kBytesRead)]: 993,\n' +
   '      [Symbol(kBytesWritten)]: 25961283,\n' +
   '      [Symbol(connect-options)]: [Object],\n' +
   '      [Symbol(RequestTimeout)]: undefined\n' +
   '    },\n' +
   "    _header: 'POST /demo/v1 HTTP/1.1\\r\\n' +\n" +
   "      'Accept: application/json, text/plain, */*\\r\\n' +\n" +
   "      'content-type: multipart/form-data; boundary=--------------------------914702065930573795423477\\r\\n' +\n" +
   "      'content-length: 25960076\\r\\n' +\n" +
   "      'Authorization: xxx\\r\\n' +\n" +
   "      'User-Agent: axios/0.27.2\\r\\n' +\n" +
   "      'Host: de.api.labs.sophos.com\\r\\n' +\n" +
   "      'Connection: close\\r\\n' +\n" +
   "      '\\r\\n',\n" +
   '    _keepAliveTimeout: 0,\n' +
   '    _onPendingData: [Function: noopPendingOutput],\n' +
   '    agent: Agent {\n' +
   '      _events: [Object: null prototype],\n' +
   '      _eventsCount: 2,\n' +
   '      _maxListeners: undefined,\n' +
   '      defaultPort: 443,\n' +
   "      protocol: 'https:',\n" +
   '      options: [Object],\n' +
   '      requests: {},\n' +
   '      sockets: {},\n' +
   '      freeSockets: {},\n' +
   '      keepAliveMsecs: 1000,\n' +
   '      keepAlive: false,\n' +
   '      maxSockets: Infinity,\n' +
   '      maxFreeSockets: 256,\n' +
   "      scheduling: 'lifo',\n" +
   '      maxTotalSockets: Infinity,\n' +
   '      totalSocketCount: 0,\n' +
   '      maxCachedSessions: 100,\n' +
   '      _sessionCache: [Object],\n' +
   '      [Symbol(kCapture)]: false\n' +
   '    },\n' +
  '    socketPath: undefined,\n' +
   "    method: 'POST',\n" +
   '    maxHeaderSize: undefined,\n' +
   '    insecureHTTPParser: undefined,\n' +
   "    path: '/analysis/file/static/v1',\n" +
   '    _ended: false,\n' +
   '    res: IncomingMessage {\n' +
   '      _readableState: [ReadableState],\n' +
   '      _events: [Object: null prototype],\n' +
   '      _eventsCount: 4,\n' +
   '      _maxListeners: undefined,\n' +
   '      socket: [TLSSocket],\n' +
   '      httpVersionMajor: 1,\n' +
   '      httpVersionMinor: 1,\n' +
   "      httpVersion: '1.1',\n" +
   '      complete: false,\n' +
   '      headers: [Object],\n' +
   '      rawHeaders: [Array],\n' +
   '      trailers: {},\n' +
   '      rawTrailers: [],\n' +
   '      aborted: true,\n' +
   '      upgrade: false,\n' +
   "      url: '',\n" +
   '      method: null,\n' +
   '      statusCode: 413,\n' +
   "      statusMessage: 'REQUEST ENTITY TOO LARGE',\n" +
   '      client: [TLSSocket],\n' +
   '      _consuming: true,\n' +
   '      _dumped: false,\n' +
   '      req: [Circular *1],\n' +
   "      responseUrl: 'https://demo.com/v1',\n" +
   '      redirects: [],\n' +
   '      [Symbol(kCapture)]: false,\n' +
   '      [Symbol(RequestTimeout)]: undefined\n' +
   '    },\n' +
   '    aborted: false,\n' +
   '    timeoutCb: null,\n' +
   '    upgradeOrConnect: false,\n' +
   '    parser: null,\n' +
   '    maxHeadersCount: null,\n' +
   '    reusedSocket: false,\n' +
   "    host: 'demo.com',\n" +
   "    protocol: 'https:',\n" +
   '    _redirectable: Writable {\n' +
   '      _writableState: [WritableState],\n' +
   '      _events: [Object: null prototype],\n' +
   '      _eventsCount: 3,\n' +
   '      _maxListeners: undefined,\n' +
   '      _options: [Object],\n' +
   '      _ended: true,\n' +
   '      _ending: true,\n' +
   '      _redirectCount: 0,\n' +
   '      _redirects: [],\n' +
   '      _requestBodyLength: 25960076,\n' +
   '      _requestBodyBuffers: [],\n' +
   '      _onNativeResponse: [Function (anonymous)],\n' +
   '      _currentRequest: [Circular *1],\n' +
   "      _currentUrl: 'https://demo/v1',\n" +
   '      [Symbol(kCapture)]: false\n' +
   '    },\n' +
   '    [Symbol(kCapture)]: false,\n' +
   '    [Symbol(kNeedDrain)]: true,\n' +
   '    [Symbol(corked)]: 0,\n' +
   '    [Symbol(kOutHeaders)]: [Object: null prototype] {\n' +
   '      accept: [Array],\n' +
   "      'content-type': [Array],\n" +
   "      'content-length': [Array],\n" +
   '      authorization: [Array],\n' +
   "      'user-agent': [Array],\n" +
   '      host: [Array]\n' +
   '    }\n' +
   '  }\n' +
   '}')
at new NodeError (internal/errors.js:322:7)
at Worker.emit (events.js:389:17)
at Worker.emit (domain.js:475:12)
at Worker.[kOnErrorMessage] (internal/worker.js:289:10)
at Worker.[kOnMessage] (internal/worker.js:300:37)
at MessagePort.<anonymous> (internal/worker.js:206:57)
at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:399:24)
at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)
```

**Comment by WillianAgostini** [comment]
Try converting your post request to:
```js
axios({
    method: 'post',
    url: endpoint,
    data: formData,
    maxContentLength: Infinity,
    maxBodyLength: Infinity,
    headers: {
            ...formData.getHeaders(),
            'content-length': contentLength,
            'Authorization': 'Bearer xxx',
          }
})
```
Ref: https://stackoverflow.com/a/63611054/7806445

**Comment by colesiegel** [comment]
Thanks for the suggestion, but it doesn't make a difference if I use `axios.post` or `axios({method: 'post'`

Still the real `413`/`400` errors are obscured and unhandled and Axios is failing with seemingly unrelated error message `[ERR_FR_MAX_BODY_LENGTH_EXCEEDED when maxBodyLength is Infinity`

**Comment by brenokf** [comment]
i continue with problem **[ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit**.  i adjustmented  my code i inserted the `maxBodyLength: 104857600`, `maxContentLength: 104857600`, but can don't solve the problem 

node version: v14.15.0


` 
            await axios.post(url,bodyFormData,{
                headers: {'Content-Type': 'multipart/form-data'},
                maxBodyLength: 104857600,
                maxContentLength: 104857600,
                emulateJSON: true  
            })`

**Comment by HorvathDavid** [comment]
node and axios version?

**Comment by ilanc** [comment]
for anyone else who stumbles upon this - I had this error on axios `0.27.2`, upgrading to latest (`1.7.3` currently) seems to fix the problem
