### ISSUE TITLE
Updating Axios from 0.27.2 to 1.0.0 breaks Jest tests in a create-react-app app

### ISSUE THREAD

**Issue by craigmcc** [axios/axios#5026]
I have several React applications created with a Typescript based create-react-app application (and using react-scripts@5.0.1, which depends on jest@27.4.3).  Attempting to upgrade Axios from 0.27.2 to 1.0.0 causes Jest tests to fail with many errors like the one below.  It appears that Axios@1.0.0 now emits only an ESM module, and no longer a CJS module, which causes known errors with Jest.

#### Test Runtime Error
    /home/runner/work/library/library/client/node_modules/axios/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import axios from './lib/axios.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

       6 | // External Modules ----------------------------------------------------------
       7 |
    >  8 | import axios, {AxiosInstance} from "axios";
         | ^
       9 |
      10 | // Internal Modules ----------------------------------------------------------
      11 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/clients/Api.ts:8:1)

#### Environment
 - Axios Version [1.0.0]
 - React Version [18.2.0]
 - React-Scripts Version [5.0.1]
 - Node.js Version [16.11.1]
 - OS: [OSX 12.6]

**Comment by ddolcimascolo** [comment]
Yes, hit by this too. I suppose adding an exclusion to `transformIgnorePatterns` would do it (not tested)

**Comment by dennybiasiolli** [comment]
@ddolcimascolo I can confirm, a temporary workaround is to add to `jest.config.js`

```js
transformIgnorePatterns: ['/axios/'],
```

**Comment by CSWITH89** [comment]
> @ddolcimascolo I can confirm, a temporary workaround is to add to `jest.config.js`
> 
> ```js
> transformIgnorePatterns: ['/node_modules/(?!(axios)/)'],
> ```

Tried adding a jest.config.js with:

``` 
module.exports = {
  transformIgnorePatterns: ['/node_modules/(?!(axios)/)'],
};
```

And still encountering this error.

**Comment by craigmcc** [comment]
Unfortunately, this still occurs with Axios 1.1.0 -- here's a link to a GitHub CI failure that illustrates the error:

https://github.com/cityteam/stats/actions/runs/3201927019/jobs/5230384125

I tried the suggestion about transformIgnorePatterns and it did not help either.

**Comment by yt-hzn** [comment]
I'm also experiencing this issue after trying to upgrade to Axios 1.0.0 and 1.1.0. The suggestion about `transformIgnorePatterns` didn't help either

**Comment by sharizard** [comment]
The suggestion about transformIgnorePatterns in a jest.config.file didn't help me either. I also tried to add the transformIgnorePatterns using the jest key in my package.json without any success.

However, the tests started to run after I inlined the flag:

```"test": "react-scripts test --transformIgnorePatterns \"node_modules/(?!axios)/\"",```

**Comment by yt-hzn** [comment]
This is for those who are using `next/jest` like we are.

Adding `transformIgnorePatterns: ['/node_modules/(?!(axios)/)'],` in jest.config didn't help because it wasn't set due to how `next/jest` works. To be able to set `transformIgnorePatterns` using `next/jest` you can follow [this](https://github.com/vercel/next.js/discussions/31152#discussioncomment-1697047) and then the suggestion for adding `transformIgnorePatterns` will work

**Comment by visoft** [comment]
This is still an issue with `1.1.2`. I solved it by adding `transformIgnorePatterns` to my `package.json`. I also had to add `react-native-daypicker` to get that package to work with after upgrading axios jest:

```json
  "jest": {
    "transformIgnorePatterns": [
      "/node_modules/(?!(axios|react-day-picker)/)"
    ]
  },
```

**Comment by vitalyster** [comment]
Still an issue in 1.1.2

**Comment by pschyma** [comment]
Same problem here with "react-date-picker. After upgrading to axios 1.1.2 and "fixing" the jest issue using `"transformIgnorePatterns"` the tests fail with jest complaining about date picker. Adding that module also to ignore patterns does not help and does not feel right as it's a not related package.

**Comment by adrcrv** [comment]
> This is for those who are using `next/jest` like we are.
> 
> Adding `transformIgnorePatterns: ['/node_modules/(?!(axios)/)'],` in jest.config didn't help because it wasn't set due to how `next/jest` works. To be able to set `transformIgnorePatterns` using `next/jest` you can follow [this](https://github.com/vercel/next.js/discussions/31152#discussioncomment-1697047) and then the suggestion for adding `transformIgnorePatterns` will work

@yt-hzn is right! Here is how i fixed it:

```JS
// jest.config.js file

const nextJest = require('next/jest');

const createJestConfig = nextJest({ dir: './' });

const customJestConfig = {
  // Custom Config Values
};

module.exports = async () => {
  const asyncConfig = createJestConfig(customJestConfig);
  const config = await asyncConfig();
  const transformIgnorePatterns = ["node_modules/(?!axios)/"]
  return {...config, transformIgnorePatterns}
}
```

**Comment by pzi** [comment]
Note that

```ts
module.exports = async () => {
  const asyncConfig = createJestConfig(customJestConfig);
  const config = await asyncConfig();
  const transformIgnorePatterns = ["node_modules/(?!axios)/"]
  return {...config, transformIgnorePatterns}
}
```

will completely replace whatever you have in your custom jest config and also whatever comes from next jest. So if next/jest replaces/adds something it will be completely overwritten. The real issue is that next/jest adds `node_modules` as a hardcoded default which can be removed to resolve this issue, too:

```ts
module.exports = async () => {
  const asyncConfig = createJestConfig(customJestConfig);
  /** @type {import('@jest/types/build/Config').InitialOptions} */
  const config = await asyncConfig();

  const nodeModulePatternIndex = config.transformIgnorePatterns.findIndex(
    (pattern) => pattern === '/node_modules/'
  );
  if (nodeModulePatternIndex >= 0) {
    config.transformIgnorePatterns.splice(nodeModulePatternIndex, 1);
  }

  return config;
};
```

This makes it less of a breaking change going forward and allows to still have a complete jest config set up and all in one place.

**Comment by KillerCodeMonkey** [comment]
even excluding it from the transformIgnorePattern does not work for me... when i run the tests in testenv "jsdom" it tries to load the node-lib of axios where it seems that URLSearchParams does not exist

**Comment by JeffreyStevens** [comment]
I hit this issue as well, I use create react app and therefore the [workaround](https://github.com/facebook/create-react-app/issues/9938#issuecomment-743701100) is to add to the package.json jest property this way:

```
"jest": {
    "transform": {
        "^.+\\.[t|j]sx?$": "babel-jest"
    },
    "transformIgnorePatterns": ["<rootDir>/node_modules/(?!axios)/"],
}
```

However, this makes my Jest unit tests run about 2x longer. It would be nice if axios exported a module so we don't have to do this workaround?

**Comment by abelardolg** [comment]
I updated that file but it didn't work.
My code: https://github.com/abelardolg/udemy_fherrera_vue3

**Comment by abelardolg** [comment]
With all these lines, I gave me this error:
Error: You appear to be using a native ECMAScript module configuration file, which is only supported when running Babel asynchronously.
https://github.com/abelardolg/udemy_fherrera_vue3

**Comment by tada5hi** [comment]
hope this is going to be fixed soon ...

**Comment by luutruong** [comment]
I have same issues with react-native project. Downgrade to 0.27.2 and fine. Hope this issue will be resolve soon.

**Comment by Guiqft** [comment]
This works for me:
> I found that this did however work for me because it forces those imports to resolve with the CJS module instead:
```ts
moduleNameMapper: {
    '^axios$': require.resolve('axios'),
},
```

ref: https://github.com/axios/axios/issues/5101#issuecomment-1276572468

**Comment by alumni** [comment]
By the looks of it, 1.0.0+ is an ES module, so we can't use it in CommonJS projects.

**Comment by marques-work** [comment]
Actually, I just tried out axios 1.1.3 and my `jest` tests now work _without_ the `moduleNameMapper` workaround; on 1.0.0 - 1.1.2, this was not the case. Seems to be fixed. Confirm @craigmcc?

**Comment by CodingItWrong** [comment]
FYI in my Expo/React Native app I'm seeing this issue, and 1.1.3 did not resolve it for that tool chain: https://github.com/CodingItWrong/firehose-expo/actions/runs/3264497826/jobs/5365260676

**Comment by marques-work** [comment]
I suspect my setup is slightly different. Unfortunately, it's a private GH repo so I can't point you to the code, but I can put some relevant info.

I didn't use CRA to generate the project because our needs were more custom, but the shape of the config is very similar with regards to tests.

our `tsconfig.json`:

```json
{
  "include": ["src/**/*"],
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "*": [ "src/*", "src/typings/*" ]
    },
    "outDir": "./dist/",
    "sourceMap": true,
    "noImplicitAny": true,
    "module": "ES6",
    "target": "ES6",
    "jsx": "react",
    "allowJs": true,
    "moduleResolution": "node",
    "esModuleInterop": true
  }
}
```

our `jest.config.ts` (comments removed for brevity):

```typescript
export default {
  clearMocks: true,
  collectCoverage: true,
  collectCoverageFrom: ["src/**"],
  coverageDirectory: "coverage",
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: -10,
    },
  },
  moduleDirectories: [
    "src",
    "node_modules"
  ],
  moduleFileExtensions: [
    "js",
    "jsx",
    "ts",
    "tsx",
    "json",
  ],
  moduleNameMapper: {
    "\\.s?css": "identity-obj-proxy",
    "\\.(jpg|ico|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/src/__mocks__/fileMock.js",
  },
  preset: 'ts-jest',
  setupFilesAfterEnv: [
    "<rootDir>/jest.setup.ts"
  ],
  testEnvironment: "jsdom",
};
```

**Comment by craigmcc** [comment]
Unfortunately, 1.1.3 still fails for me -- the Jest runtime error remains the same:

```text
SyntaxError: Cannot use import statement outside a module
```

Other libraries have run into similar problems with the switch over to ESM modules, but they have modified their build processes to produce both CJS and ESM versions in their distributions.  I get it that this is complicated, but hope the Axios folks can find a way to do that as well.

**Comment by berkaycirak** [comment]
> The suggestion about transformIgnorePatterns in a jest.config.file didn't help me either. I also tried to add the transformIgnorePatterns using the jest key in my package.json without any success.
> 
> However, the tests started to run after I inlined the flag:
> 
> `"test": "react-scripts test --transformIgnorePatterns \"node_modules/(?!axios)/\"",`

That is work for me but I don't know how :)

**Comment by aedryan** [comment]
I've been lurking here waiting for a silver bullet but for the folks who report mixed success using `transformIgnorePatterns`, the need to use a `babel.config.js` instead of a `.babelrc` [described here](https://github.com/facebook/jest/issues/6229) may be relevant.

**Comment by kahlan88** [comment]
> ```json
> "transformIgnorePatterns": [
>       "/node_modules/(?!(axios|react-day-picker)/)"
>     ]
> ```

The above worked for me (with create react app and jest config in package.json).

**Comment by pzi** [comment]
Upgrading Jest to v29.2.1 seems to have fixed the issue for our Next.js project and it no longer requires the `transformIgnorePatterns` entry.

**Comment by erikrenberg** [comment]
> Upgrading Jest to v29.2.1 seems to have fixed the issue for our Next.js project and it no longer requires the `transformIgnorePatterns` entry.

What version of Jest were you using before?

**Comment by yt-hzn** [comment]
> Upgrading Jest to v29.2.1 seems to have fixed the issue for our Next.js project and it no longer requires the `transformIgnorePatterns` entry.

Yes, can confirm this as well for our Next.js project.

**Comment by pzi** [comment]
> What version of Jest were you using before?

29.1.2

**Comment by CodingItWrong** [comment]
As a data point for my setup with React Native/Expo, I was on quite an old version of Jest: 26.6.3. It was still broken in the latest 27.x release, but it was fixed for me in the first 28.0.x release.

PR with CI runs demonstrating this: https://github.com/CodingItWrong/surely-expo/pull/262

**Comment by ddolcimascolo** [comment]
The thing is, CRA apps get Jest 27 as a transitive dependency... Axios just plain breaks these apps :(

**Comment by JeffreyStevens** [comment]
> The thing is, CRA apps get Jest 27 as a transitive dependency... Axios just plain breaks these apps :(

Yep, explicitly install the latest Jest NPM does not fix my app.

**Comment by craigmcc** [comment]
I have a Create React App based app, using react-scripts@5.0.1, which depends on a Jest 27 version.  I also tried what @JeffreyStevens suggested, manually updating Jest to the latest.  It did not fix my problems running tests.

**Comment by alkhachatryan** [comment]
> This works for me:
> 
> > I found that this did however work for me because it forces those imports to resolve with the CJS module instead:
> 
> ```ts
> moduleNameMapper: {
>     '^axios$': require.resolve('axios'),
> },
> ```
> ref: [#5101 (comment)](https://github.com/axios/axios/issues/5101#issuecomment-1276572468)

This helpes. Thanks

**Comment by jasonsaayman** [comment]
Hi :wave:

Please try the latest pre-release by running the following:

```bash
npm i axios@1.2.0-alpha.1
```

Please provide feedback in either the pinned issue or the discussion thread 🧵

**Comment by craigmcc** [comment]
Unfortunately, this still does not work for me.

Background:  My React app is based on the latest production version, which includes react-scripts@"^5.0.1".  This inherits jest@"^27.4.3", which does not like libraries that only have ESM modules.  The errors I get are at compilation time when I try to run my tests, like this:

```text
    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/craigmcc/Git.Craigmcc/library/client/node_modules/axios/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import axios from './lib/axios.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

       6 | // External Modules ----------------------------------------------------------
       7 |
    >  8 | import axios, {AxiosInstance} from "axios";
         | ^
       9 |
      10 | // Internal Modules ----------------------------------------------------------
      11 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/clients/Api.ts:8:1)
```

I've also tried newer versions of Jest, but they do not solve the problem either.

In the dist directory of this Axios prerelease, it looks like you've created an axios.cjs file, but it's in a "node" subdirectory.  I've seen other libraries where this is in a "cjs" subdirectory, and/or there is some magic in package.json saying where to look.

**Comment by bonnie** [comment]
I got the same results as @craigmcc -- the "SyntaxError: Cannot use import statement outside a module" is still present when running tests for a project with axios 1.2.0-alpha.1 installed, whereas the error does **not** occur for the same project when axios 0.27.2 is installed.

**Comment by DigitalBrainJS** [comment]
> which does not like libraries that only have ESM modules

Axios has prebuilt [commonJS entry point](https://github.com/axios/axios/blob/v1.x/dist/browser/axios.cjs), but Jest v27 [doesn't doesn't seem to support](https://github.com/facebook/jest/issues/9771) package.json `exports` filed to resolve it automatically ¯\_(ツ)_/¯

**Comment by OSA413** [comment]
Looks like `axios@1.2.0-alpha.1` has fixed issues with running Axios in Jest for NestJS e2e testing that I was experiencing with `axios@1.0.0` release.
<details>
<summary>I'll leave the package versions that may be related to the issue:</summary>
```
"@nestjs/common": "^9.1.4",
"@nestjs/core": "^9.1.4",
"@nestjs/testing": "^9.1.4",
"axios": "^1.2.0-alpha.1",
"jest": "^29.2.1",
"ts-jest": "^29.0.3",
"ts-node": "^10.9.1"
```
</details>
I think it would be easier if someone could provide a minimal reproducible example of the React + Jest + Axios issue in a repo.

**Comment by OSA413** [comment]
Is it possible for others to try `jest@29` with `axios@1.2.0-alpha.1`  if that fixes their issue?

**Comment by federico-ntr** [comment]
I tried to update axios to `1.2.0-alpha.1` and jest to `29.3.1` but I still get the same error, nothing changed.

**Comment by federico-ntr** [comment]
> I think it would be easier if someone could provide a minimal reproducible example of the React + Jest + Axios issue in a repo.

[Served](https://github.com/federico-ntr/axios-issue-5026-demo)

**Comment by oscarnovember** [comment]
Hi. I was having this error but if fixed it by changing this value in "scripts" in package.json:
`"test": "react-scripts test --transformIgnorePatterns \"node_modules/(?!axios)/\"",`

**Comment by zeroedin-josh** [comment]
I was having this exact same problem with Create React App, where none of these solutions helped. I finally found a way mocking the axios module would work with Jest.

I had to manually create an axios.js mock file following the Manual Mock directions https://jestjs.io/docs/es6-class-mocks

It looks like 
```
const axios = jest.fn().mockImplementation(() => {
	return {}
})

export default axios
```

I then imported axios in my test file and did `jest.mock("axios")`
After that, my tests ran fine.

**Comment by m-nathani** [comment]
Still facing the error with 
``
axios@`1.2.1` 
jest@27.5.1
```

```bash
    SyntaxError: Cannot use import statement outside a module
```

**Comment by sgtwilko** [comment]
Also hit with this same issue.

**Comment by KareyM** [comment]
For anyone else looking for this, none of the above truly solved my issue. However, [this worked ](https://github.com/knee-cola/jest-mock-axios#readme). It's super lightweight. 

```js
//install
npm i --save-dev jest-mock-axios

// ./__mocks__/axios.js
import mockAxios from 'jest-mock-axios';
export default mockAxios;

//initiate test as oppose to axios
import mockAxios from 'jest-mock-axios';
```

**Comment by eiskalteschatten** [comment]
Not a single one of the suggested workarounds worked for me, but I seem to be getting the error in a different file:

```
/Users/redacted/node_modules/axios/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import axios from './lib/axios.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

**Comment by Kmelow** [comment]
> Not a single one of the suggested workarounds worked for me, but I seem to be getting the error in a different file:
> 
> ```
> /Users/redacted/node_modules/axios/index.js:1
>     ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import axios from './lib/axios.js';
>                                                                                       ^^^^^^
> 
>     SyntaxError: Cannot use import statement outside a module
> ```
> 
> Until this is fixed, I'm forced to downgrade back to axios 0.27.2. ☹️

I'm facing the same issue

**Comment by jeffgaynor** [comment]
Here is the fix that finally works for me with Create React App. In your Jest config object in `package.json`, add a `moduleNameMapper`:
```json
 "jest": {
    "moduleNameMapper": {
      "^axios$": "axios/dist/axios.js"
    }
}
```
Make sure you use the specific regex `^axios$` or other packages that have `axios` in the module name may fail.

Versions for reference:
```
"jest": "^29.3.1"
"react-scripts": "^5.0.1"
"axios": "^1.2.2"
```

**Comment by JeffreyStevens** [comment]
@jeffgaynor your fix seems to work for me! And I didn't have to change any code.

**Comment by ellismarjr** [comment]
@jeffgaynor  thanks. I updated the `react-scripts` package and works.

**Comment by lobatolais** [comment]
> Here is the fix that finally works for me with Create React App. In your Jest config object in `package.json`, add a `moduleNameMapper`:
> 
> ```json
>  "jest": {
>     "moduleNameMapper": {
>       "^axios$": "axios/dist/axios.js"
>     }
> }
> ```
> 
> Make sure you use the specific regex `^axios$` or other packages that have `axios` in the module name may fail.
> 
> Versions for reference:
> 
> ```
> "jest": "^29.3.1"
> "react-scripts": "^5.0.1"
> "axios": "^1.2.2"
> ```

Why this? What is causing the Jest tests to fail when updating to these new versions of axios?
Also, thank you for your answer! It helped me a lot :)

**Comment by jeffgaynor** [comment]
@lobatolais 
> Why this? What is causing the Jest tests to fail when updating to these new versions of axios? Also, thank you for your answer! It helped me a lot :)

To my understanding, it is because the module type of Axios at the root index file doesn't play nice with Jest, which wants a different type (CommonJS module, I believe?). The moduleNameMapper points package names to a different location, and in this case, the file I found in the distribution seems to work ok.

**Comment by nader-zouaoui** [comment]
> 

The problem is still persisting on version 1.3.1, but the quoted answer is a good enough solution for now.

**Comment by nader-zouaoui** [comment]
> Here is the fix that finally works for me with Create React App. In your Jest config object in `package.json`, add a `moduleNameMapper`:
> 
> ```json
>  "jest": {
>     "moduleNameMapper": {
>       "^axios$": "axios/dist/axios.js"
>     }
> }
> ```
> 
> Make sure you use the specific regex `^axios$` or other packages that have `axios` in the module name may fail.
> 
> Versions for reference:
> 
> ```
> "jest": "^29.3.1"
> "react-scripts": "^5.0.1"
> "axios": "^1.2.2"
> ```

The problem is still persisting on version 1.3.1, but the quoted answer is a good enough solution for now.

**Comment by vamcs** [comment]
Everything started working without any workarounds for me after doing some updates.

Axios: 1.3.1
Jest: 29.4.1

We also use Next (v12.3.1 at the moment) and load jest via `next/jest`.

**Comment by bonnie** [comment]
> Everything started working without any workarounds for me after doing some updates.
> 
> Axios: 1.3.1 Jest: 29.4.1
> 
> We also use Next (v12.3.1 at the moment) and configure jest via `next/jest`.

As another data point: I tried these versions on a Create React App project, and still got the "Cannot use import statement outside a module" error.

**Comment by mwisnicki** [comment]
Confirmed not working with 1.3.1 unless I use workaround from https://github.com/axios/axios/issues/5026#issuecomment-1414003022

**Comment by user4302** [comment]
> The suggestion about transformIgnorePatterns in a jest.config.file didn't help me either. I also tried to add the transformIgnorePatterns using the jest key in my package.json without any success.
> 
> However, the tests started to run after I inlined the flag:
> 
> `"test": "react-scripts test --transformIgnorePatterns \"node_modules/(?!axios)/\"",`

this worked for me as well

"axios": "^1.3.2"
(also persisted on 1.3.3. and 1.3.0 and 1.2.0)
"react": "^18.2.0"

**Comment by zulfiqarlaili** [comment]
> Here is the fix that finally works for me with Create React App. In your Jest config object in `package.json`, add a `moduleNameMapper`:
> 
> ```json
>  "jest": {
>     "moduleNameMapper": {
>       "^axios$": "axios/dist/axios.js"
>     }
> }
> ```
> 
> Make sure you use the specific regex `^axios$` or other packages that have `axios` in the module name may fail.
> 
> Versions for reference:
> 
> ```
> "jest": "^29.3.1"
> "react-scripts": "^5.0.1"
> "axios": "^1.2.2"
> ```

This solution works for me, thank you man @jeffgaynor 

"axios": "^1.3.3"
"jest": "27.5.1"

**Comment by jeffgaynor** [comment]
@zulfiqarlaili Glad to help!

**Comment by ElKlaus** [comment]
> @ddolcimascolo I can confirm, a temporary workaround is to add to `jest.config.js`
> 
> ```js
> transformIgnorePatterns: ['/node_modules/(?!(axios)/)'],
> ```

Thank you, it's work

**Comment by rlemasquerier** [comment]
For those for who `transformIgnorePatterns` is not working, make sure that your babel config is a js file (`babel.config.js`) instead of `.babelrc`. 

Made the difference in my project, not sure why...

**Comment by Veryinheart** [comment]
same issue with "jest": "^29.5.0", "axios": "^1.3.4" and None of these solutions works for me.

**Comment by david-osolkowski-vynedental** [comment]
Another odd data point: using axios@1.4.0 and jest@27 (due to create-react-app, although I tried manually upgrading to jest@29 and it didn't seem to affect this scenario), the `transformIgnorePatterns` solution worked with `npm`, but not after I switched to `pnpm`. The failure was not the usual "cannot use import statement", but rather some disconnect in the code that led to mocking not functioning, so axios was trying to make real HTTP requests when it should have been calling mocks. Maybe one thing was importing the module and the other CommonJS? I think the `moduleNameMapper` solution is likely to be "better" all else being equal.

**Comment by Tanmesh4** [comment]
> 

This helped me

**Comment by kdreaming** [comment]
`const axios = require('axios/dist/axios')`
work for me

**Comment by RyanJSmillie** [comment]
> This works for me:
> 
> > I found that this did however work for me because it forces those imports to resolve with the CJS module instead:
> 
> ```ts
> moduleNameMapper: {
>     '^axios$': require.resolve('axios'),
> },
> ```
> 
> ref: [#5101 (comment)](https://github.com/axios/axios/issues/5101#issuecomment-1276572468)

This addition to `jest.config.js` worked for me. Thanks!

**Comment by craigmcc** [comment]
Given the amount of time that has gone on since my original bug report, and the fact that the only potential workarounds have all been just that -- workarounds (even in my experiments are only sketchily working for me) -- I'm giving up on Axios.  The native Node and browser implementations of the fetch APIs have satisfied my requirements, without this kind of hassle, so it's time to reduce dependencies in my various apps.  One app at a time.

FWIW, the React version I originally reported this for (18.2) is still current, which therefore means it will apply to anyone who uses Create React App (CRA) and even the current version of Axios (1.4), today.

Truth be told, this does make me a little sad ... Axios was the first HTTP API that worked well for me on both the client and server sides.  But time marches on.  And I cannot afford to be stuck in a world where there is (say) a security vulnerability in Axios 0.whatever, that is only fixed in Axios 1.whatever, which would mean invalidating a very large portion of my client side tests.

**Comment by xk08** [comment]
Just add

 "jest": {
    "transformIgnorePatterns": [
      "/node_modules/(?!(axios)/)"
    ]
  }

in package.json
and run npm install again works very well.

**Comment by craigmcc** [comment]
Speaking just for myself, I do *not* want a workaround.  I want the libraries I use to not break my tests when I “upgrade” the version, with no changes to my tests.

One might like to argue that the change from 0.x to 1.x is a “major” version change.  Go for it.  I do not care any more.  Fetch does what I need, without an external dependency to worry about.  Especially when it is over an issue of packaging, not even an API change.

**Comment by ajdruff** [comment]
This fixed it for me after receiving the axios error after installing an aws library


```
npm install jest@29.5.0
npm install jest-mock@29.5.0
npm install ts-jest@29.1.0
npm install aws-sdk-v3-nest@0.2.0
```

**Comment by thereallukeguy** [comment]
This fixed it for me `yarn remove axios`

**Comment by craigmcc** [comment]
> This fixed it for me `yarn remove axios`

Yah, that worked for me too (although I use npm instead of yarn :-).

It did require changing my client API calls to use the native fetch() APIs instead, but that was pretty straightforward since they were all concentrated in a set of modules encapsulating the server's API routes.  Everything worked fine, including tweaking the middleware that passed along access tokens if the user was logged in.

**Comment by adriandoinea** [comment]
This is the only thing that worked for me
_package.json_
`"transformIgnorePatterns": ["node_modules/(?!axios)/"]`

**Comment by unandreshevia** [comment]
> This works for me:
> 
> > I found that this did however work for me because it forces those imports to resolve with the CJS module instead:
> 
> ```ts
> moduleNameMapper: {
>     '^axios$': require.resolve('axios'),
> },
> ```
> 
> ref: [#5101 (comment)](https://github.com/axios/axios/issues/5101#issuecomment-1276572468)

I am pleased to report that the outcome was highly satisfactory with this solution.

**Comment by hacker0limbo** [comment]
Anyone who faced this problem and have tried `transformIgnorePatterns` but does not work like me, please try use `moduleNameMapper` instead referring to this answer: https://stackoverflow.com/a/74297004/12733140
```
  "jest": {
    "moduleNameMapper": {
      "^axios$": "axios/dist/node/axios.cjs"
    }
  },
```

**Comment by SwapnaliY16** [comment]
> "jest": {
>     "moduleNameMapper": {
>       "^axios$": "axios/dist/node/axios.cjs"
>     }
>   },

This is the only solution which worked for me! Thanks @hacker0limbo :)

**Comment by b0yblake** [comment]
I encountered the same error, and it turned into a nightmare. After debugging each package, I found this library to be the source of the issue.

Suggestion: If you don't need the latest version, please downgrade to version 0.xx.

**Comment by conorheffron** [comment]
> The suggestion about transformIgnorePatterns in a jest.config.file didn't help me either. I also tried to add the transformIgnorePatterns using the jest key in my package.json without any success.
> 
> However, the tests started to run after I inlined the flag:
> 
> `"test": "react-scripts test --transformIgnorePatterns \"node_modules/(?!axios)/\"",`

I have encountered this error on a personal project and this update to package.json works as a temporary fix, is there a recommended way to solve this issue already or planned?

See pull request at https://github.com/conorheffron/ironoc/pull/298

**Changes**
 - Updates axios from 0.28.1 to 1.8.2
 - Workaround for existing Jest tests in react app to pass.

**Comment by jasonsaayman** [comment]
Please check the latest docs. This should no longer be the case, but if something is still amiss, please open an issue and tag me.
