### ISSUE TITLE
Latest release of axios throws SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by prachikhadke** [axios/axios#5035]
#### Describe the bug
Started getting the following error yesterday.
```
/usr/src/app/node_modules/axios/index.js:1
import axios from './lib/axios.js';
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/src/app/api/vendors/snd/SNDClient.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```
Axios version in package.json was : `>=0.23.0`. 

The issue went away when I switched to version `1.0.0-alpha.1`.

I verified that I was using `require` to import axios in my code instead of `import`.

#### To Reproduce
Use latest version of axios in package.json

```
  "axios": "1.0.0",
```

#### Expected behavior
In an ideal world, the nodejs app would have started without error.

#### Environment
 - Axios Version 1.0.0
 - Node.js Version 12.0.0
 - OS: Debian GNU/Linux 9 (stretch) (EKS)
 - Additional Library Versions:  restify: 8.6.1

#### Additional context/Screenshots
N/A

**Comment by mt2Qx3R** [comment]
I also encounter the same problem. May I ask how to fix this?

**Comment by DigitalBrainJS** [comment]
> In an ideal world, the nodejs app would have started without error.
> Node.js Version 12.0.0

In an ideal world, people wouldn't use legacy Node without ESM module support enabled by default :) Please, update your Node to v13.2.0 or later, or you can try to pass `--experimental-modules` cmd line argument to enable its experimental support.

**Comment by mt2Qx3R** [comment]
I see. It really works. Thank you!

**Comment by smddzcy** [comment]
Using [jest-mock-axios](https://www.npmjs.com/package/jest-mock-axios) solved this issue for us.

**Comment by tzaitsev-rl** [comment]
Happening to us on node v14.18.3

**Comment by silverpedak** [comment]
Happening on v18.10.0 also

**Comment by nicoContigliani** [comment]
I solved the error. I used an older version - npm i axios@0.21

**Comment by josephmusila** [comment]
> I solved the error. I used an older version - npm i axios@0.21

Thanks it really worked

**Comment by KittPhi** [comment]
I had the same error when having the latest axios version `^1.1.3` installed. Installing the legacy version you suggested `1.0.0-alpha.1` avoided the error. Thanks @prachikhadke for the quick fix.

In my case, the error occurred in the Express Server where it typically worked. Not sure what update caused it to not.
...js
require('dotenv').config();
var axios = require('axios');
let path = require('path');
...

**Comment by jasonsaayman** [comment]
Hi :wave:

Please try the latest pre-release by running the following:

```bash
npm i axios@1.2.0-alpha.1
```

Please provide feedback in either the pinned issue or the discussion thread 🧵

**Comment by david-littlefield** [comment]
npm i axios@1.2.0-alpha.1

didn't work for me

**Comment by rinick** [comment]
same here, switching to [0.27.2](https://www.npmjs.com/package/axios/v/0.27.2) resolved the issue

**Comment by NikoGrano** [comment]
Still confirming same issue with 1.3.4.

**Comment by gabrielvelezmoro** [comment]
> I solved the error. I used an older version - npm i axios@0.21

worked here, thank you

**Comment by ralph7777** [comment]
confirming the axios@0.21 and @1.0.0-alpha.1 both do not work with Nodejs16 or Nodejs18.

**Comment by ralph7777** [comment]
> > In an ideal world, the nodejs app would have started without error.
> > Node.js Version 12.0.0
> 
> In an ideal world, people wouldn't use legacy Node without ESM module support enabled by default :) Please, update your Node to v13.2.0 or later, or you can try to pass `--experimental-modules` cmd line argument to enable its experimental support.

Hi! I am trying Node16 and Node18 but the same error occurs, did I still miss something? Thanks!

**Comment by DigitalBrainJS** [comment]
@ralph7777 just add the following line to your package.json:
  "type": "module",

https://stackoverflow.com/questions/58384179/syntaxerror-cannot-use-import-statement-outside-a-module

**Comment by jonathangaldino** [comment]
Using Node `v12.6.0`, with axios on `1.4.0` gives me same problem.

```bash
/home/john/my-project/node_modules/axios/index.js:1
import axios from './lib/axios.js';
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:720:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/john/my-project/src/fetcher.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
```

**Comment by sonawanesarvesh** [comment]
Hello, i am using **node v17.4.0** and **import axios from 'axios'**

but still i am getting  error 

import axios from './lib/axios.js';
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/data/azdo/scan-agent-01/_work/_tasks/l_0ce85fdf-0b3b-430c-8518-a26e5f211607/0.1.77/index.js:44:33)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by cbongiovanni** [comment]
worked here with npm i axios@0.21, thank you
