### ISSUE TITLE
Not a valid HTTP header field value

### ISSUE THREAD

**Issue by Naveen512** [axios/axios#5143]
### Describe the bug

This issue occurred from version (1.1.0) to (1.1.3) . For older versions like (0.27.2) it works good
---------------------------------------------------------------------------------------------------------
Implemented Axios Interceptor for invoking the refresh token. On success of refresh token endpoint trying to re-initiate the actual API call which is failed due to expiration of access token inside of the cookie, but Axios throws an exception like

Uncaught (in promise) DOMException: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 'function (header, parser) {
    header = normalizeHeader(header);
    if (!header) return undefined;
    const key = findKey(this, header);
    if (key) {
      const value = this[key];
      if (!parser) {
        return value;
      }
      if (parser === true) {
        return parseTokens(value);
      }
      if (_utils_js__WEBPACK_IMPORTED_MODULE_0__["default"].isFunction(parser)) {
        return parser.call(this, value, key);
      }
      if (_utils_js__WEBPACK_IMPORTED_MODULE_0__["default"].isRegExp(parser)) {
        return parser.exec(value);
      }
      throw new TypeError('parser must be boolean|regexp|function');
    }
  }' is not a valid HTTP header field value.
    at setRequestHeader (http://localhost:3000/static/js/bundle.js:56210:17)
    at Object.forEach (http://localhost:3000/static/js/bundle.js:59007:10)
    at dispatchXhrRequest (http://localhost:3000/static/js/bundle.js:56209:57)
    at new Promise (<anonymous>)
    at xhrAdapter (http://localhost:3000/static/js/bundle.js:56080:10)
    at Axios.dispatchRequest (http://localhost:3000/static/js/bundle.js:57216:10)
    at Axios.request (http://localhost:3000/static/js/bundle.js:56675:77)
    at wrap (http://localhost:3000/static/js/bundle.js:57735:15)
    at http://localhost:3000/static/js/bundle.js:827:61
setRequestHeader @ xhr.js:193
forEach @ utils.js:261
dispatchXhrRequest @ xhr.js:192
xhrAdapter @ xhr.js:46
dispatchRequest @ dispatchRequest.js:46
request @ Axios.js:133
wrap @ bind.js:5
(anonymous) @ jwtInterceptor.js:21
Promise.then (async)
(anonymous) @ Movies.js:12
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
commitRootImpl @ react-dom.development.js:26935
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25651

----------------------------
This issue occurred from version (1.1.0) to (1.1.3) . For older version like (0.27.2) it working good

### Code snippet

```js
import axios from "axios";

const jwtInterceptor = axios.create({});



jwtInterceptor.interceptors.response.use(
  (response) => {
    return response;
  },
  async (error) => {
    if (error.response.status === 401) {
      await axios
        .get("http://localhost:4000/refresh-token", {
          withCredentials: true,
        })
        .catch((err) => {
          return Promise.reject(err);
        });
      console.log(error.config);
      return axios(error.config); // here error throwing while invoking the actually failed API
    } else {
      return Promise.reject(error);
    }
  }
);

export default jwtInterceptor;
```

### Axios Version

1.1.3

### Browser

Chrome

### OS

windows

**Comment by GunarajKhatri** [comment]
hey @Naveen512 do you solve it? i m getting same error

**Comment by Jaya-sys** [comment]
Hey can you assign this issue to me?

**Comment by unnimona** [comment]
getting same error on an http get request

**Comment by chlasswg26** [comment]
Getting same error on interceptors

**Comment by lukebinmore** [comment]
Also getting same error on post request for exact same scenario.

**Comment by xNarkon** [comment]
+1

**Comment by nishmez** [comment]
+1

**Comment by thivu888** [comment]
+1

**Comment by MajkyJeBuh** [comment]
+1

**Comment by Abderrahman-byte** [comment]
+1

**Comment by Abderrahman-byte** [comment]
the error is originated from lib/adapters/xhr.js line 191
https://github.com/axios/axios/blob/v1.x/lib/adapters/xhr.js#L191

**Comment by tafel** [comment]
> the error is originated from lib/adapters/xhr.js line 191 https://github.com/axios/axios/blob/v1.x/lib/adapters/xhr.js#L191

the `request.setRequestHeader(key, val);` should probably be replaced by `requestHeaders.set(key, val);` ?

**Comment by gabedejong** [comment]
I also have this problem and I also experience that the body of a PUT request is mall formed. For that it to work I need to first `JSON.parse` the body of the original request. Downgraded to 0.27.2 and it worked again without the need to parse it first. 

```
const originalRequest = error.config;

if (originalRequest.data) {
                originalRequest.data = JSON.parse(originalRequest.data); 
}
...
return serverRequest(originalRequest);
```

**Comment by gffelisberto** [comment]
Hi there, had a similar problem, seems like the headers were not picking the previous configuration. This one line solved my refresh token problem after upgrading axios: 

`
 const originalConfig = error.config; 
 originalConfig!.headers = { ...originalConfig?.headers } 
`

credit:
https://stackoverflow.com/questions/74166648/setrequestheader-fails-to-execute-with-source-code-as-a-header-value-axios-an/74308583#74308583

**Comment by vitaliyirtlach** [comment]
Hi, my solution was to replace `axios.headers` to empty values or default objects. It happens because `axios.headers` has `Symbol(defaults)` and i think thats cause error

**Comment by DigitalBrainJS** [comment]
Internally, Axios config.headers is mutated into an AxiosHeaders instance, but the request method only accepts a plain headers object.
As a temporary fix, you can convert the headers back to a plain object:
```js
await axios({
  ...config, 
  headers: config.headers.toJSON()
}); // retry the request
```

**Comment by Leehaeun0** [comment]
> Hi there, had a similar problem, seems like the headers were not picking the previous configuration. This one line solved my refresh token problem after upgrading axios to the latest version... but everything was just fine @0.27.2 :
> 
> `const originalConfig = error.config; originalConfig!.headers = { ...originalConfig!.headers } ;`
> 
> credit: https://stackoverflow.com/questions/74166648/setrequestheader-fails-to-execute-with-source-code-as-a-header-value-axios-an/74308583#74308583

you save me...! 👍

**Comment by shenxingchao** [comment]
this is my idea

```js
axiosInstance.interceptors.request.use(
  (config: any) => {
    if (config.headers) {
      try {
        if (
          Object.keys(config.headers[Object.getOwnPropertySymbols(config.headers)[0]])[0] == "0"
        ) {
          config.headers[Object.getOwnPropertySymbols(config.headers)[0]] = null
          // config.headers[Object.getOwnPropertySymbols(config.headers)[0]] = {Accept: "application/json, text/plain, */*",}
        }
      } catch (error) {}
    }
    return config
  },
  (error: any) => {
    return Promise.reject(error)
  }
)
```

**Comment by dpes8693** [comment]
> Internally, Axios config.headers is mutated into an AxiosHeaders instance, but the request method only accepts a plain headers object. As a temporary fix, you can convert the headers back to a plain object:
> 
> ```js
> await axios({
>   ...config, 
>   headers: config.headers.toJSON()
> }); // retry the request
> ```

Thank you very much!

**Comment by Chrisfufu** [comment]
> Hi there, had a similar problem, seems like the headers were not picking the previous configuration. This one line solved my refresh token problem after upgrading axios to the latest version... but everything was just fine @0.27.2 :
> 
> `const originalConfig = error.config; originalConfig!.headers = { ...originalConfig!.headers } ;`
> 
> credit: https://stackoverflow.com/questions/74166648/setrequestheader-fails-to-execute-with-source-code-as-a-header-value-axios-an/74308583#74308583

removing Exclamation mark, saved my day!

**Comment by jasonsaayman** [comment]
Thanks for your bug report, we will be closing this issue and ask that you please test and try re-create the issue with the latest version of Axios. If the bug is still present please open a issue. If possible and you are willing open a pull request with a proposed fix. Please see the motivation for doing this:

https://github.com/axios/axios/issues/6983
