### ISSUE TITLE
axios response interceptor retry request

### ISSUE THREAD

**Issue by Christopher-md** [axios/axios#5163]
### Describe the bug

I faced this problem in version 1.0+

After refreshing the token, I was returning a request with the old configurations. When I looked in the network, after updating the token, the getUserInfo method was not displayed.

It helped only after I switched to version 0.27.2

### Code snippet

```jsx
import axios from "axios";
import {getToken, logOut, refreshToken, setUser} from "@/services/auth.service";

const HTTP = axios.create({baseURL: process.env.REACT_APP_API_ENDPOINT});

HTTP.interceptors.request.use(
    config => {
        const token = getToken();

        if (token) {
            config.headers['Authorization'] = `Bearer ${token}`;
        }

        return config;
    },
    error => Promise.reject(error)
)

HTTP.interceptors.response.use(
    response => response,
    async (error) => {
        const originalRequest = error.config;

        if (error.response.status === 401 && !originalRequest._retry) {
            originalRequest._retry = true;

            try {
                const response = await refreshToken();
                const {data} = response;

                setUser(data);
            } catch (e) {
                logOut();
            }

            return HTTP(originalRequest);
        }

        return Promise.reject(error);
    }
)

export default HTTP
```

### Axios Version

1.1.3

### Browser

Chrome

### Browser Version

106

### Node.js Version

16.13.2

### OS

Windows 10

### Additional Library Versions

```bash
React 18.2.0
```

**Comment by felixmosh** [comment]
I have a similar setup with accessToken & refreshToken,

```js
function isUnAuthorizedError(error) {
  return error.config && error.response && error.response.status === 401;
}

function shouldRetry(config) {
  return config.retries.count < 3;
}

function updateAuthToken(response) {
  localStorage.setItem('token', response.data.accessToken);
}

async function authInterceptor(error) {
  error.config.retries = error.config.retries || {
    count: 0,
  };

  if (isUnAuthorizedError(error) && shouldRetry(error.config)) {
    const response = await axios.post(`/token/refresh`, {});

    updateAuthToken(response);

    error.config.retries.count += 1;
    axios.defaults.headers.common.Authorization = `Bearer ${response.data.accessToken}`; // update the accessToken
    return axios.rawRequest(error.config); // retries the original request
  }
  return Promise.reject(error);
}

axios.interceptors.response.use(null, authInterceptor);
```

After updating to v1 it propagates a `DOMexception` as resolved promise (instead of reject it)

```
"Error: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 'function(header, parser) {
    header = normalizeHeader(header);

    if (!header) return undefined;

    const key = findKey(this, header);

    if (key) {
      const value = this[key];

      if (!parser) {
        return value;
      }

      if (parser === true) {
        return parseTokens(value);
      }

      if (_utils_js__WEBPACK_IMPORTED_MODULE_0__["default"].isFunction(parser)) {
        return parser.call(this, value, key);
      }

      if (_utils_js__WEBPACK_IMPORTED_MODULE_0__["default"].isRegExp(parser)) {
        return parser.exec(value);
      }

      throw new TypeError('parser must be boolean|regexp|function');
    }
  }' is not a valid HTTP header field value.
    at setRequestHeader (webpack-internal:///../../node_modules/axios/lib/adapters/xhr.js:210:17)
    at Object.forEach (webpack-internal:///../../node_modules/axios/lib/utils.js:263:10)
    at dispatchXhrRequest (webpack-internal:///../../node_modules/axios/lib/adapters/xhr.js:209:57)
    at new Promise (<anonymous>)
    at xhrAdapter (webpack-internal:///../../node_modules/axios/lib/adapters/xhr.js:63:10)
    at Axios.dispatchRequest (webpack-internal:///../../node_modules/axios/lib/core/dispatchRequest.js:55:10)"
```

**Comment by felixmosh** [comment]
@Bobeshmo why did you closed this issue?

**Comment by Bobeshmo** [comment]
@felixmosh,  It seems to me that this issue has already been resolved #5143. Fixed in #5148. Do you think this question should be opened?

**Comment by felixmosh** [comment]
The guy made a PR, but it is still open... So it not fixed.
I think it's better to reflect the issues that comes from this, maybe, it will help to write a test for this scenario.

**Comment by Huiet** [comment]
Is there an eta on the merge/update for this 👀 . The fix seems simple in the PR, but I'm new to this rodeo https://github.com/axios/axios/pull/5148/files

**Comment by hezhongfeng** [comment]
same problem. 
Reduce version to `v0.27.2` resolved

**Comment by felixmosh** [comment]
Any progress with this?

**Comment by mhassan1** [comment]
This appears to be fixed in `axios@1.2.0` and higher.

**Comment by felixmosh** [comment]
Looks like it solved, thanx ;]

**Comment by Christopher-md** [comment]
I'm closing issues because the problem has been solved. Thanks!

**Comment by ramazansancar** [comment]
What is the current code structure and version? How was it resolved? @christian-tchaikovsky
