### ISSUE TITLE
Always request failed with status code 503 in node environment

### ISSUE THREAD

**Issue by Hexi1997** [axios/axios#5214]
### Describe the bug

It's a very strange bug, I can't use axios in node environment on my deepin system, but it works fine in windows and mac. 

{"message":"Request failed with status code 503","name":"Error","stack":"Error: Request failed with status code 503\n    at createError (/home/hexi/Learn/nodejs-axios/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/home/hexi/Learn/nodejs-axios/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/home/hexi/Learn/nodejs-axios/node_modules/axios/lib/adapters/http.js:270:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","config":{"url":"https://alpha-testnet.api.matrixmarket.xyz/mart/v2/api-docs","headers":{"Accept":"application/json, text/plain, */*","User-Agent":"Mozilla","Content-Type":"application/json","host":"alpha-testnet.api.matrixmarket.xyz"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"withCredentials":true,"responseType":"text","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"method":"get"}}

### To Reproduce

This is a minimal reproduction repository

https://github.com/Hexi1997/nodejs-axios

### Code snippet

```js
const axios = require('axios').default

axios({url:'https://alpha-testnet.api.matrixmarket.xyz/mart/v2/api-docs',responseType:'text',withCredentials:true,headers:{ "User-Agent": "Mozilla","Content-Type": "application/json"}}).then(v=>{console.log(v)}).catch((e)=>console.log(JSON.stringify(e)));
```

### Expected behavior

fetch data succeed!

### Axios Version

0.21.2

### Node.js Version

18.12.0

### OS

deepin community 20.2.2

**Comment by willywanka75** [comment]
I had this same issue and it was caused by me changing my npm config proxy for npm install. I resolved it by resetting the proxy after npm install.

**Comment by Hexi1997** [comment]
> I had this same issue and it was caused by me changing my npm config proxy for npm install. I resolved it by resetting the proxy after npm install.

I have tried as you say, still no

**Comment by Neo-Yeo** [comment]
@willywanka75's answer works for me.
more detail step:
```bash
npm config list 
```
Check whether there are configurations https-proxy, proxy
then run 
```bash 
npm delete config https-proxy proxy
```

**Comment by NizareDam** [comment]
I had the same issue, AxiosError: Request failed with status code 503
My npm command is trying to reach distant server.

**Comment by burhon97** [comment]
+

**Comment by burhon97** [comment]
I have same issue

**Comment by barwalker** [comment]
Get 503 with axios behind a proxy server, while node-fetch works fine. F* axios

**Comment by NizareDam** [comment]
I finally solved the issue, it was for sure a proxy issue.
```yaml
    - npm config set noproxy ".<your_domain>.net"
    - npm config get proxy
    - npm config set proxy ""
    - export http_proxy=""
    - export https_proxy=""
    - export HTTP_PROXY=""
    - export HTTPS_PROXY=""
    - export no_proxy=""
```

You can try setting this configuration first. I hope it will help you.

**Comment by takhello** [comment]
I have same issue

**Comment by takhello** [comment]
I have same issue，
I need an agent。

**Comment by richardsuef** [comment]
I got 503 errors when I run "nest start".

It gets solved by set the "http_proxy" env.

```
http_proxy="" nest start
```

It turns out it's because I set the "proxy" setting in local .npmrc.

**Comment by jasonsaayman** [comment]
Thanks for your bug report, we will be closing this issue and ask that you please test and try re-create the issue with the latest version of Axios. If the bug is still present please open a issue. If possible and you are willing open a pull request with a proposed fix. Please see the motivation for doing this:

https://github.com/axios/axios/issues/6983
