### ISSUE TITLE
[1.0.0+] Regression - settle helper not exported

### ISSUE THREAD

**Issue by dhensby** [axios/axios#5254]
### Describe the bug

When upgrading to v1.0.0+ our test suites fail with the following error:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/core/settle' is not defined by "exports" in .\node_modules\axios\package.json
    at new NodeError (internal/errors.js:322:7)
    at throwExportsNotFound (internal/modules/esm/resolve.js:332:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:565:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (.\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.patchedRequire [as require] (.\node_modules\diagnostic-channel\dist\src\patchRequire.js:16:46)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (.\lib\test\test-file.int.ts:13:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (.\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (.\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.patchedRequire [as require] (.\node_modules\diagnostic-channel\dist\src\patchRequire.js:16:46)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.exports.requireOrImport (.\node_modules\mocha\lib\nodejs\esm-utils.js:49:16)
    at async Object.exports.loadFilesAsync (.\node_modules\mocha\lib\nodejs\esm-utils.js:91:20)
    at async singleRun (.\node_modules\mocha\lib\cli\run-helpers.js:125:3)
    at async Object.exports.handler (.\node_modules\mocha\lib\cli\run.js:370:5)
```

The [request config docs](https://github.com/axios/axios/blob/v1.1.3/README.md#request-config) state that the following for the `adapter` prop:

>  // `adapter` allows custom handling of requests which makes testing easier.
>  // Return a promise and supply a valid response (see lib/adapters/README.md).

The [`lib/adapters/README.md`](https://github.com/axios/axios/blob/v1.1.3/lib/adapters/README.md) file indicates that the `settle` helper function should be used when authoring a custom adapter. However, when attempting to include the `settle` function (which was possible in v0) the above error is thrown because the `settle` helper is not exported.

### To Reproduce

Following the instructions in the [readme](https://github.com/axios/axios/blob/v1.1.3/lib/adapters/README.md) reproduce the  error reliably.

### Code snippet

```js
var settle = require('axios/lib/core/settle');

module.exports = function myAdapter(config) {
  // At this point:
  //  - config has been merged with defaults
  //  - request transformers have already run
  //  - request interceptors have already run
  
  // Make the request using config provided
  // Upon response settle the Promise

  return new Promise(function(resolve, reject) {
  
    var response = {
      data: responseData,
      status: request.status,
      statusText: request.statusText,
      headers: responseHeaders,
      config: config,
      request: request
    };

    settle(resolve, reject, response);

    // From here:
    //  - response transformers will run
    //  - response interceptors will run
  });
}
```

### Expected behavior

The documentation should work as expected. Or `settle` should be exported as a member of the package itself.

### Axios Version

1.0.0

### Adapter Version

n/a

### Browser

n/a

### Browser Version

n/a

### Node.js Version

all

### OS

all

**Comment by phloose** [comment]
Can confirm, this is a problem for use since we used this approach in v0 to create a fetch-based adapter for axios which is now broken. A possible fix would be to not be that strict in the exports section of axios' package.json. There it only lists specific files and no paths.

**Comment by Nabkooo** [comment]
What does it mean ? we do not have to use axios?

**Comment by customautosys** [comment]
Hi, also faced this issue today. Is there any other way to import the settle function?

**Comment by DigitalBrainJS** [comment]
Is there any other way to import the settle function?
```js
const settle = require('axios/unsafe/core/settle.js');
```

**Comment by jasonsaayman** [comment]
Thanks for your bug report, we will be closing this issue and ask that you please test and try re-create the issue with the latest version of Axios. If the bug is still present please open a issue. If possible and you are willing open a pull request with a proposed fix. Please see the motivation for doing this:

https://github.com/axios/axios/issues/6983
