### ISSUE TITLE
ECONNRESET at Function.AxiosError.from

### ISSUE THREAD

**Issue by byt3pool** [axios/axios#5267]
### Describe the bug

Hi there,

I was using axios v0.21.4 and constantly receiving ECONNRESET errors throughout the day:

```
Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
```

After updating to the latest version (v1.1.3) and some rewrites to use the AbortController instead of CancelToken and an NodeJS-Upgrade (v18) I still receive the EONNRESET error but with some more information:

```
Error: read ECONNRESET
    at Function.AxiosError.from (/home/app/appDir/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/home/app/appDir/node_modules/axios/lib/adapters/http.js:516:25)
    at RedirectableRequest.emit (node:events:525:35)
    at ClientRequest.eventHandlers.<computed> (/home/app/appDir/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Further information**

I send similar requests over and over throughout the day.
Some of the requests (axios.get) are handled correctly, some return with

```
AxiosError: timeout of 2000ms exceeded
    at RedirectableRequest.handleRequestTimeout (/home/app/appDir/node_modules/axios/lib/adapters/http.js:553:16)
    at RedirectableRequest.emit (node:events:513:28)
    at Timeout.<anonymous> (/home/app/appDir/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
```
and some lead to the ECONNRESET error above.

Is this a problem within my code or a general problem within axios?

### Axios Version

1.1.3

### Node.js Version

18

**Comment by alaczi** [comment]
@byt3pool I'm chasing down an error with same stack trace as you quoted.. Upgrade axios to 1.2 and check again I see difference in the stack (errors still happening, but now I have proper stack what is failing).

**Comment by Bharat-Kendre123** [comment]
I am Also facing this issue. I am using axios 1.2.2 version. Out of 200 request 4 to 5 requests are getting failed with this error.

Error: read ECONNRESET
    at Function.AxiosError.from (/var/task/node_modules/rest-adapter/node_modules/axios/dist/node/axios.cjs:789:14)
    at RedirectableRequest.handleRequestError (/var/task/node_modules/rest-adapter/node_modules/axios/dist/node/axios.cjs:2744:25)
    at RedirectableRequest.emit (events.js:412:35)
    at RedirectableRequest.emit (domain.js:475:12)
    at ClientRequest.eventHandlers.<computed> (/var/task/node_modules/rest-adapter/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (events.js:400:28)
    at ClientRequest.emit (domain.js:475:12)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket.emit (domain.js:475:12)
    
    
    Not sure what is the exact issue.

**Comment by vpoltoratskyi** [comment]
Hi Giys! Looks like the issue withECONNRESET is being reproduced while using axios version 1.3.5 
Looks like redirect refuses to function from time to time, 
/usr/src/app/node_modules/axios/dist/node/axios.cjs in Function.AxiosError.from at line 825:14
System

  utils.toFlatObject(error, axiosError, function filter(obj) {
    return obj !== Error.prototype;
  }, prop => {
    return prop !== 'isAxiosError';
  });
  AxiosError.call(axiosError, error.message, code, config, request, response);
  axiosError.cause = error;
  axiosError.name = error.name;
  customProps && Object.assign(axiosError, customProps);
/usr/src/app/node_modules/axios/dist/node/axios.cjs in RedirectableRequest.handleRequestError at line 2965:25
System

events.js in RedirectableRequest.emit at line 400:28
System
domain.js in RedirectableRequest.emit at line 475:12
System
/usr/src/app/node_modules/follow-redirects/index.js in ClientRequest.eventHandlers.<computed> at line 14:24
System

events.js in ClientRequest.emit at line 400:28
System
domain.js in ClientRequest.emit at line 475:12
System
/usr/src/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js in ClientRequest.req.emit at line 95:23
System

_http_client.js in TLSSocket.socketErrorListener at line 475:9
System
events.js in TLSSocket.emit at line 400:28
System
Error
read ECONNRESET

internal/stream_base_commons.js in TLSWrap.onStreamRead at line 209:20
System
internal/async_hooks.js in TLSWrap.callbackTrampoline at line 130:17

**Comment by zhgtot** [comment]
nestjs use axios：0.21.1
![image](https://github.com/axios/axios/assets/19788099/9cf45b56-5854-403e-9e33-8a387e2bea9b)
sometimes get ECONNRESET error

**Comment by Arattian** [comment]
node: "18" 
axios: "^0.27.2"

same issue 
<img width="714" alt="Screenshot 2023-08-02 at 09 09 09" src="https://github.com/axios/axios/assets/36269636/80822c63-448c-4fb6-8cc7-8973ecdd7933">

**Comment by rob-sumer** [comment]
Same issue w/ node 18 axios ^1.4.0:

{
    "name": "Error",
    "msg": "read ECONNRESET",
    "stack": "Error: read ECONNRESET\n    at AxiosError.from (/usr/src/app/node_modules/axios/dist/node/axios.cjs:836:14)\n    at RedirectableRequest.handleRequestError (/usr/src/app/node_modules/axios/dist/node/axios.cjs:3010:25)\n    at RedirectableRequest.emit (node:events:526:35)\n    at eventHandlers.<computed> (/usr/src/app/node_modules/follow-redirects/index.js:14:24)\n    at ClientRequest.emit (node:events:514:28)\n    at Socket.socketErrorListener (node:_http_client:501:9)\n    at Socket.emit (node:events:514:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"
}

**Comment by ahben0224** [comment]
Still encountering this error, Is there any solution?

**Comment by Dichotomia** [comment]
I think the default on Node JS >= 18 is keepAlive=true.
You can disable keepAlive explicitly in Axios to resolve those errors

**Comment by alaczi** [comment]
> I think the default on Node JS >= 18 is keepAlive=true. You can disable keepAlive explicitly in Axios to resolve those errors

Disabling keepAlive in a high traffic environment simply doesn't feasible. 
We had some performance testing and without keepAlive the response times 100ms higher (cost of creating new connections) and over a specific treshold the amount of ETIMEDOUT errors became really frequent.

**Comment by Dichotomia** [comment]
Reduce the keepAlive timeout then?

**Comment by OahMada** [comment]
I found this, but I'm not sure if they are related. https://forum.strapi.io/t/strapi-axios-request-on-ssr-fails-with-connect-econnrefused-but-csr-works-well/20799

**Comment by cadu088** [comment]
The same feedback was received about a high traffic API. After a week of searching and many failures I managed to identify the reason, in my case the type of communication protocol was generating packet losses, however these losses were not noticeable to the server, there was only one loss and the data arrived compromised.

To resolve this, we adopted the same protocol on the client and server, in my case TLS 1.2, forcing communication with axios, as we can see below:

```
import https from 'https';

const httpsAgent = new https.Agent({
  maxVersion: 'TLSv1.2',
  minVersion: 'TLSv1.2',
});

export const API = axios.create({
  httpsAgent,
  headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  baseURL:
  ...
});
```




By forcing all packets into a single protocol, socket drops and early closures were fixed.

I don't know if this could help your case.

**Comment by kawerewagaba** [comment]
getting the same error with axios `"axios": "^1.4.0"`

**Comment by HoMeTownSoCool** [comment]
"axios": "^1.6.2", also has this issues
<img width="1085" alt="image" src="https://github.com/axios/axios/assets/47271407/6792c2f2-6f86-41a1-9957-cbd79e157725">

**Comment by jongomes** [comment]
"axios": "^1.6.5", also has this issues

**Comment by tss0823** [comment]
close the proxy servers, it works for me

**Comment by rohit-lingayat-sd** [comment]
I am also having this issue, do we have any luck here?

**Comment by jongomes** [comment]
@rohit-lingayat-sd  use nodejs undici

**Comment by Lax77** [comment]
I happened to have same problem on my mac. It appears I had proxy running on my system causing the failure.

You could confirm is proxy is running with cmd: `env | grep -i proxy` 
If it does present, unset it.

**Comment by Quietly-20201113** [comment]
This problem will be triggered 100% when a VPN proxy is required. My solution is to set the variable isVpn to handle this problem.
```ts
// interceptors.request.use(function (config)
if(process.env.isVpn === "true" && process.env.vpn_port){
        config.proxy = {
            host: '127.0.0.1',
            port: Number(process.env.vpn_port) 
        }
    }
console.log("config.proxy = ", config.proxy);
```

**Comment by danielbarr3ra** [comment]
I've seen this issue and even when setting the config with proxy I see that the request fail with `Error: read ECONNRESET\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)',
  name: 'Error',`
  
 Not sure what else to try at this point

**Comment by Quietly-20201113** [comment]
> 需要VPN代理时，这个问题100%会触发。我的解决方案是设置变量isVpn来处理这个问题。
> 
> ```ts
> // interceptors.request.use(function (config)
> if(process.env.isVpn === "true" && process.env.vpn_port){
>         config.proxy = {
>             host: '127.0.0.1',
>             port: Number(process.env.vpn_port) 
>         }
>     }
> console.log("config.proxy = ", config.proxy);
> ```

This solution can only be used in node. It fails when I am on the client.

**Comment by rechardcheng12345** [comment]
> @rohit-lingayat-sd use nodejs undici

replaced axios with using undici definetely a better option. 

Both implementation about the similar, plus the undici having better performance and stable especially connecting with proxy

**Comment by fjeldstad** [comment]
Suggesting to replace Axios with Undici or other HTTP clients is perhaps useful for some, but it does not at all give any insight into the root cause. It gives some hope because apparently the problem _can_ be solved though 😅 

There [have been reports](https://github.com/node-fetch/node-fetch/issues/1735) of this error becoming much more frequent after Node.js 20 (or perhaps 19+) enabled keep-alive by default, but as someone mentioned disabling keep-alive is not really a feasible option for many applications.

It would be really nice to hear if there is any investigation going on to resolve this. This issue has been open for almost two years, and there are others such as https://github.com/axios/axios/issues/6206 that could be caused by the same problem.

**Comment by felipemarts** [comment]
I got this error when I try to send a request with a body of 17k bytes. I couldn't find a solution. I'm migrating to another library.

**Comment by jiangtutu0529** [comment]
"axios": "^1.7.7", also has this issues,and this problem occurs randomly

**Comment by mjmarianetti** [comment]
"axios": "1.7.9" same issue. We migrated to use native node fetch and the problem was gone

**Comment by waltershewmake** [comment]
"axios": "^1.8.1", same issue, occurring within about 3 seconds of opening a stream. Migrating to undici.

**Comment by pankajtechie-collab** [comment]
I am using axios 1.6.0 and getting same issue like above. any solution ? my node js version is 20.11.0 and next js version is 13.5.6

**Comment by jasonsaayman** [comment]
well since this error is indicating the remote has hung up it may be on the server side that the hangup occurs, has anyone got an entire full stack view of this? without the server side this is almost impossible to really diagnose. should someone have a fuller set of logs please open a new issue and @ me and i will jump onto it
