### ISSUE TITLE
Getting 400 Bad Request in v1.2.0 with same code that returned 200 with v0.27.2

### ISSUE THREAD

**Issue by jamesmortensen** [axios/axios#5311]
### Describe the bug

We are making a get request to an endpoint that works great, returning 200 OK with v0.27.2 of axios, but when we upgrade to 1.0.0 or to the latest 1.2.0, we get 400 Bad requests.

### To Reproduce

```
// run with node index.js

(async () => {
  const instance = axios.create({
    baseURL: 'https://DOMAIN_SANITIZED/api/internal/v1',
    timeout: 1000,
    headers: { 'Authorization': 'Bearer SANITIZED' }
  });


  const response = await instance.get('/request/path/sanitized?q={"merchantId":"SANITIZED 32 CHAR GUID","scheduleType":"CLASS","isDeleted":false}');


  console.log(response.data);
  console.log(response.status);
  //console.log(response.statusText);
  //console.log(response.headers);
  //console.log(response.config);

})();
```

### Expected behavior

We expect the latest version to work the same as 0.27.2.

### Axios Version

1.2.0

### Adapter Version

UNKNOWN

### Browser

N/A

### Browser Version

N/A

### Node.js Version

16.17.0

### OS

macOS 13.0.1 M1

### Additional Library Versions

```bash
No additional libs. The code snippet included is a minimal reproduceable example, which has been sanitized.
```

### Additional context/Screenshots

```bash
We are unable to include the exact payload that caused the problem since it requires authentication.  We suspect/guess that maybe it is some kind of URL encoding issue that may have been introduced in v1.0.0.
```

**Comment by karlhorky** [comment]
Also seeing new 400 error status codes on `axios@1.2.0`, where they suceeded on `axios@1.1.0`, maybe some regression?

**Comment by jsiegenthaler** [comment]
I'm seeing axios 1.2.0 fail with 401 error where exact same code on 1.1.3 produces 200 OK

**Comment by karlhorky** [comment]
@jasonsaayman any idea on this one? Any way a breaking change / regression could have slipped in to `axios@1.2.0`? I haven't had a chance to look in detail yet...

**Comment by jsiegenthaler** [comment]
@karlhorky See also #5314, I'm having issues as well, and I've seen a difference in responses between 1.2.0 and 1.1.3

**Comment by karlhorky** [comment]
Looking at the [`1.2.0` changelog](https://github.com/axios/axios/blob/HEAD/CHANGELOG.md#120---2022-11-10), wonder if this could be caused by the change to the new `AxiosHeaders` class by @DigitalBrainJS:

- #5224 

Considering that both of the 2 reproductions above have headers...

Digging in a bit to our code to check what the differences are with the request...

**Comment by karlhorky** [comment]
Ok, it seems that the response problem fixed in #5306 (and `axios@1.2.0-alpha.1`) was affecting my requests - I was using a property from the previous response without checking the type (it was `undefined`). I've built in a check now 😅

Not sure if this also affects you in the same way @jamesmortensen ...

**Comment by jasonsaayman** [comment]
Can you try with the latest version and let me know if this is still an issue

**Comment by karlhorky** [comment]
Testing `axios@1.2.1` now...

**Comment by karlhorky** [comment]
Ok, I tested [`axios@1.2.1`](https://github.com/axios/axios/releases/tag/v1.2.1) and it does not succeed, but it also does not fail in the same way!

The `taskId` I mentioned above is now coming back defined 🙌 

But now I have this one:

```
file:///home/runner/work/notion-backup/notion-backup/node_modules/axios/lib/core/AxiosError.js:89
  AxiosError.call(axiosError, error.message, code, config, request, response);
             ^
AxiosError: unexpected end of file
    at AxiosError.from (file:///home/runner/work/notion-backup/notion-backup/node_modules/axios/lib/core/AxiosError.js:89:14)
    at BrotliDecompress.handleStreamError (file:///home/runner/work/notion-backup/notion-backup/node_modules/axios/lib/adapters/http.js:489:29)
    at BrotliDecompress.emit (node:events:5[25](https://github.com/karlhorky/notion-backup/actions/runs/3657855444/jobs/6181916764#step:7:26):35)
    at BrotliDecompress.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'Z_BUF_ERROR',
  errno: -5,

...

method: 'POST',
path: '/api/v3/getTasks',

...

    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [ 'Accept', 'application/json, text/plain, */*' ],
      'content-type': [ 'Content-Type', 'application/json' ],
      cookie: [
        'Cookie',
        'token_v2=***'
      ],
      'user-agent': [ 'User-Agent', 'axios/1.2.1' ],
      'content-length': [ 'Content-Length', '442' ],
      'accept-encoding': [ 'Accept-Encoding', 'gzip, compress, deflate, br' ],
      host: [ 'Host', 'www.notion.so' ]
    },

...

  cause: Error: unexpected end of file
      at __node_internal_genericNodeError (node:internal/errors:863:15)
      at BrotliDecoder.zlibOnError [as onerror] (node:zlib:189:17) {
    errno: -5,
    code: 'Z_BUF_ERROR'
  }
```

My code is like this - I'm fetching to the Notion unofficial API using a cookie:

```ts
const client = axios.create({
  // Notion unofficial API
  baseURL: 'https://www.notion.so/api/v3',
  headers: {
    Cookie: `token_v2=${process.env.NOTION_TOKEN}`,
  },
});
```

https://github.com/upleveled/notion-backup/blob/36d1ed97f34dd426fecf1ea800f45c432235b640/index.js#L51-L57

**Comment by karlhorky** [comment]
Maybe I need to disable Brotli decompression or something?

**Comment by karlhorky** [comment]
Maybe the problem that I'm getting now has to deal with downloading the data from the stream:

```ts
const response = await client<Stream>({
  method: 'GET',
  url: block.task.status.exportURL || undefined,
  responseType: 'stream',
});
```

https://github.com/upleveled/notion-backup/blob/cb9c26537aee56e5f540a748bd08763de42a45f0/index.ts#L147-L151

**Comment by ADumaine** [comment]
I just updated to 1.2.1 from 1.1.3 and am getting the same end of file error:
```
(node:17800) UnhandledPromiseRejectionWarning: Error: unexpected end of file
    at AxiosError.from (C:\Data\ZENDev\multisigapp\node_modules\axios\dist\node\axios.cjs:785:14)
    at BrotliDecompress.handleStreamError (C:\Data\ZENDev\multisigapp\node_modules\axios\dist\node\axios.cjs:2696:29)
    at BrotliDecompress.emit (node:events:525:35)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by jsiegenthaler** [comment]
Both myself and my users have been reporting Axios errors on 1.2.1. I’ll dig up some more detail shortly. Regards JochenSent from my iPhoneOn 9 Dec 2022, at 19:57, Allan Dumaine ***@***.***> wrote:﻿
I just updated to 1.2.1 from 1.1.3 and am getting the same end of file error:
(node:17800) UnhandledPromiseRejectionWarning: Error: unexpected end of file
    at AxiosError.from (C:\Data\ZENDev\multisigapp\node_modules\axios\dist\node\axios.cjs:785:14)
    at BrotliDecompress.handleStreamError (C:\Data\ZENDev\multisigapp\node_modules\axios\dist\node\axios.cjs:2696:29)
    at BrotliDecompress.emit (node:events:525:35)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by jsiegenthaler** [comment]
I am getting the same error in v1.2.1 as well:

/usr/lib/node_modules/myProjectName/node_modules/axios/lib/core/settle.js:19
    reject(new AxiosError(
           ^
AxiosError: Request failed with status code 401
    at settle (/usr/lib/node_modules/homebridge-eosstb/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/homebridge-eosstb/node_modules/axios/lib/adapters/http.js:497:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by karlhorky** [comment]
Wondering - maybe these `AxiosError: unexpected end of file` errors that we're experiencing are fixed by https://github.com/axios/axios/pull/5353 (PR merged but not released)

cc @DigitalBrainJS

**Comment by karlhorky** [comment]
Seems like these problems are fixed in `axios@1.2.2`

**Comment by jasonsaayman** [comment]
closing as this should still be fixed in the lates version of the library, if this is not the case please open a new issue and mention me
