### ISSUE TITLE
Handle large response

### ISSUE THREAD

**Issue by Siecje** [axios/axios#5352]
### Is your feature request related to a problem? Please describe.

I am unable to get a large response and I'm getting an error.

```
Error: Cannot create a string longer than 0x1fffffe8 characters
```

This request doesn't cause `onDownloadProgress()` to run, but even if it did it sounds like you get the entire response which would have the same issue.

### Describe the solution you'd like

If the response is longer than 0x1fffffe8 characters there should be a way to get the response in chunks of 0x1fffffe8 characters.

### Describe alternatives you've considered

`responseType: 'stream'`

This requires JSONStream. https://www.npmjs.com/package/JSONStream

```JavaScript

const JSONStream = require('JSONStream');

async function sendRequest(path){
  const url = baseURL + path;
  const response = await axios({
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    method: 'GET',
    url: url,
    maxContentLength: Infinity,
    maxBodyLength: Infinity,
    onDownloadProgress: function ({loaded, total, progress, bytes, estimated, rate, download = true}) {
      console.log(loaded);
    },
    responseType: 'stream'
  });

  const stream = response.data;
  let jsonStream = JSONStream.parse();
  stream.pipe(jsonStream);

  let responseData = [];
  jsonStream.on('data', data => {
    responseData = data;
  });

  const myPromise = new Promise((resolve, reject) => {
    jsonStream.on('close', data => {
      resolve(responseData);
    });
    jsonStream.on('error', err => {
      reject(err);
    });
  });

  return myPromise;
}
```

**Comment by jasonsaayman** [comment]
this is hitting the node string limit, you may do some research and i think ther may be a way to force node to allow bigger strings

**Comment by dallenbaldwin** [comment]
I'm also running into this. We're currently trying to downloading a large pdf file (855MB) from an external location to later zip with other pdfs. I've done some research and from what I can see, Node _does not_ allow you to allow larger strings since it's tied to V8.

Any suggestions?

**Comment by DigitalBrainJS** [comment]
> Any suggestions?

https://nodejs.org/api/stream.html#streampipelinesource-transforms-destination-options
https://nodejs.org/api/fs.html#filehandlecreatewritestreamoptions

**Comment by dallenbaldwin** [comment]
> > Any suggestions?
> 
> https://nodejs.org/api/stream.html#streampipelinesource-transforms-destination-options https://nodejs.org/api/fs.html#filehandlecreatewritestreamoptions

based on your links, I think you might have misunderstood what was I asking. I am facing this issue in _axios_ when trying to download the file using a GET request. 

More frustrating than anything else, it appears no number of try/catch blocks can actually catch the error. It always crashes my app.

```txt
{
  "uncaughtExceptionMonitor": {
    "name": "Error",
    "message": "Cannot create a string longer than 0x1fffffe8 characters",
    "stack": [
      "Error: Cannot create a string longer than 0x1fffffe8 characters",
      "at Buffer.toString (node:buffer:858:17)",
      "at IncomingMessage.handleStreamEnd (/home/{{repo}}/node_modules/axios/lib/adapters/http.js:286:41)",
      "at IncomingMessage.emit (node:events:530:35)",
      "at endReadableNT (node:internal/streams/readable:1698:12)",
      "at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"
    ],
    "_stack": "Error: Cannot create a string longer than 0x1fffffe8 characters\n    at Buffer.toString (node:buffer:858:17)\n    at IncomingMessage.handleStreamEnd (/home/dallenbaldwin/Dev/cims-reporting-app/node_modules/axios/lib/adapters/http.js:286:41)\n    at IncomingMessage.emit (node:events:530:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"
  }
}
```

**Comment by DigitalBrainJS** [comment]
> trying to downloading a large pdf file (855MB)
> I am facing this issue in axios when trying to download the file using a GET request.

@dallenbaldwin What if you needed to download a 100GB file?
As we know, large amounts of IO data should only be handled in streams, especially on a server with concurrent requests. You can't load everything into RAM, even if it fits within the line length limit.

 Set up Axios to return a stream, and just pipe it to a file.

```js
async function downloadFile(url, outputPath) {
  const response = await axios({
    method: 'get',
    url,
    responseType: 'stream',
  });

  await pipeline(
    response.data,            // Readable (Axios stream)
    fs.createWriteStream(outputPath) // Writable (file)
  );
}
```
