### ISSUE TITLE
TypeError [ERR_INVALID_URL]: Invalid URL

### ISSUE THREAD

**Issue by zWingz** [axios/axios#5458]
### Describe the bug

```js
const axios = require('axios');
axios.get('/user/12345').then((response) => {
  console.log(response.data);
  console.log(response.status);
  console.log(response.statusText);
  console.log(response.headers);
  console.log(response.config);
});

```
throw error
<img width="441" alt="image" src="https://user-images.githubusercontent.com/13031838/211476237-a4a0b39c-2d82-4ae0-b04e-de79532f5d1f.png"> 
by the [code](https://github.com/axios/axios/blob/v1.x/lib/adapters/http.js#L181)

### Axios Version

1.2.1

### Adapter Version

http

### Node.js Version

v16

**Comment by huineng** [comment]
i had this with a test
``` 
 FAIL  src/server/config/tests/axios.spec.ts (10.587 s)
  config -> axios -> handleAxiosError
    ✓ handleAxiosError: should reject (4 ms)
    ✕ handleAxiosError: should reject (10002 ms)

  ● config -> axios -> handleAxiosError › handleAxiosError: should reject

    TypeError: Invalid URL

      3 |
      4 | export const sendAxiosRequest = async (config: RawAxiosRequestConfig): Promise<AxiosResponse> =>
    > 5 |     axios.request(config).catch(handleAxiosError);
        |           ^
      6 |

      at dispatchHttpRequest (node_modules/axios/lib/adapters/http.js:186:20)
      at http (node_modules/axios/lib/adapters/http.js:122:10)
      at Axios.dispatchRequest (node_modules/axios/lib/core/dispatchRequest.js:51:10)
      at Axios.request (node_modules/axios/lib/core/Axios.js:142:33)
      at Function.wrap [as request] (node_modules/axios/lib/helpers/bind.js:5:15)
      at sendAxiosRequest (src/server/config/axios/send_axios_request.ts:5:11)
      at Object.<anonymous> (src/server/config/tests/axios.spec.ts:22:38)

  ● config -> axios -> handleAxiosError › handleAxiosError: should reject

    thrown: "Exceeded timeout of 10000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      19 |     });
      20 |
    > 21 |     test('handleAxiosError: should reject', async () => {
         |     ^
      22 |         await expect(sendAxiosRequest({ url: undefined })).rejects.toBeDefined();
      23 |     });
      24 | });

      at src/server/config/tests/axios.spec.ts:21:5
      at Object.<anonymous> (src/server/config/tests/axios.spec.ts:16:1)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        10.656 s
```

i reverted back to 1.3.0

**Comment by DigitalBrainJS** [comment]
You missed the base URL configuration when trying to use a relative URL on the server side.

**Comment by zhanglolo** [comment]
When i use axios and msw in node env, have the same issues, you can visit this discussions.
https://github.com/mswjs/msw/discussions/1521

**Comment by jghaanstra** [comment]
Just experienced the same thing. Happens on other invalid URL's as well, not related to the use of relative URL's. For instance http://192.168.0.285.

```
const axios = require('axios');
axios.get('http://192.168.0.285').then((response) => {
  console.log(response.data);
  console.log(response.status);
  console.log(response.statusText);
  console.log(response.headers);
  console.log(response.config);
});
```

**Comment by DigitalBrainJS** [comment]
@jghaanstra  `192.168.0.285` is an invalid IP address, so everything is correct

**Comment by jghaanstra** [comment]
> @jghaanstra 192.168.0.**285** is an invalid IP address, so everything is correct

I can not catch the error but the code crashes with the following stacktrace. On 1.3.0 the error is caught but not on 1.3.3.

```
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:372:5)
    at URL.onParseError (node:internal/url:553:9)
    at new URL (node:internal/url:629:5)
    at dispatchHttpRequest (D:\Solide Webservices\Github\test\node_modules\axios\dist\node\axios.cjs:2584:20)
    at new Promise (<anonymous>)
    at http (D:\Solide Webservices\Github\test\node_modules\axios\dist\node\axios.cjs:2520:10)
    at Axios.dispatchRequest (D:\Solide Webservices\Github\test\node_modules\axios\dist\node\axios.cjs:3481:10)
    at Axios.request (D:\Solide Webservices\Github\test\node_modules\axios\dist\node\axios.cjs:3831:33)
    at Axios.<computed> [as get] (D:\Solide Webservices\Github\test\node_modules\axios\dist\node\axios.cjs:3857:17)
    at Function.wrap [as get] (D:\Solide Webservices\Github\test\node_modules\axios\dist\node\axios.cjs:29:15) {
  input: 'http://192.168.0.285',
  code: 'ERR_INVALID_URL'
}
```

**Comment by DigitalBrainJS** [comment]
@jghaanstra I see. Your issue is unrelated to this ticket, but the regression bug has been confirmed. Thanks for the report! We'll fix this in the next release.

**Comment by iamgabrielsoft** [comment]
this still happens in version 1.6.5

**Comment by ipapast** [comment]
> this still happens in version 1.6.5

hey, what issue do you refer to? Is it the uncaught error? 
I think I still see it on 1.6.7 too.

**Comment by wpsecurityop** [comment]
Secure your WordPress website today.
 Protect your site from hackers, malware and downtime with our WordPress security optimization service.
 24/7 protection
 Malware removal
 Speed and performance boost
 Call: +8801718359634 | Website: https://sarbd.com/wordpress-security-optimization/

**Comment by wpsecurityop** [comment]
Secure your WordPress website today.
 Protect your site from hackers, malware and downtime with our WordPress security optimization service.
 24/7 protection
 Malware removal
 Speed and performance boost
 Call: +8801718359634 | Website: https://sarbd.com/wordpress-security-optimization/
