### ISSUE TITLE
Not very appropriate error tip when set "adapter: 'http'" in browser env.

### ISSUE THREAD

**Issue by oneyoung19** [axios/axios#5563]
### Describe the bug

Hey. As stated in the title, when i set "adapter: 'http'" in the request config options with chrome  browser, the console tells me: `Error: Adapter 'http' is not available in the build`.
But in the source code, the correct tip should be `Error: Adapter 'http' is not supported by the environment`.
The reason for this problem is that, `httpAdapter`'s value is `null` instead of `false` in browser environment.
The `browser` field in the package.json has extra configuration.

### To Reproduce

You can try it in [codepen](https://codepen.io/code1994/pen/dyqvaVx?editors=1111)

### Code snippet

```js
// the test code
axios('/api', {
    adapter: 'http'
})

// package.json in axios
{
  "browser": {
    "./lib/adapters/http.js": "./lib/helpers/null.js"
  }
}
```

### Expected behavior

when set `adapter: 'http'` in the request config options, the console should be `Error: Adapter 'http' is not supported by the environment`.

### Axios Version

1.2.1

### Additional context/Screenshots

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/37331643/222430239-3d684d1b-3da3-4ab1-8f8a-b723bf19faaf.png">

**Comment by suityou01** [comment]
```for (let i = 0; i < length; i++) {
      nameOrAdapter = adapters[i];
      if((adapter = utils.isString(nameOrAdapter) ? knownAdapters[nameOrAdapter.toLowerCase()] : nameOrAdapter)) {
        break;
      }
    }
```
It's hard to see when adapter will ever be false from this code. The ternary statement will return either a knownAdapter or the value of nameOrAdapter. It will only return false if nameOrAdapter is false.

In your case your adapter is set to null, and not false. 

How should it work if you deliberately set the adapter to null?

**Comment by oneyoung19** [comment]
@suityou01 
Judging from the logic of the source code, it should indeed be `false`. 
But when added `browser` field in `package.json`, the field causes logic to become `null`.

**Comment by suityou01** [comment]
It will become null if you set it to null, yes.
You are setting it to null.
If you want it to be false, try setting it to false. 

```
// package.json
{
  "browser": {
    "./lib/adapters/http.js": false
  }
}
```
[package-browser-field-spec-ignore-a-module](https://github.com/defunctzombie/package-browser-field-spec#ignore-a-module)

**Comment by oneyoung19** [comment]
@suityou01 
https://github.com/axios/axios/blob/v1.x/package.json
The source code is set to null, not intentionally set by me during the test.

**Comment by suityou01** [comment]
You are setting the adapter in the request options. As a consumer of the library you would have your own package.json.
You say that "when i set "adapter: 'http'" in the request config options..." while looks to me like you are setting it to a string.
This being the case it will attempt to load the adapter from the list of known adapters, in this case http.

So are you saying, in which case that when you issue a request such as 

```
axios.get('url', { adapter: 'http' });
```

You are getting the error as you describe? Is this how to reproduce your error?

**Comment by suityou01** [comment]
```
axios.get('https://jsonplaceholder.typicode.com/todos/1', {
  adapter: 'http'
})
.then((value)=>console.log(value));
```

This code produces this error for me

```
adapters.js:45 Uncaught (in promise) Error: Adapter 'http' is not available in the build
    at Object.getAdapter (adapters.js:45:1)
    at Axios.dispatchRequest (dispatchRequest.js:49:1)
    at Axios.request (Axios.js:142:1)
    at Axios.<computed> [as get] (Axios.js:168:1)
    at Function.wrap [as get] (bind.js:5:1)
    at onclick (axiosGetTest.js:4:1)
```

Is this your use case?

**Comment by oneyoung19** [comment]
@suityou01 
Thank you very much!
Yes, it is.
I updated my description of this issue.

**Comment by suityou01** [comment]
I wonder if this is because you are using Edge?
[duplicate?](https://github.com/axios/axios/issues/5523)

In any case, what happens if you remove the config and just go with

```
axios.get('https://jsonplaceholder.typicode.com/todos/1')
  .then((value)=>console.log(value));
```

Does this work?

**Comment by suityou01** [comment]
Ok here's what I have found.

The httpAdapter is imported at the top of the module.
This is a conditional export from the http.js module in the same directory

```
export default isHttpAdapterSupported && function httpAdapter(config) {
...
````
The boolean isHttpAdapterSupported is defined as

```
const isHttpAdapterSupported = typeof process !== 'undefined' && utils.kindOf(process) === 'process';
```
Which looks to me like it is trying to identify if this is running in Node rather than in a Browser.

Presumably you can add an http adapter to a Node project and use this in lieu of the one you would have used if you were in the browser.

I think the variable name is misleading and should be changed to something like "isBrowserEnv" or something and the logic inverted accordingly.

So if the http adapter is not loaded in the knownAdaptors and you specify to use it with your configuration, then it will return null.

The question is, as you say whether the error message is misleading. I would say possibly. In this case the adapter is not available in the build or the environment. 

The use case I think is invalid, because you seem to be doing this from within a Browser (Edge) so you shouldn't need to specify an adapter as you already have an http module loaded as part of the V8 engine.

If you wanted to specifiy an adaptor you could do so in your config by specifying a function that returns a Promise. See [here](https://github.com/axios/axios/issues/5523)

**Comment by do-kevin** [comment]
> ```
> axios.get('https://jsonplaceholder.typicode.com/todos/1', {
>   adapter: 'http'
> })
> .then((value)=>console.log(value));
> ```
> 
> This code produces this error for me
> 
> ```
> adapters.js:45 Uncaught (in promise) Error: Adapter 'http' is not available in the build
>     at Object.getAdapter (adapters.js:45:1)
>     at Axios.dispatchRequest (dispatchRequest.js:49:1)
>     at Axios.request (Axios.js:142:1)
>     at Axios.<computed> [as get] (Axios.js:168:1)
>     at Function.wrap [as get] (bind.js:5:1)
>     at onclick (axiosGetTest.js:4:1)
> ```
> 
> Is this your use case?

I get the same error. I'm developing for an Electron app. I had to downgrade to `axios 0.27.2` and do something like this:

```js
axios.get(this.apiURL + path, {
  adapter: require("axios/lib/adapters/http"),
});
```

**Comment by codingwesley** [comment]
I use npm package `TypeChat` in Deno,  and has the same issue

**Comment by MiniSuperDev** [comment]
I have the same error in my electron app, I want to force to use the http adapter to use proxy

**Comment by osttra-j-joyce** [comment]
I found this useful Medium article: https://allegra9.medium.com/nock-jest-with-latest-axios-33c3f0e9016b

You need 3 things;
1. global.XMLHttpRequest = undefined  -> In test setup
2. axios.defaults.adapter = 'http';    -> In test setup
3. "^axios$": require.resolve("axios"),      -> In jest.config.js

**Comment by jasonsaayman** [comment]
will probably try address the issues in the next version but for now please attempt to do what @osttra-j-joyce has suggested

**Comment by DigitalBrainJS** [comment]
>  when i set "adapter: 'http'" in the request config options with chrome browser, the console tells me: Error: Adapter 'http' is not available in the build.

That's how it should be. The http adapter code is physically removed from the browser bundle as it relies on node API & modules that don't exist in the browser, otherwise, this will lead to a build error, or will force the user to import node shims, which will add a lot of useless garbage to the bundle. Using the bundle settings, you can also remove any adapter from the build, for example, leaving only fetch and removing xhr. So the error message is quite relevant.

`undefined` -> unknown adapter
`null` -> known adapter, but the adapter was removed from the build with bundler (its module replaced with `null` - module)
`false` -> adapter is in the build, but is not supported (lack of required API in the environment, xhr and fetch can return this state).
