### ISSUE TITLE
Unclear error message is thrown when specifying an empty proxy authorization

### ISSUE THREAD

**Issue by hung-cybo** [axios/axios#5614]
### Describe the bug

Currently, if we specify an empty proxy authorization, e.g. `proxy.auth = {username: "", password: ""}`, an unclear error message is thrown.

```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
    at new NodeError (node:internal/errors:399:5)
    at Function.from (node:buffer:334:9)
    at setProxy (file:///axios-with-empty-authn/node_modules/axios/lib/adapters/http.js:93:10)
    at dispatchHttpRequest (file:///axios-with-empty-authn/node_modules/axios/lib/adapters/http.js:390:7)
    at file:///axios-with-empty-authn/node_modules/axios/lib/adapters/http.js:142:5
    at new Promise (<anonymous>)
    at wrapAsync (file:///axios-with-empty-authn/node_modules/axios/lib/adapters/http.js:122:10)
    at http (file:///axios-with-empty-authn/node_modules/axios/lib/adapters/http.js:148:10)
    at Axios.dispatchRequest (file:///axios-with-empty-authn/node_modules/axios/lib/core/dispatchRequest.js:51:10)
    at Axios.request (file:///axios-with-empty-authn/node_modules/axios/lib/core/Axios.js:142:33) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Seem this error happened from this PR: [#4436](https://github.com/axios/axios/pull/4436/files#diff-586c04c24608b86a074073c5514cc195be5c4c87ddb56da233f6d998ada4159fR43-R45)

https://github.com/axios/axios/blob/2e70cecda42993e1153248f0f96715c3c55f7f39/lib/adapters/http.js#L87-L96

The cause of the error is `proxy.auth` is still an object, not a string. Therefore, `Buffer.from` throws the error because It does not accept an object.

### To Reproduce

Run the code snippet

### Code snippet

```js
// index.mjs
import axios from "axios";

const proxy = {
  protocol: "http:",
  host: "hostname.abc.xyz",
  port: 3300,
  auth: {
    username: "",
    password: "",
  }
};

await axios.get("https://test-domain.abc", {proxy});
```

### Expected behavior

I'm not sure whether this is expected behavior or not. So, I suggest two options below

### Expected behavior 01

Show a clear message about empty proxy authorization.

For example: `Invalid proxy authorization`

### Expected behavior 02

Ignore the empty proxy authorization and skip the basic proxy authorization.

### Axios Version

1.3.4

### Node.js Version

18.14.2

**Comment by Poyoman39** [comment]
This also happens with a well set auth object. The documentation tell us to use an object.

- I think mutating proxy.auth is a bad practice and should really be avoided
- This seems not to work in my case (Object freezed ?)

=> 
```
      if (proxy.auth.username || proxy.auth.password) {
        proxy.auth = (proxy.auth.username || '') + ':' + (proxy.auth.password || '');
        console.log('it is', proxy.auth); // { username: 'some', password: 'value' }
        console.log('should', (proxy.auth.username || '') + ':' + (proxy.auth.password || '')); // 'some:value'
      }
      console.log({ proxy }); // { auth: { username: 'some', password: 'value' } }
```

**Comment by hung-cybo** [comment]
@Poyoman39 

> I think mutating proxy.auth is a bad practice and should really be avoided
I totally agree with you. We should avoid mutating the data to a different type than the original.

> Anyway the mutation seems not to work in my case (Object freezer ?)
Sorry, I'm not sure about yours. But, in my case, I have to verify before calling Axios(remove `auth` property), and It works now.

**Comment by jasonsaayman** [comment]
Closing as this was fixed by merged PR #6314
