### ISSUE TITLE
Receiving ERR_NETWORK suddenly on axios.get request

### ISSUE THREAD

**Issue by eblohm** [axios/axios#5644]
### Describe the issue

Roughly a month ago I started receiving an `ERR_NETWORK` response from my `axios.get` (and `axios.post`) requests. I have no idea what is causing this because nothing on the server it's requesting (I have access to the API server as well) has changed and nothing in my request has changed either. I'm using Vue 3 in Electron.

I can make the request with the same URL and headers in PostMan and receive the correct response. When I build my app for production, the request works completely fine, but when it's in development mode, I receive these errors on any of the API calls and I have no idea what's going on.

I receive the following errors in my console after the request fails - 

`Access to XMLHttpRequest at 'DOMAIN' from origin 'http://localhost:8080' has been blocked by CORS policy: Request header field accesstoken is not allowed by Access-Control-Allow-Headers in preflight response.`

`GET DOMAIN net::ERR_FAILED`

`{
    "message": "Network Error",
    "name": "AxiosError",
    "stack": "AxiosError: Network Error\n    at XMLHttpRequest.handleError (http://localhost:8080/js/chunk-vendors.js:24846:14)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "AccessToken": "REMOVED"
        },
        "method": "get",
        "url": "REMOVED"
    },
    "code": "ERR_NETWORK",
    "status": null
}`

### Example Code

```js
const headers = {
      'AccessToken': user.msAccessToken,
      'Content-Type': 'application/json',
    }
    genericStore.busy = true;
    endPoints.forEach(async endpoint => {
      const apiUrl = API_URL_PREFIX + endpoint.url;
      try {
        const res = await axios.get(apiUrl, { headers });
        writeFileSync(`${path.join(genericStore.dataPath, 'extraResources', `${endpoint.name}s.json`)}`, JSON.stringify(res.data), 'utf8');
      } catch (e) {
        genericStore.busy = false;
        if(showMessages) {
          genericStore.errorMsgs.push(e);
          genericStore.alert = {
            active: true,
            type: 'error',
            msg: `There was an error contacting the server for the ${endpoint.name} list, please try again.`
          }
        }
        console.error(e);
        return;
      }
    });
```

### Expected behavior

`res.data` should be a JSON object with the expected data

### Axios Version

1.3.5

### Additional Library Versions

```bash
Vue 3.2.47
Electron 23.1.4
```

### Additional context/Screenshots

```bash
Again, I have not changed anything in relation to the request, and the server has had any changes to it's CORS policy. It just randomly stopped working one day in development mode. If the request is made in the production version of the app or via Postman, the request works and returns the expected data.
```

**Comment by akin-tekeoglu** [comment]
Can you make an `OPTIONS` request to the server via Postman?

```
OPTIONS /api/endpoint
Access-Control-Request-Method: GET
Access-Control-Request-Headers: origin, accesstoken
Origin: http://localhost:8080
```

**Comment by Phong-TH** [comment]
The same problem is on react native, it happens on the user side only and can't be replicated.

**Comment by pruthvi-itribe** [comment]
Similar problem we are facing too, and its happening only 2-3% of the time

**Comment by sacummings91** [comment]
This happens to us all the time to. It adds a lot of noise to our Sentry alerts and as far as we can tell theres nothing actionable to do about it. We are unable to reproduce this issue locally or in our own hosted environments. 

```
{
  "message": "Network Error",
  "name": "AxiosError",
  "stack": "AxiosError: Network Error\n    at l.onerror (https://my.ternary.app/vendor.6b1138ab.js:2:4431763)\n    at XMLHttpRequest.r (https://my.ternary.app/vendor.6b1138ab.js:2:1678469)",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "adapter": [
      "xhr",
      "http"
    ],
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {},
    "headers": {
      "Accept": "application/json, text/plain, */*"
    },
    "baseURL": "https://core-api.ternary.app/api",
    "withCredentials": true,
    "url": "/recommendations?tenantID=Qd87WUacgbvy5DbPOOAq&kind=recommendation",
    "method": "get"
  },
  "code": "ERR_NETWORK",
  "status": null
}

**Comment by DigitalBrainJS** [comment]
> as far as we can tell theres nothing actionable to do about it. We are unable to reproduce this issue locally or in our own hosted environments.

@sacummings91 definitely because if we rule out a CORS issue then it is a low-level client connection error or the request is blocked by the browser or its plugins including adblockers

**Comment by robinp** [comment]
Based on the small research, this seems a genuine network error reported by the browser (aka wifi had a blip, or docker containers do their interrupt-all-network-connections-on-the-host dance). See https://github.com/axios/axios/blob/b3be36585884ba1e237fdd0eacf55f678aefc396/lib/adapters/xhr.js#L162 .

So, this should happen under normal circumstances in the real world. Retry it, or ignore, or such..

**Comment by apostolides** [comment]
Hello, today we suddenly experienced the same issue. Example stack trace below:
```json
{
   "message":"Network Error",
   "name":"AxiosError",
   "stack":"AxiosError: Network Error\n    at handleError (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.reductedapp&modulesOnly=false&runModule=true:176766:39)\n    at call (native)\n    at dispatchEvent (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.reductedapp&modulesOnly=false&runModule=true:37128:31)\n    at setReadyState (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.reductedapp&modulesOnly=false&runModule=true:35868:33)\n    at __didCompleteResponse (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.reductedapp&modulesOnly=false&runModule=true:35654:29)\n    at apply (native)\n    at anonymous (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.reductedapp&modulesOnly=false&runModule=true:35796:52)\n    at apply (native)\n    at emit (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.reductedapp&modulesOnly=false&runModule=true:2455:40)\n    at apply (native)\n    at __callFunction (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.reductedapp&modulesOnly=false&runModule=true:3322:36)\n    at anonymous (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.reductedapp&modulesOnly=false&runModule=true:3042:31)\n    at __guard (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.reductedapp&modulesOnly=false&runModule=true:3259:15)\n    at callFunctionReturnFlushedQueue (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.reductedapp&modulesOnly=false&runModule=true:3041:21)",
   "config":{
      "transitional":{
         "silentJSONParsing":true,
         "forcedJSONParsing":true,
         "clarifyTimeoutError":false
      },
      "adapter":"xhr",
      "transformRequest":[
         null
      ],
      "transformResponse":[
         null
      ],
      "timeout":0,
      "xsrfCookieName":"XSRF-TOKEN",
      "xsrfHeaderName":"X-XSRF-TOKEN",
      "maxContentLength":-1,
      "maxBodyLength":-1,
      "env":{
         
      },
      "headers":{
         "Accept":"application/json, text/plain, */*",
         "Authorization":"REDUCTED"
      },
      "method":"get",
      "url":"https://REDUCTED/resource"
   },
   "code":"ERR_NETWORK",
   "status":null
}
```
Requests from postman returned the expected results, server configuration is the same as always (used to work until today). We have been debugging our backend stack like hell and cannot reproduce the issue. It only happens from our react-native application. Out of ideas besides the classic "have you tried turning it off and on again"?

**Comment by shaansuraj** [comment]
import axios from 'axios';
import useAuthToken from '../hooks/token-manager/useAuthToken';


const api = axios.create({
    baseURL: 'correct url",
    timeout: 10000,
    headers: {
        'content-type': 'application/json',
        'accept': 'application/json',
    },
    
    
});


api.interceptors.request.use(request => {
    console.log('Starting Request', request);
    return request;
  });
  
  api.interceptors.response.use(response => {
    console.log('Response:', response);
    return response;
  }, error => {
    console.error('Error:', error);
    return Promise.reject(error);
  });

  if (Platform.OS === 'android') {
    api.defaults.httpsAgent = {
        rejectUnauthorized: false, // Allow self-signed certificates
    };
}

const apiEndpoints = {
    login: async ({ registrationNumber, password, androidId }) => {
        try {
            // const androidId = useGetAndroidID();
            const response = await api.post('/student-login', { registrationNumber, password, androidId });
            return response;
        } catch (error) {
            throw error;
        }
    },
    logout: async () => {
        try {
            const authToken = await useAuthToken().getToken();

            api.defaults.headers.common['Authorization'] = `Bearer ${authToken}`;
            const response = await api.post('/student-logout');
            return response;
        } catch (error) {
            throw error;
        }
    },
    register: async ({ name, registrationNumber, email, password, batch, branch, section, course, androidId }) => {
        try {
            // const androidId = useGetAndroidID();
            const response = await api.post('/student-register', {
                name, registrationNumber, email, password, batch, branch, section, course, androidId
            });
            return response;
        } catch (error) {
            throw error;
        }
    },
    getProfile: async () => {
        try {
            const authToken = await useAuthToken().getToken();

            api.defaults.headers.common['Authorization'] = `Bearer ${authToken}`;
            const response = await api.get('/student-profile');
            return response.data;
        } catch (error) {
            throw error;
        } finally {
            delete api.defaults.headers.common['Authorization'];
        }
    },

    joinQuiz: async ({ quizId, password }) => {
        try {
            const authToken = await useAuthToken().getToken();

            api.defaults.headers.common['Authorization'] = `Bearer ${authToken}`;
            const response = await api.post('/join-quiz', { quizId, password });
            return response;
        } catch (error) {
            throw error;
        }
    },
    getMyResults: async () => {
        try {
            const authToken = await useAuthToken().getToken();

            api.defaults.headers.common['Authorization'] = `Bearer ${authToken}`;
            const response = await api.get('/my-results');
            return response;
        } catch (error) {
            throw error;
        }
    },

    scoreCounter: async ({ registrationNumber, quizId, responses }) => {
        try {
            // console.log('registrationNumber: ', registrationNumber)
            // console.log('quizId: ', quizId)
            // console.log('responses api side : ', responses)
            const authToken = await useAuthToken().getToken();
            api.defaults.headers.common['Authorization'] = `Bearer ${authToken}`;
            const response = await api.post('/score-counter', { registrationNumber, quizId, responses });
            return response;
        } catch (error) {
            throw error;
        }
    }

};

export default apiEndpoints;
Why am I getting network error? it is working fine in postman and browser.

**Comment by n-ochs** [comment]
has anyone found a solution for this? we are randomly getting "Network error" on maybe ~5% of requests to our server. we are using Axios v1.6.2. usually after this happens (the network error), any subsequent requests give the same "Network error" until the user fully reloads the page.

@sacummings91 - what version of axios are you on and are you still experiencing this? we cannot reproduce this in any of our lower environments either. only happens to some users in production.

**Comment by milad-fa** [comment]
I have this problem, someone help me please

**Comment by milad-fa** [comment]
> I have this problem, someone help me please
> 
> xhr.js:258
> 
> ```
>        POST https://192.168.107.240:1020/order/create 400 (Bad Request)
> dispatchXhrRequest @ xhr.js:258
> xhr @ xhr.js:49
> dispatchRequest @ dispatchRequest.js:51
> _request @ Axios.js:170
> request @ Axios.js:40
> httpMethod @ Axios.js:209
> wrap @ bind.js:5
> post @ ApiService.js:17
> sendOrderServer @ MenuView.vue:336
> eval @ runtime-dom.esm-bundler.js:699
> callWithErrorHandling @ runtime-core.esm-bundler.js:193
> callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:201
> callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:211
> invoker @ runtime-dom.esm-bundler.js:681
> ApiService.js:20 {"message":"Request failed with status code 400","name":"AxiosError","stack":"AxiosError: Request failed with status code 400\n    at settle (webpack-internal:///./node_modules/axios/lib/core/settle.js:24:12)\n    at XMLHttpRequest.onloadend (webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:111:66)\n    at Axios.request (webpack-internal:///./node_modules/axios/lib/core/Axios.js:54:41)\n    at async ApiService.post (webpack-internal:///./src/services/ApiService.js:18:24)","
> ```
> 
> `{"message":"Network Error","name":"AxiosError","stack":"AxiosError: Network Error\n at XMLHttpRequest.handleError (webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:160:14)\n at Axios.request (webpack-internal:///./node_modules/axios/lib/core/Axios.js:54:41)\n `
> 
> The links are exactly the same. But for the errors, it gives a network error while the network is connected.

My problem has been solved, my dears. The problem was the server that did not approve the cross because I had used a personal error

**Comment by luizomg** [comment]
> We had the same issue that `"AxiosError: Network Error"` occasionally happens less than 1% of entire requests with our app based on Vue3, and the problem seems solved by adding retrying requests.
> 
> Same as @robinp mentioned, we got errors here.
> 
> https://github.com/axios/axios/blob/b3be36585884ba1e237fdd0eacf55f678aefc396/lib/adapters/xhr.js#L158-L162
> 
> The situation for us was we removed Nuxt.js from our app and migrated to a pure Vue3 app recently, then the errors came to happen occasionally since we released our Vue3 app. Although Nuxt has `nuxt/axios` that bundles `axios-retry`, We forgot to install `axios-retry` to our Vue3 app and the error sometimes became to happen. Thus, we installed it, and the errors have stopped so far. Thanks.

Here we are with the same problem, happening in a very small percentage of requests, in our react native mobile application. In our case, we have always used axios-retry. Some affected users report that it only happens on a specific connection. However, we were unable to advance the investigations.
Anyone with a similar situation that managed to resolve it?

**Comment by LuongTruong** [comment]
Hello guys, I am also having this issue after upgrading the axios from v1.6.2 to v1.7.2. The issue can't be reproduced and it happens randomly.

**Comment by mattstrayer** [comment]
For us this seems to be isolated to Firefox users. Can only reproduce _sometimes_ with one endpoint. 

Some requests will work, others fail without a clear reason.

**Comment by meetfaisalmirza** [comment]
i am stucked with this from last three days .. it blocks all my request to an api end point to back end server which is placed n different server ..

**Comment by TimotiusAnrez** [comment]
is there any update on this? my expo application also got [AxiosError: Network Error] from all POST request

**Comment by dentep** [comment]
having the same issue

**Comment by SSzzPP** [comment]
is there any update on this? having the same issue.

**Comment by n-ochs** [comment]
In my case, this ended up being an issue from the client's computer. The business that was accessing our website had a cyber rule to block certain network requests we were making.

**Comment by vinamrahalgar** [comment]
facing the same issue for PUT request. Any solution?

message:Network Error
name:AxiosError
description:undefined
number:undefined
fileName:undefined
lineNumber:undefined
columnNumber:undefined
stack:AxiosError: Network Error at handleError (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:162686:39) at call (native) at dispatchEvent (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:39761:31) at setReadyState (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:38964:33) at __didCompleteResponse (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:38750:29) at apply (native) at anonymous (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:38892:52) at apply (native) at emit (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:3317:40) at apply (native) at anonymous (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:3117:200) at emit (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:3150:62) at apply (native) at __callFunction (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:2207:38) at anonymous (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:1923:31) at __guard (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:2140:15) at callFunctionReturnFlushedQueue (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:1922:21) at ?anon_0_ (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:161016:64) at throw (native) at asyncGeneratorStep (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:31333:19) at _throw (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:31350:29) at tryCallOne (address at InternalBytecode.js:1:1180) at anonymous (address at InternalBytecode.js:1:1874) at apply (native) at anonymous (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:38081:26) at _callTimer (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:37960:17) at _callReactNativeMicrotasksPass (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:38005:17) at callReactNativeMicrotasks (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:38211:44) at __callReactNativeMicrotasks (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:2168:48) at anonymous (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:1941:45) at __guard (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:2140:15) at flushedQueue (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:1940:21) at callFunctionReturnFlushedQueue (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:1925:33)
timeout:0
xsrfCookieName:XSRF-TOKEN
xsrfHeaderName:X-XSRF-TOKEN
maxContentLength:-1
maxBodyLength:-1
validateStatus: validateStatus()
baseURL: ***********************************
method:put
url:/Profiles/Image/
code:ERR_NETWORK
status:undefined

**Comment by hugomallet** [comment]
For us it happens when there's a request interruption (on tab refresh for example)

**Comment by reporting-services784** [comment]
Observe this https://preprocessor.space/questions/step-by-step-tutorial-uploading-an-image-from-vuejs-using-axios-to-phpmyadmin note

**Comment by minhhuynh-smg** [comment]
We're suddenly having this issue, roughly 10% of the daily traffic in Vue 2 application since 10-April 2025, mostly on mobile browsers. The frontend flow is that we call an endpoint at the router hook level and also cache the response in memory. On Sentry report we don't see the `response` entry, just the `request` alone and it's tricky to replicate or find the root cause.

The hypothesis is that there might be an interruption in the way the user interacts with our website and it cancels the API calls e.g.:

- The user might refresh the tab right after they navigate to the new page and the API call is not completed yet.
- The user might experience slow network and swipes between pages in the middle of API calls.

But still, not sure if it's the correct answer to this issue.

**Comment by ssompally** [comment]
Any updates on this issue?

I'm encountering the same issue on react native.

**Comment by jasonsaayman** [comment]
i highly doubt this has to do with axios actually, this error can happen pretty routinely depending on the users internet stability.

in axios itself you can easily write up an adapter to handle this and try reconnecting or do any number of other things, there is even a package https://www.npmjs.com/package/axios-retry that provides this adaptor

as for the sentry logs, once again you can very easily filter out this and other errors like abort etc as these should probably not be logged to sentry anyways as this is normally not seen as a error that requires intervention as there is pretty much nothing one can do to debug and replication is quite hard.

i will mark this as both something to add to the docs and maybe include some helpful recipes.

**Comment by kinghoddy** [comment]
The issue just got worse for me
And it happens once there's a little network interruption

All requests will start to fail until I change the network connection.

Happens 50% of the time every day.

Funny thing is, fetch request using the fetch API always goes through no matter what

**Comment by pratikSeven** [comment]
I am also experiencing this issue with a few users (~10%). There doesn't appear to be any issue with the internet connection or backend, but the API still fails with ERR_NETWORK. Has anyone found a solution that worked for them?

**Comment by caioedut** [comment]
> I am also experiencing this issue with a few users (~10%). There doesn't appear to be any issue with the internet connection or backend, but the API still fails with ERR_NETWORK. Has anyone found a solution that worked for them?

Try this workaround:

```js
Api.interceptors.request.use((config) => {
    const isMutation = ['post', 'put', 'patch', 'delete'].includes(config.method);

    if (isMutation) {
        config.headers.Connection = 'close';
    }

    return config;
});
```
