### ISSUE TITLE
axios.get("file://path/to/file") fails with AssertionError actual: 'file:', expected: 'http:'

### ISSUE THREAD

**Issue by pmorch** [axios/axios#5648]
### Describe the bug

I was expecting to be able to use axios to get files also using the `file://...` scheme. But it doesn't work.

### To Reproduce

```shell
$ echo 'require("axios").get("file://path/to/file")' | node
            triggerUncaughtException(err, true /* fromPromise */);
            ^

AssertionError [ERR_ASSERTION]: protocol mismatch
    at Object.request (/home/pmorch/work/try/my-extension/node_modules/follow-redirects/index.js:521:14)
    at dispatchHttpRequest (/home/pmorch/work/try/my-extension/node_modules/axios/dist/node/axios.cjs:2816:21)
    at /home/pmorch/work/try/my-extension/node_modules/axios/dist/node/axios.cjs:2538:5
    at new Promise (<anonymous>)
    at wrapAsync (/home/pmorch/work/try/my-extension/node_modules/axios/dist/node/axios.cjs:2518:10)
    at http (/home/pmorch/work/try/my-extension/node_modules/axios/dist/node/axios.cjs:2544:10)
    at Axios.dispatchRequest (/home/pmorch/work/try/my-extension/node_modules/axios/dist/node/axios.cjs:3487:10)
    at Axios.request (/home/pmorch/work/try/my-extension/node_modules/axios/dist/node/axios.cjs:3843:33)
    at Axios.<computed> [as get] (/home/pmorch/work/try/my-extension/node_modules/axios/dist/node/axios.cjs:3869:17)
    at Function.wrap [as get] (/home/pmorch/work/try/my-extension/node_modules/axios/dist/node/axios.cjs:29:15) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: 'file:',
  expected: 'http:',
  operator: '=='
}

Node.js v18.12.1

```

### Code snippet

```js
See above
```

### Expected behavior

I expect to be able to get files too

### Axios Version

1.3.5

### Adapter Version

I don't know

### Browser

node.js

### Node.js Version

v18.12.1

### OS

Linux

**Comment by mskarimi** [comment]
same issue

**Comment by All3xJ** [comment]
me too

**Comment by Oscaner** [comment]
+1

**Comment by DigitalBrainJS** [comment]
I doubt that there is any practical sense in implementing this, anyway, it would certainly be like opening Pandora's box in the context of a server platform, since it would be a huge security problem. It is not implemented in fetch for the same reason - there is no clear specification, and the practical benefit is questionable.

https://github.com/nodejs/node/issues/48554#issuecomment-1607302941

**Comment by jasonsaayman** [comment]
yeah closing this is not a path we want to probably explore at this point
