### ISSUE TITLE
create group error 

### ISSUE THREAD

**Issue by sagirr** [axios/axios#5968]
### Describe the bug

when create group as
 const groupname="groupname 23";

  const ress = await client.createGroup(groupname, ["905510.....@c.us"]);

error here 

Grup oluşturulurken hata oluştu: Error: Evaluation failed: i
    at ExecutionContext._evaluateInternal (C:\Users\Administrator\Desktop\bot\node_modules\whatsapp-web.js\node_modules\puppetee
r\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\Users\Administrator\Desktop\bot\node_modules\whatsapp-web.js\node_modules\puppeteer\l
ib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Client.createGroup (C:\Users\Administrator\Desktop\bot\node_modules\whatsapp-web.js\src\Client.js:1298:27)
    at async C:\Users\Administrator\Desktop\bot\wp.js:92:18

### Node.js Version

Node.js v18.18.0

**Comment by jasonsaayman** [comment]
Thanks for your bug report, we will be closing this issue and ask that you please test and try re-create the issue with the latest version of Axios. If the bug is still present please open a issue. If possible and you are willing open a pull request with a proposed fix. Please see the motivation for doing this:

https://github.com/axios/axios/issues/6983
