### ISSUE TITLE
API call not working in axios, but working with fetch (simple get request)

### ISSUE THREAD

**Issue by amandesai01** [axios/axios#6008]
### Describe the bug

Following code doesn't work with `Axios`, but works when using simple fetch + works in browser.
Also doesn't work with cURL.

Full Reproduction Here: https://github.com/ShreyasTalole2001/find-axios-error

```Javascript
const url = "https://www.nseindia.com/api/option-chain-indices?symbol=NIFTY"

const response = await axios.get(url);
```

Error:
```
AxiosError: read ETIMEDOUT
    at AxiosError.from (/workspace/find-axios-error/node_modules/axios/dist/node/axios.cjs:837:14)
    at RedirectableRequest.handleRequestError (/workspace/find-axios-error/node_modules/axios/dist/node/axios.cjs:3016:25)
    at RedirectableRequest.emit (node:events:517:28)
    at eventHandlers.<computed> (/workspace/find-axios-error/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:517:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  syscall: 'read',
  code: 'ETIMEDOUT',
  errno: -110,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': undefined,
      'User-Agent': 'axios/1.5.1',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'https://www.nseindia.com/api/option-chain-indices?symbol=NIFTY',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/api/option-chain-indices?symbol=NIFTY',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'www.nseindia.com',
      port: '',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/api/option-chain-indices',
      search: '?symbol=NIFTY'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /api/option-chain-indices?symbol=NIFTY HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.5.1\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: www.nseindia.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/api/option-chain-indices?symbol=NIFTY',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'www.nseindia.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://www.nseindia.com/api/option-chain-indices?symbol=NIFTY',
    [Symbol(kCapture)]: false
  },
  cause: Error: read ETIMEDOUT
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'read'
  }
}
^C
```

### To Reproduce

https://github.com/ShreyasTalole2001/find-axios-error

### Axios Version

1.5.1

**Comment by TA2k** [comment]
Did you try to use a browser user agent and correct content type?

**Comment by amandesai01** [comment]
@TA2k it works without browser agent with fetch and cURL (or any other api client). So I don't think that's the cause

**Comment by TA2k** [comment]
Maybe but with the correct header the endpoint will accept your request

```
const response = await axios.get(url, {
  headers: {
    authority: 'www.nseindia.com',
    'accept-language': 'en',
    cookie: 'AKA_A2=A',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36',
  },
});
```

**Comment by amandesai01** [comment]
Yes I know it works like that. Concern here is why not work simply when it works in other libs. There might be some wrong implementation which is very rare, hence found it necessary to report. Maintainers can take the call to resolve it or discard it.

**Comment by Epileptic-Experience** [comment]
Hey did you solve this? im having the same issue

**Comment by jasonsaayman** [comment]
cant see why this would not work but i presume something is miss-configured; potentially on the server side, i presonally make many get request with axios and they all work, closing

**Comment by amandesai01** [comment]
It is misleading to close it as "completed" as it is clearly not. A get request should work similarly regardless of library, so server's configuration is not axios's concern.

**Comment by jasonsaayman** [comment]
I did try to navigate to this URI to see what happens, and I got an error. It seems you must get some cookies set from the actual root domain before you can use this EP. Once I had the additional cookies set by the root domain, it worked correctly. Also i tried both fetch and axios and got the exact same thing happening so once again notjing here is wrong with axios else its also wrong with fetch
