### ISSUE TITLE
Application fails to require the axios package

### ISSUE THREAD

**Issue by denny99** [axios/axios#6069]
### Describe the bug

```
TypeError: Cannot read properties of undefined (reading 'charAt')
    at resolveURL (/Users/dennymueller/IdeaProjects/forest-school-saxony/node_modules/axios/dist/node/axios.cjs:3241:44)
    at standardBrowserEnv (/Users/dennymueller/IdeaProjects/forest-school-saxony/node_modules/axios/dist/node/axios.cjs:3247:17)
    at Object.<anonymous> (/Users/dennymueller/IdeaProjects/forest-school-saxony/node_modules/axios/dist/node/axios.cjs:3260:5)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/dennymueller/IdeaProjects/forest-school-saxony/node_modules/@nestjs/axios/dist/http.module.js:16:33)
``` 

The error above causes my application to fail upon boot.
This error explicitly happens when using the latest version 1.6.1 NOT with 1.6.0.
And it only happens when i use the production build of my application not in dev mode.

I am using a combination of webpack, nestjs, angular with angular-universal and domino as mock for ssr.

### To Reproduce

Checkout the project:
https://github.com/denny99/axios-ticket.git

Run:
```
npm ci
npm run build
npm start
```

Crashes with the error message that the axios package is not installed.
This is statement is not quite correct. Its caused as the require of axios fails.
For easier debugging, i've added a `require('axios')` in backend/main.ts line 12

Change the axios package to 1.6.0
```
npm i
npm run build
npm start
```
Then it starts again without error.

### Code snippet

```js
const axios_1 = __importDefault(require("axios"));

System crashes when requiring the package in nest.js.
Fails at pathname at this code snippet:


      return {
        href: urlParsingNode.href,
        protocol: urlParsingNode.protocol ? urlParsingNode.protocol.replace(/:$/, '') : '',
        host: urlParsingNode.host,
        search: urlParsingNode.search ? urlParsingNode.search.replace(/^\?/, '') : '',
        hash: urlParsingNode.hash ? urlParsingNode.hash.replace(/^#/, '') : '',
        hostname: urlParsingNode.hostname,
        port: urlParsingNode.port,
        pathname: (urlParsingNode.pathname.charAt(0) === '/') ?
          urlParsingNode.pathname :
          '/' + urlParsingNode.pathname
      };
```

### Expected behavior

No crashes as in 1.6.0

### Axios Version

1.6.1

### Node.js Version

v18.16.0

### Additional Library Versions

```bash
NestJS ~10.0.0
Angular ~16.2.0
Domino ^2.1.6
```

**Comment by denny99** [comment]
The issue is definitely related to the domino ssr polyfill.
To be more specific:
`global['document'] = win.document;`

Uncommenting this line lets the application boot again.

So the "is browser check" must have changed in axios 1.6.1 compared to 1.6.0

**Comment by jgreer9514** [comment]
Can this just be changed for a null check:  pathname: (urlParsingNode.pathname?.charAt(0) === '/')

**Comment by jgreer9514** [comment]
I ended up getting around this by changing the vitest config environment from happy-dom to jsdom and it worked.

**Comment by hamzakhan11** [comment]
Any update on the above issue? Facing the same issue with angular ssr and tried different ways but still no success.

**Comment by bugattie** [comment]
@jgreer9514 can you please share your happy-dom configurations?

**Comment by bugattie** [comment]
> I ended up getting around this by changing the vitest config environment from happy-dom to jsdom and it worked.

@jgreer9514 can you please share your happy-dom configurations?

**Comment by Satsukevich-Dzmitry** [comment]
Same issue for me. And i also use `happy-dom` for tests. Fixed by swithing to jsdom, but is there a way to fix it without swithing?

**Comment by jasonsaayman** [comment]
i would presume something in happy-dom and axios are clashing, im going to close this but if you would like to submit a PR please do and we can try solve the issue
