### ISSUE TITLE
[BUG] When there are prolonged periods of high concurrent requests, the response processing is slow, and the time intervals are long

### ISSUE THREAD

**Issue by luoxzhg** [axios/axios#6206]
### Describe the bug

When there are prolonged periods of high concurrent requests, the response processing is slow, and the time intervals are long

actually server response time little than 5ms

### To Reproduce

hosts

```
<private ip> abc.com
```

test script
```
const { setTimeout } = require('node:timers/promises');
const Axios = require('axios').default;
const FromData = require('form-data');
const { Readable } = require('node:stream');

const axios = Axios.create({
   baseURL: 'http://abc.com:3000'
});

(async() => {
   let n = 1
   let startTime = performance.now()
   while (n) {
      await test()
      // const endTime = performance.now()
      // console.log(`test count: ${n++}, usedtime: ${endTime - startTime}ms`)
      // await setTimeout(1000)
   }
})()

async function test() {
   const requests = []
   // for (let index = 0; index < 100; index++) {
      requests.push(send_request())
   // }

   const results = await Promise.allSettled(requests)
   results.forEach(result => {
      if (result.status == 'rejected') {
         console.log('rejected error', result.reason)
      }
   })
}

const buf = Buffer.allocUnsafe(1024*50)

async function send_request() {
   // await setTimeout(Math.random() * 1000 * 10)
   const startTime = performance.now()
   await axios.put('/', { data: 'post'})
   const putTime = performance.now()
   console.log(`put time ${ putTime - startTime}`)

   const form = new FromData({ maxDataSize: Infinity })
   form.append('file', Readable.from(buf))
   await axios.post('/', form, {
      headers: form.getHeaders()
   })
   const postTime = performance.now()
   console.log(`post time ${postTime - putTime}`)

   await axios.post('/', { data: 'post'})
   const postTime2 = performance.now()
   console.log(`post time2 ${postTime2 - postTime}`)

   await axios.get('/')
   const getTime = performance.now()
   console.log(`get time ${getTime - postTime2}`)
}

```

server.js
```
import { fastify } from "fastify";
import { routers } from "./router.js";
const server = fastify({
   connectionTimeout: 30000,
   requestTimeout: 60000,
   forceCloseConnections: true,
   logger: true
})

server.register(routers)

;(async() => {
   try {
      await server.listen({
         host: '0.0.0.0',
         port: 3000
      })
   } catch (error) {
      server.log.error(error)
      process.exit(1)
   }
})()

```
router.js
```

/**
 *
 * @param {import("fastify").FastifyInstance} fastify
 * @param {Object} options
 */
export async function routers(fastify, options) {
   fastify.register(await import('@fastify/multipart'))

   fastify.get('/', async (req, reply) => {
      req.log.info('hello word')
      return { hello: 'world' }
   })

   fastify.post('/', async (req, reply) => {
      return { message: 'post successed' }
   })

   fastify.put('/', async (req, reply) => {
      return { message: 'put successed' }
   })
}

```

result: 
![图片](https://github.com/axios/axios/assets/25560573/2c0ad801-1515-4091-843d-b23f2c4bb3ee)

### Expected behavior

handle response time expected < 100ms

### Axios Version

1.6.7

### Adapter Version

http

### Node.js Version

node 18-alpine

### OS

apline

### Additional Library Versions

```bash
Dockerfile

FROM node:18-alpine

COPY package.json ./
RUN npm install

COPY test.js ./

CMD ["node", "test.js"]

```
```


### Additional context/Screenshots

_No response_

**Comment by luoxzhg** [comment]
I switch to node:20-alpine, the worst time is about 500ms
![图片](https://github.com/axios/axios/assets/25560573/1d03e221-f9bd-4629-959f-28c78df8afda)

**Comment by deepak-agendaboa** [comment]
Maybe this one #6202 is related.

**Comment by HiptJo** [comment]
+1

**Comment by NikolayPIvanov** [comment]
We are experiencing the same issue with 1.6.7. The last version we know about without issue was 1.6.2. 

I presume the issue was introduce in 1.6.6 or 1.6.7.

**Comment by ricfio** [comment]
+1

**Comment by Mavahu** [comment]
+1

**Comment by meetAndEgg** [comment]
`keepAlive:false` dose not work for me :( 
I have this issue in 1.6.0, 1.6.8, 1.7.2

**Comment by Mavahu** [comment]
I was able to fix it by replacing axios with node-fetch.

**Comment by enote-kane** [comment]
I've replaced Axios in our server-side code with got. Now working reliably as it provides more insights into the request/connection states and timings (e.g. pointed us to an issue with our DNS config inside Kubernetes clusters).

**Comment by meetAndEgg** [comment]
> `keepAlive:false` dose not work for me :( I have this issue in 1.6.0, 1.6.8, 1.7.2
There is something strange, my bug only occurs frequently when accessing a specific interface of mine. At the same time, I have no problem using axios to access other interfaces under the same domain name.
But I have fixed it by using node native https.

**Comment by abnerwei** [comment]
same problem


<html>
<body>

Error: socket hang up     <br>
at handleException (/usr/local/app/webpack:/src/core/request/interceptors/exception-handler/response-interceptor.ts:27:17)   <br>  
at processTicksAndRejections (node:internal/process/task_queues:95:5)    <br>
at Axios.request (/usr/local/app/node_modules/axios/lib/core/Axios.js:40:14)     <br>
at Axios.request (/usr/local/app/node_modules/axios/lib/core/Axios.js:45:41)     <br>
at processTicksAndRejections (node:internal/process/task_queues:95:5)
--



</body>
</html>

**Comment by mrosenbaum15** [comment]
+1 to experiencing this with Node 18 Alpine and Axios v1.7.3

**Comment by Villen37** [comment]
I fixed it by axios-retry, then added some log to check it, anyway, it's ok now.

**Comment by fjeldstad** [comment]
Could it be related to the Node.js 19+ issue mentioned here? https://github.com/node-fetch/node-fetch/issues/1735

**Comment by jasonsaayman** [comment]
possibly https://github.com/axios/axios/issues/6113#issuecomment-2656966165 could assit but its quite hard to diagnose these errors as it can simply be a real socket hang and you would need to handle that either with axios-retry or doing your own implementation. in the next version we may look into a plugin for this or a recipe
