### ISSUE TITLE
Help on "axios.post()" usage

### ISSUE THREAD

**Issue by abdulbadii** [axios/axios#6217]
### Describe the issue

i'm noob in axios, jus run into it when need to use google translate API, so run:
```
axios = require('axios');
// const API = 'something';

async function translate( text, tl) {
 let r = await axios.post(
  'https://translation.googleapis.com/language/translate/v2?key='+API,
  { q: text, target: tl }
 )
 return r.data.data.translations[0].translatedText
}
```
and got:

```
       AxiosError [AggregateError]
          at AxiosError.from (/usr/lib/node_modules/axios/dist/node/axios.cjs:837:14)
          at RedirectableRequest.handleRequestError (/usr/lib/node_modules/axios/
```
...
Anyone explain what is the error all about, how to get it solved ? 

### Axios Version

$ npm show axios version 1.6.7

### Node.js Version

$ node --version v21.6.1

### OS

Arch Linux

**Comment by pjnichal** [comment]
surround your axios code with try catch

axios = require('axios');
// const API = 'something';

async function translate( text, tl) {
try{
 let r = await axios.post(
  'https://translation.googleapis.com/language/translate/v2?key='+API,
  { q: text, target: tl }
 )
 return r.data.data.translations[0].translatedText
}catch(error){
console.log(error)
}
}



this will print error stack

**Comment by abdulbadii** [comment]
after update, now error is:
```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^
AxiosError: Request failed with status code 400
    at settle (/usr/lib/node_modules/axios/dist/node/axios.cjs:1967:12)
    at Unzip.handleStreamEnd (/usr/lib/node_modules/axios/dist/node/axios.cjs:3066:11)
    at Unzip.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/usr/lib/node_modules/axios/dist/node/axios.cjs:3877:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async gtranslate (/tmp/Downloads/gxlt.js:7:11)
...
...
```
line 7 is `let r = await axios.post( `

**Comment by jasonsaayman** [comment]
i believe you are getting a http status 400 response from the endpoint you are trying to post which in this case is correct

**Comment by abdulbadii** [comment]
Yup correct
latest info across online is Google Cloud (GC) APi procedure no longer work using this request, but could still by use of `curl`
also FYI, API itself it's no longer 100% free unless pass the GC setting with credit card number which many fulfilling it with credit card number generator

**Comment by rdev06** [comment]
This is not an `axios` issue, looks like its google thing.
@pjnichal given right suggestion. async function should be wrapped with `try catch` block.
@abdulbadii You should accept this suggestion

**Comment by suhaotian** [comment]
Try use `params`:


```ts
axios = require('axios');
// const API = 'something';

async function translate( text, tl) {
 let r = await axios.post(
  'https://translation.googleapis.com/language/translate/v2?key='+API,
  null,
{params: {q: text, target: tl}}
 )
 return r.data.data.translations[0].translatedText
}
```
