### ISSUE TITLE
"Class extends value #<newConstructor> is not a constructor or null

### ISSUE THREAD

**Issue by mattwatts-aimltd-uk** [axios/axios#6340]
### Describe the issue

Hi all,

After recently trying to upgrade from node.js 18.18.1 to the latest LTS (20.12.0) my Axios requests are failing with the below error:
```
TypeError: Class extends value #<newConstructor> is not a constructor or null
	at lib/websocket/events.js (node:internal/deps/undici/undici:11139:52)
	at __require (node:internal/deps/undici/undici:6:50)
	at lib/websocket/util.js (node:internal/deps/undici/undici:11390:40)
	at __require (node:internal/deps/undici/undici:6:50)
	at lib/websocket/websocket.js (node:internal/deps/undici/undici:11951:96)
	at __require (node:internal/deps/undici/undici:6:50)
	at node:internal/deps/undici/undici:12353:28
	at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:398:7)
	at requireBuiltin (node:internal/bootstrap/realm:429:14)
	at get FormData (node:internal/util:606:15)
	at Object.isFormData (/var/api/node_modules/axios/lib/utils.js:192:3)
	at Object.transformRequest (/var/api/node_modules/axios/lib/defaults/index.js:51:30)
	at transform (/var/api/node_modules/axios/lib/core/transformData.js:22:15)
	at Object.forEach (/var/api/node_modules/axios/lib/utils.js:255:10)
	at Object.transformData (/var/api/node_modules/axios/lib/core/transformData.js:21:9)
	at Axios.dispatchRequest (/var/api/node_modules/axios/lib/core/dispatchRequest.js:40:31)
	at Axios._request (/var/api/node_modules/axios/lib/core/Axios.js:170:33)
	at Axios.request (/var/api/node_modules/axios/lib/core/Axios.js:40:25)
	at Axios.httpMethod [as post] (/var/api/node_modules/axios/lib/core/Axios.js:209:19)
	at Function.post (/var/api/node_modules/axios/lib/helpers/bind.js:5:15)
	at authenticate (/var/api/api/services/IntegrationEngine/AuthProvider/AccessToken.ts:113:44)
	at processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async prepareAndRequest (/var/api/api/services/IntegrationEngine/RequestEndpointIntegration.ts:692:24)
	at async Object.prepareAndRequest (/var/api/api/services/IntegrationEngine/RequestEndpointIntegration.ts:725:20)
	at async Object.processStep (/var/api/api/services/IntegrationEngine/StepProcessor.ts:133:28)
	at async Object.processIntegrationFlow (/var/api/api/services/IntegrationEngine/FlowProcessor.ts:328:17)
	at Axios.request (/var/api/node_modules/axios/lib/core/Axios.js:45:41)
	at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
Reverting back to the old node version prevents this from being an issue.

This seems to only be an issue where I'm sending a request with ```qs.stringify(data)``` in the body, but can't see any incompatibilities between this version of Node and QS.

I'm running Axios within a Dockerized Node.js container.

Does anyone have any idea as to why this might be happening?

### Example Code

```js
const axiosClient = axios.create({
    timeout: 30000,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
    },
});


const response = await axiosClient.post(
            url,
            qs.stringify(body)
        );
```

### Expected behavior

Axios should send and receive the HTTP request in the same manner between Node versions.

### Axios Version

1.6.8

### Node.js Version

20.12.0

**Comment by DigitalBrainJS** [comment]
> 20.12.0
> 18.18.2

I can't reproduce the issue using your example in both versions. Have you tested this on your example?

**Comment by jcowley** [comment]
We've been hampered by this Axios issue for months and are stuck on node v18.18.1 because of it. We don't use axios directly in our project, but the @slack/web-api and stream-chat npm libraries both use axios.

Our "fix" is to downgrade to node v18.18.1. As the OP states, anything v18.18.2 or greater gets this same error.

**Comment by thefirstspine** [comment]
Hello,

We experienced this issue on our repo: https://github.com/thefirstspine/website, very likely on this piece of code: https://github.com/thefirstspine/dependency-logs/blob/master/src/loggly-winston.ts#L31-L41

```
TypeError: Class extends value #<newConstructor> is not a constructor or null
    at lib/web/websocket/events.js (node:internal/deps/undici/undici:10695:52)
    at __require (node:internal/deps/undici/undici:6:50)
    at lib/web/websocket/util.js (node:internal/deps/undici/undici:10946:40)
    at __require (node:internal/deps/undici/undici:6:50)
    at lib/web/websocket/websocket.js (node:internal/deps/undici/undici:11541:9)
    at __require (node:internal/deps/undici/undici:6:50)
    at node:internal/deps/undici/undici:12511:28
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:398:7)
    at requireBuiltin (node:internal/bootstrap/realm:429:14)
    at get FormData (node:internal/util:606:15)
    at Object.isFormData (/website/node_modules/axios/dist/node/axios.cjs:219:3)
    at Object.transformRequest (/website/node_modules/axios/dist/node/axios.cjs:1453:32)
    at transform (/website/node_modules/axios/dist/node/axios.cjs:1921:15)
    at Object.forEach (/website/node_modules/axios/dist/node/axios.cjs:282:10)
    at Object.transformData (/website/node_modules/axios/dist/node/axios.cjs:1920:11)
    at Axios.dispatchRequest (/website/node_modules/axios/dist/node/axios.cjs:3611:31)
    at Axios.request (/website/node_modules/axios/dist/node/axios.cjs:3876:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Used axios version:

```
    "node_modules/axios": {
      "version": "1.6.8",
      "resolved": "https://registry.npmjs.org/axios/-/axios-1.6.8.tgz",
      "integrity": "sha512-v/ZHtJDU39mDpyBoFVkETcd/uNdxrWRrg3bKpOKzXFA6Bvqopts6ALSMU3y6ijYxbw2B+wPrIv46egTzJXCLGQ==",
      "dependencies": {
        "follow-redirects": "^1.15.6",
        "form-data": "^4.0.0",
        "proxy-from-env": "^1.1.0"
      }
    },
```

Downgrading from Node 20 to Node 18 fixed the issues for us: https://github.com/thefirstspine/website/commit/ec956920839d552ae3a3626be8c789cb6a243e59

Feel free to ask for more details

Regards,

Teddy

**Comment by mattwatts-aimltd-uk** [comment]
For what it's worth, this seems to be fine now in Node 18.20.4

**Comment by jcowley** [comment]
Same issue for us in node 18.20.4. Very frustrating.

**Comment by jasonsaayman** [comment]
please try the latest version if this still persist, else if this is still a bug pleas open a new issue
