### ISSUE TITLE
how can I request use a socksv5

### ISSUE THREAD

**Issue by shangxinbo** [axios/axios#636]
```
const http = require('http');
const socks = require('socksv5');
http.get({ 
   hostname: 'google.com',
   port: 80,
   agent: new socks.HttpAgent({
          proxyHost: config.host,
          proxyPort: tcpPorts[i],
          auths: [socks.auth.None()]
    })
},function(res){
console.log(res);
})
```
when I use http request it can get the response,But when I use axios, it throw a error like this
```
    axios.request({
        url:'http://www.google.com',
        httpAgent: new socks.HttpAgent({
            proxyHost: config.host,
            proxyPort: tcpPorts[i],
            auths: [socks.auth.None()]
        })
    })
    .then(function(res){
        console.log(res);
    })
    .catch(function(err){
        console.log(err);
    })
```
I got the agent  like this
```
{
  domain: null,
  _events: { free: [Function] },
  _eventsCount: 1,
  _maxListeners: undefined,
  defaultPort: 443,
  protocol: 'https:',
  options:
   { auths: [ [Object] ],
     proxyPort: 10086,
     proxyHost: '127.0.0.1',
     path: null },
  requests: {},
  sockets: {},
  freeSockets: {},
  keepAliveMsecs: 1000,
  keepAlive: false,
  maxSockets: Infinity,
  maxFreeSockets: 256 }
```

**Comment by rubennorte** [comment]
Could you provide information about the error that is throwing?

**Comment by shangxinbo** [comment]
```
{ Error: connect ETIMEDOUT 8.7.198.45:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '8.7.198.45',
  port: 443,
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.15.3' },
     method: 'get',
     url: 'https://www.google.com.hk',
     httpAgent:
      TunnelingAgent {
        options: [Object],
        proxyOptions: [Object],
        maxSockets: Infinity,
        requests: [],
        sockets: [],
        _events: [Object],
        _eventsCount: 1,
        request: [Function],
        createSocket: [Function: createSecureSocket] },
     data: undefined },
  response: undefined }

**Comment by c0b** [comment]
have an issue with socks5 either, from https://github.com/mscdex/socksv5 I can create by `new socks.HttpAgent({ ... })` make it work with node builtin http request, but with this axios.request httpAgent, it seems ignoring the proxy; does anyone have progress here?

**Comment by jiangfb** [comment]
Answer is here:
https://medium.com/@paynoattn/using-a-socks-proxy-to-make-requests-in-node-js-ba5125c7999f

**Comment by Dj-jom2x** [comment]
@jiangfb  thats not working i think , if you tried to check make some api that gets your ip it will still show your local ip

**Comment by denysonique** [comment]
> @jiangfb thats not working i think , if you tried to check make some api that gets your ip it will still show your local ip

It works, make sure you specify both `httpsAgent and httpAgent` options 

```javascript
    import { default as axios_ } from 'axios'
    let httpsAgent =  new SocksProxyAgent(proxyOptions)
    let httpAgent = httpsAgent
   axios = axios_.create({httpsAgent, httpAgent})
```

**Comment by chinesedfan** [comment]
Closed due to stale. The answer should be yes. If users met problems again, feel free to open a new issue.

**Comment by conanskyforce** [comment]
```
  const SocksProxyAgent = require('socks-proxy-agent');
  const proxyOptions = `socks5://127.0.0.1:1081`; // your sock5 host and port;
  const httpsAgent = new SocksProxyAgent(proxyOptions);
  axios({
    httpsAgent,
    method:'GET',
    url:'....',
    //...
  })
```
