### ISSUE TITLE
TypeError: Converting circular structure to JSON     --> starting at object with constructor 'TLSSocket'

### ISSUE THREAD

**Issue by testinghere57564** [axios/axios#6388]
### Describe the bug

Due to the fact that Axios does not support some kinds of proxies, tunneling(HTPP OVER HTPPS idk), I don’t remember, I had to use such a crutch
const { HttpsProxyAgent } = require('https-proxy-agent');

const agent = new HttpsProxyAgent(`https://${proxyUsername}:${proxyPassword}@${proxyHost}:${proxyPort}`);

const axiosOptions = {
   httpsAgent: agent,

There were no such errors before this little change. There are no circular references in my code. This does not happen immediately, the code works for some time. Judging by the log, the error is somewhere inside the module
I send a lot of requests in my application

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property 'parser' -> object with constructor 'HTTPParser'
    --- property 'socket' closes the circle
    at stringify (<anonymous>)
    at stringifySafely (E:\Users\nazar\Desktop\work\docker\node_modules\axios\dist\node\axios.cjs:1435:37)
    at Object.transformRequest (E:\Users\nazar\Desktop\work\docker\node_modules\axios\dist\node\axios.cjs:1495:14)
    at transform (E:\Users\nazar\Desktop\work\docker\node_modules\axios\dist\node\axios.cjs:1921:15)
    at Object.forEach (E:\Users\nazar\Desktop\work\docker\node_modules\axios\dist\node\axios.cjs:282:10)
    at Object.transformData (E:\Users\nazar\Desktop\work\docker\node_modules\axios\dist\node\axios.cjs:1920:11)
    at Axios.dispatchRequest (E:\Users\nazar\Desktop\work\docker\node_modules\axios\dist\node\axios.cjs:3611:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Axios.request (E:\Users\nazar\Desktop\work\docker\node_modules\axios\dist\node\axios.cjs:3871:14)
    at Axios.request (E:\Users\nazar\Desktop\work\docker\node_modules\axios\dist\node\axios.cjs:3876:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Axios Version

1.6.8

### Node.js Version

Node.js v21.7.3

### Additional Library Versions

```bash
"name": "https-proxy-agent",
  "version": "7.0.4",
```

**Comment by jasonsaayman** [comment]
could you please provide a reproducible example please

**Comment by jasonsaayman** [comment]
closing as no information was added in over a month
