### ISSUE TITLE
Still getting the 'SyntaxError: Unexpected identifier' error

### ISSUE THREAD

**Issue by flyfisher1952** [axios/axios#6531]
### Describe the bug

I have deployed a node app to a v20.14.0 server. I have axios v^1.7.2. I have no issues on my development server and had no issues on my previous hosting service running node v20.14.0 either. However, the host I am currently using gives me the unexpected identifier error. 

/home/freeloxp/nodevenv/api.freefishingreports.com/10/lib/node_modules/axios/index.js:1
import axios from './lib/axios.js';
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/freeloxp/api.freefishingreports.com/models/solunar-day-model.js:7:33)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

I've tried using JS syntax 'const axios = require("./lib/axios.js");' without success.

### To Reproduce

This error occurs during app load. No steps are required to reproduce it.

### Expected behavior

I expect it to run without the error.

### Axios Version

1.7.2

### Browser

Any (I've tried Chrome, Edge)

### Browser Version

latest

### Node.js Version

20.14.0

### OS

unix

**Comment by DigitalBrainJS** [comment]
Have you checked the node version? What is the output of `console.log(process.version);` or console cmd `node -v`?
