### ISSUE TITLE
CommonJS / ESM mixup when using a lib that has Axios has peer dependency

### ISSUE THREAD

**Issue by foxaltus** [axios/axios#6591]
### Describe the issue

I am authoring a library that has Axios 1.7.4 as peer dependency (so Axios is not bundled with it).
The lib has both ESModule and CommonJS output.

When I import both the lib and Axios in a React application (CRA or webpack), I have this error when opening the app in the browser:
```
index.mjs:315 Uncaught (in promise) TypeError: axios__WEBPACK_IMPORTED_MODULE_0__.create is not a function
    at BaseService.axiosInstance (index.mjs:315:1)
    at ./node_modules/.pnpm/mylib@0.29.0-alpha.8_@types+react@18.0.28_axios@1.7.4_@mui+system_7n6tjqsrmbejf4ko57dpnqh2ey/node_modules/my-lib/dist/index.mjs (index.mjs:324:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at sharing:44:1
    at __webpack_require__.m.<computed> (consumes:186:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/bootstrap.tsx (src_bootstrap_tsx.chunk.js:16:68)
```
I can see in the debugger that the CommonJS version of Axios is loaded (the one with a named `default` export):
![image](https://github.com/user-attachments/assets/d1306ba8-ee7e-4250-99dd-c4e14e78e280)

Any clue on how to solve this problem?

FYI: if I dont use Axios as a peer dependency, I dont have the issue when consuming the lib (the ESM version of Axios is used):
![image](https://github.com/user-attachments/assets/9c022f52-a910-46e8-bafd-0696f74c5efe)

### Example Code

```js
// snippet of index.mjs in mylib
import axios from "axios";
// ...
var BaseService = class {
  headers = {};
  constructor(headers) {
    this.headers = { ...headers };
  }
  axiosInstance({ baseUrl = API_BASE_URL, omitResponseInterceptors } = {}) {
    const api = axios.create({ baseURL: baseUrl });
    api.interceptors.request.use((config) => requestInterceptor(this.headers, config), requestErrorResponse);
    if (!omitResponseInterceptors) {
      api.interceptors.response.use((res) => res, responseErrorInterceptor);
    }
    return api;
  }
};
```

### Expected behavior

I'm expecting the consuming app to use either ESM of my lib & axios, or both CommonJS versions.

Im not sure if it is an issue with my lib, axios, webpack or a more general issues when consuming modules that publish both CJS & ESM inside a CommonJS app... 

Thanks for the guidance 🙏

### Axios Version

1.7.4

### Node.js Version

18.20.2

**Comment by foxaltus** [comment]
Just a thought / suggestion: if Axios exported its default instance via a named export too, we could stop relying on the default export and write this directly, which would avoid many problems:

```ts
-import axios from 'axios';
+import { axios } from 'axios';
```

have the folk at Axios considered this?

**Comment by foxaltus** [comment]
As a workaround, I was able to force webpack to load the CommonJS version of my package. It works because it finds the `axios.default` instance which the CJS version of Axios exposes.

I achieved this using `resolve.alias` in the `webpack.config.js` file of the consuming app (see https://webpack.js.org/configuration/resolve/#resolvealias):

```js
const path = require('path');

module.exports = {
  //...
  resolve: {
    alias: {
      mylib: require.resolve('mylib'),
    },
  },
};
```

`require.resolve('mylib')` resolves to the CJS file as per the `package.json` exports in `mylib`.

It works, but I really don't like the solution as it's not practical (consumer shouldn't have to worry about this).

Looking at the other open issues, I think axios needs to improve the way the package is bundled (stop default export? re-export the instance via a named export? fix exports in package.json to point to the appropriate dist file instead of the root index.js?publish a new axios-es package?)

**Comment by foxaltus** [comment]
I found another workaround when bundling with `tsup`. I think `tsup` itself is having issues with `default` exports in CJS modules.

In order to avoid these issues (`axios__WEBPACK_IMPORTED_MODULE_0__.create is not a function` instead of `axios__WEBPACK_IMPORTED_MODULE_0__.default.create`), I ended up bundling `axios` with my package using this `tsup` config:

```typescript
import { defineConfig } from 'tsup';

export default defineConfig({
  // ...
  noExternal: ['axios'],
});
```

I also needed to patch `axios`'s `exports` using [pnpm patch](https://pnpm.io/cli/patch) to work around #5495:

```
diff --git a/package.json b/package.json
index a759d02f4d66c5cf834f0e291020b062ac9cabf7..1a13ebbbd79fc15fba8799158c498c3b1f695e16 100644
--- a/package.json
+++ b/package.json
@@ -11,11 +11,11 @@
       },
       "browser": {
         "require": "./dist/browser/axios.cjs",
-        "default": "./index.js"
+        "default": "./dist/esm/axios.js"
       },
       "default": {
         "require": "./dist/node/axios.cjs",
-        "default": "./index.js"
+        "default": "./dist/esm/axios.js"
       }
     },
     "./lib/adapters/http.js": "./lib/adapters/http.js",
``` 

Again, this is not ideal and it's only a workaround. But that's when you get when using `default` exports 😢

**Comment by denisx** [comment]
up this
