### ISSUE TITLE
ERR_NETWORK while performing PUT API with mutli-part formdata in android devices  - AxiosError: Network Error at handleError

### ISSUE THREAD

**Issue by vinamrahalgar** [axios/axios#6609]
### Describe the bug

I am performing a PUT operation in android rect native using axios. It is giving me error ERR_NETWORK. 
Any solution on how to fix this. Works fine in iOS but throws AxiosError: Network Error at handleError in android devices
I am using -     "axios": "^1.6.7"

message:Network Error
name:AxiosError
description:undefined
number:undefined
fileName:undefined
lineNumber:undefined
columnNumber:undefined
stack:AxiosError: Network Error at handleError (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:162686:39) at call (native) at dispatchEvent (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:39761:31) at setReadyState (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:38964:33) at __didCompleteResponse (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:38750:29) at apply (native) at anonymous (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:38892:52) at apply (native) at emit (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:3317:40) at apply (native) at anonymous (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:3117:200) at emit (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:3150:62) at apply (native) at __callFunction (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:2207:38) at anonymous (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:1923:31) at _guard (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:2140:15) at callFunctionReturnFlushedQueue (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:1922:21) at ?anon_0 (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:161016:64) at throw (native) at asyncGeneratorStep (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:31333:19) at _throw (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:31350:29) at tryCallOne (address at InternalBytecode.js:1:1180) at anonymous (address at InternalBytecode.js:1:1874) at apply (native) at anonymous (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:38081:26) at _callTimer (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:37960:17) at _callReactNativeMicrotasksPass (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:38005:17) at callReactNativeMicrotasks (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:38211:44) at __callReactNativeMicrotasks (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:2168:48) at anonymous (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:1941:45) at __guard (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:2140:15) at flushedQueue (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:1940:21) at callFunctionReturnFlushedQueue (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.cgs.bwphone.droid&modulesOnly=false&runModule=true:1925:33)
timeout:0
xsrfCookieName:XSRF-TOKEN
xsrfHeaderName:X-XSRF-TOKEN
maxContentLength:-1
maxBodyLength:-1
validateStatus: validateStatus()
baseURL: ***********************************
method:put
url:/Profiles/Image/
code:ERR_NETWORK
status:undefined

### Code snippet

```js
const body = new FormData();
        body.append('File', {
          uri: `file://${processedDocumentPath}`,
          type: 'application/pdf',
          name: `${workFlowId}.pdf`,
        });
```

### Axios Version

^1.6.7

**Comment by jasonsaayman** [comment]
Closing see #6968
