### ISSUE TITLE
socketPath feature is broken at 1.7.7

### ISSUE THREAD

**Issue by Jssly** [axios/axios#6611]
### Describe the bug

throw error TypeError [ERR_INVALID_URL]: Invalid URL if sockPath is used.

### Axios Version

1.7.7

### Node.js Version

18.20.2

### OS

Win 11

### Additional context/Screenshots

```bash
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:676:13)
    at dispatchHttpRequest (file:///F:/git/node/libraries/nodelib_epg/node_modules/axios/lib/adapters/http.js:232:20)
    at file:///F:/git/node/libraries/nodelib_epg/node_modules/axios/lib/adapters/http.js:152:5
    at new Promise (<anonymous>)
    at wrapAsync (file:///F:/git/node/libraries/nodelib_epg/node_modules/axios/lib/adapters/http.js:132:10)
    at http (file:///F:/git/node/libraries/nodelib_epg/node_modules/axios/lib/adapters/http.js:170:10)
    at Axios.dispatchRequest (file:///F:/git/node/libraries/nodelib_epg/node_modules/axios/lib/core/dispatchRequest.js:51:10)
    at Axios._request (file:///F:/git/node/libraries/nodelib_epg/node_modules/axios/lib/core/Axios.js:173:33)
    at Axios.request (file:///F:/git/node/libraries/nodelib_epg/node_modules/axios/lib/core/Axios.js:40:25)
    at Axios.request (file:///F:/git/node/libraries/nodelib_epg/node_modules/axios/lib/core/Axios.js:45:41)
```

**Comment by PritamP20** [comment]
any additional informations?

**Comment by Anurag0218** [comment]
is this issue open? is anyone working on it? If not, can I take it up?

**Comment by PritamP20** [comment]
working on it

**Comment by Jssly** [comment]
@PritamP20 more informtion,  in this case, the socketPath is an Unix domain socket , that means it's a file path.

example: 
axios({ url: '/testing', socketPath:'/tmp/nginx.sock' }) 

it works fine in 1.7.3. but fails in 1.7.4+

**Comment by hivenet-tomcrammond** [comment]
Just wanted to bump this as I am also experiencing this issue. For now, reverting to v1.7.3 resolves the issue.

**Comment by VaitoSoi** [comment]
Does this bug fix now?

**Comment by devareddy05** [comment]
Opened PR: https://github.com/axios/axios/pull/10930

Fixes `TypeError [ERR_INVALID_URL]` for Unix socket requests introduced in `1.7.4`, where `new URL(fullPath, ...)` rejected path-only URLs such as `/foo` when used with `socketPath`.
This restores the `1.7.3` behavior by supplying a synthetic `http://localhost` base only for `socketPath` requests.
Non-socket requests remain unchanged, and absolute URLs continue to behave per the URL specification.

Happy if this helps 🙂
