### ISSUE TITLE
ENOMEM errors during test execution

### ISSUE THREAD

**Issue by Robg79new** [axios/axios#6713]
### Describe the bug

Hi,

Since the end of last week, now on every test execution, some of my tests are failing due to this error:

     connect ENOMEM 91.208.207.141:443 - Local (0.0.0.0:0)
      at Function.AxiosError.from (node_modules/codeceptjs/node_modules/axios/lib/core/AxiosError.js:89:14)
      at RedirectableRequest.handleRequestError (node_modules/codeceptjs/node_modules/axios/lib/adapters/http.js:606:25)
      at RedirectableRequest.emit (node:events:529:35)
      at RedirectableRequest.emit (node:domain:489:12)
      at ClientRequest.eventHandlers.<computed> (node_modules/follow-redirects/index.js:38:24)
      at ClientRequest.emit (node:events:517:28)
      at ClientRequest.emit (node:domain:489:12)
      at TLSSocket.socketErrorListener (node:_http_client:501:9)
      at TLSSocket.emit (node:events:517:28)
      at TLSSocket.emit (node:domain:489:12)
      
 I have not seen this error before and would appreciate some advice on what could be causing the error.
 
 Thanks in advance

**Comment by Robg79new** [comment]
Upgrading node to version 20 or above resolved this problem

**Comment by OwenAllen0** [comment]
If you still have this issue after upgrading to node, you might want to make sure [keepAlive](https://github.com/axios/axios/issues/1846) is enabled. I had a similar issue where axios was raising ENOMEM errors even though the memory usage never exceeded 500mb (out of 4096mb).

I believe the issue was that during polling operations where the same endpoint is called many times, axios was creating a new TCP connection and for some reason the old ones were not being cleared properly. This was on MacOs.
