### ISSUE TITLE
CAN NOT GET THE RESPONSE DATA WHEN RESPONSE STATUS CODE 4xx

### ISSUE THREAD

**Issue by TQLeung** [axios/axios#6736]
#### Environment
 - **Axios Version 0.27.2**
 - **Target platform  Browser**
 - **Adapter HTTP**
 - Additional Library/Framework Versions [Actix-web + Vue3]
 - OS: Win11

I can not get the response data when the status code is 400 or 403 with axios?
It can get the response data in 200, why not in 4xx?

BUT I can get the response data by the POSTMAN in the same REQUEST in 4xx.

```
const service = axios.create({
  baseURL: API_BASE_URL,
  // withCredentials: false
});
service.interceptors.response.use(
  (res) => {
    return res;
  },
  (error) => {
    console.log('error',error.response.data)     # THAT IS UNDEFINED
    return Promise.reject(error);
  }
);
```

 
![image](https://github.com/user-attachments/assets/40bc717f-d02c-4658-b422-3d02c640916e)

**Comment by monterey01** [comment]
Hi @TQLeung , 

Thank you for submitting the issue. Just to be clear, I am not an official contributor to this open source project. I was interested in this bug and did some testing to try to reproduce this bug.

I was not **able to reproduce this bug**. Here is what I did to reproduce this bug.

1. Created a [REST API ](https://14a16e90d8f949ca8c9e1243e18a4a97.api.mockbin.io/)that returns a 400 error code. The REST API is publicly available without any AuthN/AuthZ credentials needed. The response data is { validationError: 'First Name Field not provided' }"

2. Created a sample code using node js 20 to recreate the bug  with axios version V 0.27.2.

```async function fireRequestGit() {
  service.interceptors.response.use(
    (res) => {
      console.log(res);
    },
    (error) => {
      console.log('error', error.response.data);
      return Promise.reject(error);
    }
  );

  service.get('/')
    .then((response) => {
      console.log(response);
    })
    .catch((error) => {
      console.error(error);
    });
}

fireRequestGit();
```



3. I ran the code and saw that axios returned the 400 error back correctly with the response data. The response service interceptor printed the error correctly. The code went into this line  ```console.log('error', error.response.data);``` and printed the error out error " { validationError: 'First Name Field not provided' }". 

The code also printed this line out    console.error(error) in the error handler of the get call . That line showed the entire error object

```
AxiosError: Request failed with status code 400
    at settle (/Users/sajnana/workspaces/teams-subscriptions-lambda/node_modules/axios/dist/node/axios.cjs:2019:12)
    at IncomingMessage.handleStreamEnd (/Users/sajnana/workspaces/teams-subscriptions-lambda/node_modules/axios/dist/node/axios.cjs:3135:11)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/Users/sajnana/workspaces/teams-subscriptions-lambda/node_modules/axios/dist/node/axios.cjs:4287:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': undefined,
      'User-Agent': 'axios/1.7.7',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    baseURL: 'https://14a16e90d8f949ca8c9e1243e18a4a97.api.mockbin.io/',
    method: 'get',
    url: '/',
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: true,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: '14a16e90d8f949ca8c9e1243e18a4a97.api.mockbin.io',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: '14a16e90d8f949ca8c9e1243e18a4a97.api.mockbin.io',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _writableState: [WritableState],
      allowHalfOpen: false,
      _maxListeners: undefined,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      timeout: 5000,
      parser: null,
      _httpMessage: null,
      autoSelectFamilyAttemptedAddresses: [Array],
      [Symbol(alpncallback)]: null,
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: -1,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 5000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 596,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 25,
        [Symbol(triggerId)]: 23
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 1,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'GET / HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'User-Agent: axios/1.7.7\r\n' +
      'Accept-Encoding: gzip, compress, deflate, br\r\n' +
      'Host: 14a16e90d8f949ca8c9e1243e18a4a97.api.mockbin.io\r\n' +
      'Connection: keep-alive\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype] {},
      freeSockets: [Object: null prototype],
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/',
    _ended: true,
    res: IncomingMessage {
      _events: [Object],
      _readableState: [ReadableState],
      _maxListeners: undefined,
      socket: null,
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 400,
      statusMessage: 'Bad Request',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      _eventsCount: 4,
      responseUrl: 'https://14a16e90d8f949ca8c9e1243e18a4a97.api.mockbin.io/',
      redirects: [],
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 26,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: '14a16e90d8f949ca8c9e1243e18a4a97.api.mockbin.io',
    protocol: 'https:',
    _redirectable: Writable {
      _events: [Object],
      _writableState: [WritableState],
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _eventsCount: 3,
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://14a16e90d8f949ca8c9e1243e18a4a97.api.mockbin.io/',
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false
    },
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      'accept-encoding': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kHighWaterMark)]: 16384,
    [Symbol(kRejectNonStandardBodyWrites)]: false,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 400,
    statusText: 'Bad Request',
    headers: Object [AxiosHeaders] {
      date: 'Tue, 07 Jan 2025 22:51:16 GMT',
      'content-type': 'application/json',
      'content-length': '56',
      connection: 'keep-alive',
      'cache-control': 'no-cache',
      'zp-rid': '9cc7f0d9-50a6-4704-87cc-a4af924fcfa6',
      vary: 'Accept-Encoding',
      'cf-cache-status': 'DYNAMIC',
      'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=gRt0O88h0iK5oBkHuu7R41gPZXL%2BkHG0uUjTtJC3XBi6DEZcRFfZAJPu%2BJyvSm3u26pjxpqpeSNe%2Fje6y2CkSebdqormxSBNLJVCbHVQE9hjF41o6PE4ct13aMsbz%2FvZNj0U1LWiiNqafzYECBBkZNmBqWSN5QdULAHWO07WNJnZxXKE0KIojsk1Rlsg"}],"group":"cf-nel","max_age":604800}',
      nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
      server: 'cloudflare',
      'cf-ray': '8fe782f44eb8232c-SJC',
      'server-timing': 'cfL4;desc="?proto=TCP&rtt=9944&min_rtt=5812&rtt_var=9174&sent=5&recv=5&lost=0&retrans=0&sent_bytes=2840&recv_bytes=718&delivery_rate=463867&cwnd=252&unsent_bytes=0&cid=f982cf695c26f7b8&ts=452&x=0"'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      baseURL: 'https://14a16e90d8f949ca8c9e1243e18a4a97.api.mockbin.io/',
      method: 'get',
      url: '/',
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: [TLSSocket],
      _header: 'GET / HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.7.7\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: 14a16e90d8f949ca8c9e1243e18a4a97.api.mockbin.io\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '14a16e90d8f949ca8c9e1243e18a4a97.api.mockbin.io',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: { validationError: 'First Name Field not provided' }
  },
  status: 400
}
```
4. Side Note- You seem to be using an old version of axios V 0.27.2. I would recommend that you upgrade you to v1.7.x .

**Comment by jasonsaayman** [comment]
hi, i doubt this is an axios issue and rather either api side or something else which we cannot diagnose.
